### PR TITLE
[18GB] receivership corps can't lease a train if there are none

### LINKED ISSUE #9877: [18GB] game stuck w/ error: undefined method `owner' for nil"
Game will not load

(https://18xx.games/game/136880?action=830)

game will not load. We were in final round. 18GB- so it ends when there are no trains to buy or when you get a stock to the top of the track.
We had two companies which did not have CEO's and it was time for one to run. It went into the NPC's turn and would no longer load the game.

I am using Safari.

### PR DESCRIPTION
**Pull request by benjaminxscott**
Fixes #9877

### Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [NA] Add the `pins` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### Implementation Notes

If a corp in receivership would have to lease a train but there are none, it doesn't get to lease one at all

This should be a no-op in practice, as the game ends soon after the final train is purchased - and receivership corps just withhold to buy a train anyway (which never happens as there are none)

Shouldn't require pins as this PR handles an edge case that would have broken existing games

See linked older PR for more details

### CODE REVIEW

File: lib/engine/game/g_18_gb/game.rb [hunk 1]
```diff
@@ -720,7 +720,7 @@ def legal_tile_rotation?(_entity, _hex, tile)
         def route_trains(entity)
           return super unless insolvent?(entity)
 
-          [@depot.min_depot_train]
+          @depot.upcoming.any? ? [@depot.min_depot_train] : []
```
Comment (ollybh) [inline lib/engine/game/g_18_gb/game.rb:723]: `Array.any?` (and `Array.none?`) shouldn't be used without a code block testing the array elements. To test whether an array has any elements you should use `Array.empty?`.
```suggestion
          @depot.upcoming.empty? ? [] : [@depot.min_depot_train]
```
