### PR TITLE
1873: rounding issue on half dividend withholds

### LINKED ISSUE #5876: [Harzbahn 1873] Profit distribution is rounding incorrectly
Hotseat: https://gist.github.com/physic/9ea72a741f49691608ea6d789e9026e5

action=198

Rounding is never performed for monies withheld.
Rounding is performed after calculating the total dividend to a player.

See 4.3.2 Profit Distribution
> The director determines whether the profit is withheld,
> half distributed or completely distributed. When withheld,
> the bank pays the entire profit into the company’s
> treasury. In the case of half distribution, the bank pays
> half of the profit to the company’s treasury and the other
> half is distributed to the shareholders. Dividends are paid
> to the shareholders according to their respective shares in
> the company. If the distribution amount for a player is not
> an integer, the bank rounds in favour of the player to the
> next whole number.

Scenario: 2-share HW runs for 230 and pays half.
Expected:
The company receives **$115**.
A player with one share receives $57.5 rounded up = $58.
A player with both shares receives **$115**, no rounding.

Observed:
The company receives **$114**.
A player with one share receives $58.
A player with both shares receives **$116**.

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #5876 

This seemingly minor change (+/- 1M to players/corps) killed two of my hotseat tests.

### CODE REVIEW

File: lib/engine/game/g_1873/step/dividend.rb [hunk 1]
```diff
@@ -155,6 +155,10 @@ def payout_shares(entity, revenue)
             @log << "#{entity.owner.name} receives #{@game.format_currency(revenue)}"
             @game.bank.spend(revenue, entity.owner)
           end
+
+          def half_pay_withhold_amount(_entity, revenue)
+            revenue / 2
```
Comment (tobymao) [inline lib/engine/game/g_1873/step/dividend.rb:160]: does this work in ruby and javascript?

Comment (roseundy) [reply lib/engine/game/g_1873/step/dividend.rb:160]: It should (at least for 1873) since the revenue is always even.
