### PR TITLE
[18Norway] Nationalization rounds should not pay out companies

### LINKED ISSUE #11732: [18Norway] privates pay i Nationalization round
**What's your Game ID?**
207515

**How to Reproduce the Bug?**

**Which Browser / Platform?**

### PR DESCRIPTION
**Pull request by patrikolesen**
Fixes #11732

Will break existing games

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [ ] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### CODE REVIEW

File: lib/engine/game/g_18_norway/steps/nationalize_corporation.rb [hunk 1]
```diff
@@ -12,6 +12,7 @@ def description
           def actions(entity)
             return [] if !entity.corporation? || entity != current_entity
             return [] if @game.nationalized?(entity.corporation)
+            return [] if @game.round.is_a?(G18Norway::Round::Nationalization) && @game.round.nationalization_complete
```
Comment (ollybh) [inline lib/engine/game/g_18_norway/steps/nationalize_corporation.rb]: This step only exists in nationalisation rounds, so the test for the round type is pointless. And there's a `@round` variable you can use instead of `@game.round`.
```suggestion
            return [] if @round.nationalization_complete
```

File: lib/engine/game/g_18_norway/round/nationalization.rb [hunk 2]
```diff
@@ -7,6 +7,18 @@ module Game
...
       module Round
         class Nationalization < Engine::Round::Operating
+          def initialize(game, steps, **opts)
+            super
+            @nationalization_complete = false
+          end
+
+          def process_action(action)
+            super
+            @nationalization_complete = true if action.is_a?(Engine::Action::Choose) && action.choice != 'decline'
```
Comment (ollybh) [inline lib/engine/game/g_18_norway/round/nationalization.rb]: It would be better to put this in `Step::NationalizeCorporation.process_choose`.

Comment (patrikolesen) [reply lib/engine/game/g_18_norway/round/nationalization.rb]: Moved

**Review by ollybh — APPROVED** [review]
