### PR TITLE
[18CO] Fixed issue in Event: Home station reservations removed

### LINKED ISSUE #11765: [18CO] Unable to purchase 5 train
18CO Game Id: 209316

https://18xx.games/game/209316

Issue:

Player Whowhatwhere unable to purchase 5 train. 

Error message: Undefined method 'remove_reservation!' for nil

Attempted through master mode as well with no luck. 

Player IS able to purchase train from another company.

### PR DESCRIPTION
**Pull request by jakub-lore**
# [18CO] Fixed issue in Event: Home station reservations removed

Fixes #11765

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### Explanation of Change

The number of cities on tile F15 changes from 3 to 2 when tile is upgraded to green. Old code for clearing reservations tried to reach index 2 on 2-element array and then tried to call remove_reservation! on nil. 

I've changed the code to just go over all cities in hexes in question and remove all reservation for not-floated corporations

### CODE REVIEW

File: lib/engine/game/g_18_co/game.rb [hunk 1]
```diff
@@ -1390,13 +1390,15 @@ def event_unreserve_home_stations!
 
           @corporations.each do |corporation|
             next if corporation.ipoed
-
             tile = hex_by_id(corporation.coordinates).tile
-            city = tile.cities[corporation.city || 0]
-            city.remove_reservation!(corporation)
+            # When E15 tile is upgraded - the cities array on the tile has 2 elements rather than 3. 
+            # The positions of reservations reaarange, so it's safer to just iterate over all cities than to relay on original positions.
```
Comment (ollybh) [inline lib/engine/game/g_18_co/game.rb]: There are a couple of typos in this comment.
```suggestion
            # The positions of reservations rearrange, so it's safer to just iterate over all cities than to rely on original positions.
```

**Comment by jakub-lore** [comment]
Thanks @ollybh 

Everything should be fixed now

**Review by ollybh — APPROVED** [review]
