### PR TITLE
Fixes #4189

### LINKED ISSUE #4189: 18WO Question Game 30061 - Is there a bug with Nieuw Zeeland?  Seems like I never got a chance to place 2nd token, so I cannot lay track
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

### PR DESCRIPTION
**Pull request by ventusignis**
The problem was that in the case when there is no choice for the size of the IPOed corporation nor any contest for the bid the home token (NZ) gets laid AFTER attempting to purchase tokens. The fix here is to add a hook to the HomeToken step in the stock round so that the second token can be laid then
Fixes #4189

### CODE REVIEW

**Comment by michaeljb** [comment]
At the moment game 30061 is the only one affected by this. No migration is possible, so the game must be pinned. However, it has already completed, does that mean we should archive it instead? @jenf @tobymao

**Review by michaeljb — APPROVED** [review]

File: lib/engine/game/g_1817_wo/game.rb [hunk 1]
```diff
@@ -622,8 +622,16 @@ def tokenable_location_exists?
           hexes.any? { |h| h.tile.cities.any? { |c| c.tokens.count(&:nil?).positive? } }
         end
 
+        def can_place_second_token(corporation)
+          return false unless tokenable_location_exists? && corp_has_new_zealand?(corporation)
```
Comment (tobymao) [inline lib/engine/game/g_1817_wo/game.rb:626]: change to an if statement

File: lib/engine/game/g_1817_wo/game.rb [hunk 2]
```diff
@@ -622,8 +622,16 @@ def tokenable_location_exists?
...
+
+          # Does the corp have a second token already?
+          corporation.tokens[1] && corporation.tokens[1].city.nil?
```
Comment (tobymao) [inline lib/engine/game/g_1817_wo/game.rb:629]: corporation.tokens[1] && !...city

File: lib/engine/game/g_1817_wo/game.rb (hunk 1 above)
Comment (ventusignis) [reply lib/engine/game/g_1817_wo/game.rb]: Changed

File: lib/engine/game/g_1817_wo/game.rb (hunk 2 above)
Comment (ventusignis) [reply lib/engine/game/g_1817_wo/game.rb]: Changed
