### PR TITLE
make all 1868WY towns dots; fix rect towns on 1860 tiles

### LINKED ISSUE #5174: 1860 Cowes tile displays small town differently from other tiles
All of the 1860 tiles follow the convention used by the physical printing of the game, that small towns and halts are dots when they appear at a junction and perpendicular dashes when they appear along a track segment. Except for the yellow, green, and brown Cowes tile #787-789. It has a small town that appears as a black dot instead of the dash that you see on 747, 748, 749, 764, 765, 766.

The small town on tiles 787-789 should be a dash, not a dot.

### PR DESCRIPTION
**Pull request by michaeljb**
progress on #5011, fixes #5174

### CODE REVIEW

File: lib/engine/game/g_1868_wy/game.rb [hunk 1]
```diff
@@ -33,6 +33,22 @@ class Game < Game::Base
           %w[20b 30b 40o 50o 55y 60y 64 68 72],
           ['', '20b', '30b', '40o', '50o', '55y', '60y'],
         ].freeze
+
+        def init_tiles
+          tiles = super
```
Comment (tobymao) [inline lib/engine/game/g_1868_wy/game.rb:38]: super.each do 
end

may work? cuz it returns self

File: lib/engine/part/town.rb [hunk 2]
```diff
@@ -23,11 +25,13 @@ def town?
...
-      # it has any paths and either it's not in the center or it is in the center
-      # and has less than two exits and less than three paths
+      # render as a dot or rectangle; if @style is set to 'rect', then render a
+      # rectangle; if @style is set to something else, render a dot; if @style is
+      # unset, render with a rectangle if it has any paths and either it's not
+      # in the center or it is in the center and has less than two exits and
+      # less than three paths
       def rect?
-        paths.any? && paths.size < 3 && (@loc != 'center')
+        @style ? (@style == :rect) : (paths.any? && paths.size < 3)
```
Comment (tobymao) [inline lib/engine/part/town.rb:34]: !paths.empty?

**Review by tobymao — APPROVED** [review]

File: lib/engine/game/g_1868_wy/game.rb (hunk 1 above)
Comment (michaeljb) [reply lib/engine/game/g_1868_wy/game.rb:38]: ah yep, that works
