### PR TITLE
Validate correct auto actions on the server

### LINKED ISSUE #7813: Game state not fully reset after GameError for the player taking the illegal action
https://18xx.games/game/84989
Was placing a token in NY. It said the cost was $80 and failed
Placed a token in Albany and it worked but the game hung and now won't load
We have stopped playing the game, so don't need it recovered or working

### PR DESCRIPTION
**Pull request by crericha**
Fixes #7813

### CODE REVIEW

File: lib/engine/game/base.rb [hunk 1]
```diff
@@ -766,6 +773,16 @@ def maybe_raise!
         self
       end
 
+      def auto_actions_match?(a, b)
+        return false unless a.size == b.size
```
Comment (tobymao) [inline lib/engine/game/base.rb:777]: actions_a.zip(actions_b).all? do |a, b|
  a.to_h&.except('created_at') == b.to_h&.except('created_at')
end

Comment (crericha) [reply lib/engine/game/base.rb]: Fixed

**Review by tobymao — APPROVED** [review]
