### PR TITLE
Don't allow oversaturating market when force selling (fixes #321)

### LINKED ISSUE #321: App incorrectly allows selling shares so that more than 50% of a corporation is in the market during emergency fundraising
The last action here was SR buying a Diesel, funded in part by illegally selling too many KO shares. Also, the UR's purchase of the first Diesel was funded with an illegally sold AR.

```
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 1,
      "company": "Mitsubishi Ferry",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 2,
      "company": "Sumitomo Mines Railway",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 3,
      "company": "Sumitomo Mines Railway",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 4,
      "company": "Ehime Railway",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 5
    },
    {
      "type": "bid",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 6,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 7,
      "company": "Sumitomo Mines Railway",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 9,
      "company": "Dougo Railway",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "par",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 11,
      "corporation": "TR",
      "share_price": "65,5,3"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 13,
      "share": "TR_1"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 15,
      "share": "TR_2"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 17,
      "share": "TR_3"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 19,
      "hex": "G8",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 20,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 21,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 22
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 23,
      "share": "TR_4"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 26,
      "share": "TR_5"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 29,
      "share": "TR_6"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 31
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 32,
      "share": "TR_7"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 33
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 36,
      "hex": "H7",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 37,
      "city": "57-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 38,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G8",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 39,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 40,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 41,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 42,
      "shares": [
        "TR_1",
        "TR_2",
        "TR_3",
        "TR_0"
      ],
      "percent": 50
    },
    {
      "type": "par",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 43,
      "corporation": "AR",
      "share_price": "75,3,3"
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 44,
      "share": "TR_1"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 46,
      "share": "AR_1"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 47
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 48,
      "share": "TR_2"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 49
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 50,
      "share": "AR_2"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 53,
      "share": "AR_3"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 57,
      "hex": "K8",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "Mitsubishi Ferry",
      "entity_type": "company",
      "id": 58,
      "hex": "J9",
      "tile": "437-0",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 59,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 60,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 61,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 62,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "buy_company",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 63,
      "company": "Mitsubishi Ferry",
      "price": 60
    },
    {
      "type": "buy_company",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 64,
      "company": "Dougo Railway",
      "price": 120
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 65
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 66,
      "hex": "G10",
      "tile": "58-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 67,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "H7",
            "G8",
            "F9"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 68,
      "kind": "payout"
    },
    {
      "type": "buy_company",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 69,
      "company": "Sumitomo Mines Railway",
      "price": 100
    },
    {
      "type": "buy_company",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 70,
      "company": "Takamatsu E-Railroad",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 72,
      "shares": [
        "TR_6",
        "TR_7"
      ],
      "percent": 20
    },
    {
      "type": "par",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 73,
      "corporation": "KO",
      "share_price": "65,5,3"
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 74,
      "share": "AR_4"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 75
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 76,
      "share": "KO_1"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 77
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 78,
      "share": "TR_3"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 80,
      "share": "KO_2"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 82,
      "share": "TR_4"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 83
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 84,
      "share": "KO_3"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 85
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 86,
      "share": "TR_5"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 90,
      "hex": "J11",
      "tile": "5-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 91,
      "city": "5-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 92,
      "routes": [
        {
          "train": "2-4",
          "hexes": [
            "L7",
            "K8"
          ]
        },
        {
          "train": "2-5",
          "hexes": [
            "K8",
            "J9"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "J9",
            "J11"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 93,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 94
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 95,
      "hex": "J3",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 96,
      "train": "2-0",
      "price": 2
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 97,
      "train": "2-1",
      "price": 158
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 98,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 101,
      "hex": "I6",
      "tile": "8-1",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 102,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "H7",
            "G8",
            "F9"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 103,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 104,
      "train": "3-3",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 107,
      "hex": "K8",
      "tile": "205-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 108,
      "routes": [
        {
          "train": "2-4",
          "hexes": [
            "L7",
            "K8"
          ]
        },
        {
          "train": "2-5",
          "hexes": [
            "K8",
            "J9"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "J9",
            "J11"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 109,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 111,
      "hex": "I4",
      "tile": "438-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 112
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 113,
      "routes": [
        {
          "train": "3-2",
          "hexes": [
            "K4",
            "J3",
            "I4",
            "I6",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 114,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 115
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 117,
      "hex": "H7",
      "tile": "15-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 118
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 119,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "G10",
            "F9"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "F9",
            "G8",
            "H7"
          ]
        },
        {
          "train": "3-3",
          "hexes": [
            "H7",
            "I6",
            "I4",
            "J3",
            "K4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 120,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 121,
      "train": "2-0",
      "price": 254
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 122,
      "shares": [
        "TR_1",
        "TR_2",
        "TR_0"
      ],
      "percent": 30
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 123,
      "share": "KO_4"
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 124,
      "share": "TR_7"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 125
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 126,
      "share": "AR_5"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 127
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 128,
      "share": "TR_1"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 129
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 130,
      "share": "AR_6"
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 131,
      "shares": [
        "AR_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 132
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 133,
      "share": "TR_2"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 134
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 135
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 136,
      "share": "TR_3"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 137
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 138
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 139,
      "share": "TR_4"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 140
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 141
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 142,
      "share": "KO_5"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 143
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 144
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 145
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 146,
      "hex": "I10",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 147,
      "routes": [
        {
          "train": "2-4",
          "hexes": [
            "L7",
            "K8"
          ]
        },
        {
          "train": "2-5",
          "hexes": [
            "K8",
            "J9"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "J11",
            "J9"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 148,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 149
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 150,
      "hex": "J5",
      "tile": "58-1",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 151,
      "city": "438-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 152,
      "routes": [
        {
          "train": "3-2",
          "hexes": [
            "I4",
            "J3",
            "K4",
            "J5"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "I4",
            "I6",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 153,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 154
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 155
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 156,
      "hex": "G12",
      "tile": "57-1",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 157,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "I4",
            "I6",
            "H7"
          ]
        },
        {
          "train": "3-3",
          "hexes": [
            "F9",
            "G10",
            "G12"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "H7",
            "G8",
            "F9"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 158,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 159
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 160,
      "hex": "I8",
      "tile": "8-3",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 161,
      "routes": [
        {
          "train": "2-4",
          "hexes": [
            "L7",
            "K8"
          ]
        },
        {
          "train": "2-5",
          "hexes": [
            "K8",
            "J9"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "J9",
            "J11"
          ]
        },
        {
          "train": "3-1",
          "hexes": [
            "K8",
            "J7",
            "I8",
            "I10",
            "J11"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 162,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 163
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 164,
      "hex": "E8",
      "tile": "8-4",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 165,
      "routes": [
        {
          "train": "3-2",
          "hexes": [
            "I4",
            "I6",
            "H7",
            "G8",
            "F9"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "I4",
            "J3",
            "K4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 166,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 167
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 168
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 169,
      "hex": "G12",
      "tile": "206-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 170,
      "city": "206-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 171,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "H7",
            "I6",
            "I4"
          ]
        },
        {
          "train": "2-0",
          "hexes": [
            "H7",
            "G8",
            "F9"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "G12",
            "G14"
          ]
        },
        {
          "train": "3-3",
          "hexes": [
            "G12",
            "G10",
            "F9"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 172,
      "kind": "payout"
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 173,
      "shares": [
        "TR_6"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 174,
      "corporation": "IR",
      "share_price": "80,2,3"
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 175,
      "shares": [
        "TR_5",
        "TR_7"
      ],
      "percent": 20
    },
    {
      "type": "par",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 176,
      "corporation": "UR",
      "share_price": "100,0,3"
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 177,
      "share": "IR_2"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 178
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 179,
      "share": "UR_1"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 180
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 181,
      "share": "IR_3"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 182
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 183,
      "share": "UR_2"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 184
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 185,
      "share": "IR_1"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 186
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 187,
      "share": "UR_3"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 188
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 189
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 190,
      "share": "UR_4"
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 191,
      "shares": [
        "UR_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 192
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 193
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 194,
      "share": "IR_4"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 195
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 196
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 197,
      "share": "IR_5"
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 198,
      "shares": [
        "IR_4",
        "IR_5"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 199
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 200
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 201,
      "share": "KO_6"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 202
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 203
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 204,
      "share": "KO_7"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 205
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 206
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 207,
      "share": "KO_8"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 208
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 209
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 210
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 211,
      "hex": "I8",
      "tile": "25-0",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 212,
      "routes": [
        {
          "train": "2-4",
          "hexes": [
            "L7",
            "K8"
          ]
        },
        {
          "train": "2-5",
          "hexes": [
            "K8",
            "J9"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "J9",
            "J11"
          ]
        },
        {
          "train": "3-1",
          "hexes": [
            "K8",
            "J7",
            "I8",
            "I10",
            "J11"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 213,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 214
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 215,
      "hex": "C8",
      "tile": "9-1",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 216,
      "train": "2-4",
      "price": 112
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 217,
      "train": "3-3",
      "price": 60
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 218,
      "train": "3-4",
      "price": 180
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 219,
      "train": "4-0",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 220
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 221,
      "hex": "K4",
      "tile": "440-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 222,
      "routes": [
        {
          "train": "3-2",
          "hexes": [
            "K4",
            "J3",
            "I4",
            "I6",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 223,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 224,
      "train": "4-1",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 225
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 226
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 227,
      "hex": "E2",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 228,
      "train": "4-2",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 229
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 230
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 231,
      "hex": "I4",
      "tile": "439-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 232,
      "train": "3-3",
      "price": 1
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 233,
      "hex": "J11",
      "tile": "12-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 234,
      "routes": [
        {
          "train": "3-0",
          "hexes": [
            "L7",
            "K8",
            "J9"
          ]
        },
        {
          "train": "3-1",
          "hexes": [
            "K8",
            "J7",
            "I8",
            "I10",
            "J11",
            "J9"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 235,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 236
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 237
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 238,
      "hex": "H3",
      "tile": "8-3",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 239,
      "routes": [
        {
          "train": "4-1",
          "hexes": [
            "I4",
            "I6",
            "H7",
            "G8",
            "F9",
            "G10"
          ]
        },
        {
          "train": "3-2",
          "hexes": [
            "I4",
            "J3",
            "K4",
            "J5"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 240,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 241
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 242
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 243,
      "hex": "B5",
      "tile": "9-2",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 244
    },
    {
      "type": "run_routes",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 245,
      "routes": [
        {
          "train": "3-4",
          "hexes": [
            "C4",
            "B3",
            "B5",
            "B7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 246,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 247,
      "train": "3-0",
      "price": 356
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 248,
      "hex": "D3",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "buy_company",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 249,
      "company": "Ehime Railway",
      "price": 50
    },
    {
      "type": "lay_tile",
      "entity": "Ehime Railway",
      "entity_type": "company",
      "id": 250,
      "hex": "C4",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 251,
      "routes": [
        {
          "train": "4-2",
          "hexes": [
            "E2",
            "D3",
            "C4",
            "B3",
            "B5",
            "B7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 252,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 253
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 254,
      "hex": "I6",
      "tile": "29-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 255,
      "routes": [
        {
          "train": "3-3",
          "hexes": [
            "I4",
            "I6",
            "H7",
            "G8",
            "F9"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 256,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 257
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 258,
      "shares": [
        "AR_6"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 259,
      "corporation": "SR",
      "share_price": "100,0,3"
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 260,
      "shares": [
        "TR_1"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 261,
      "corporation": "KU",
      "share_price": "100,0,3"
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 262,
      "share": "SR_1"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 263
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 264,
      "share": "KU_1"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 265
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 266,
      "share": "SR_2"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 267
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 268,
      "share": "KU_2"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 269
    },
    {
      "type": "buy_share",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 270,
      "share": "SR_3"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 271
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 272,
      "share": "KU_3"
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 273
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 274
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 275,
      "shares": [
        "KO_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 276,
      "share": "SR_4"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 277
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 278,
      "shares": [
        "SR_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_share",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 279,
      "share": "IR_4"
    },
    {
      "type": "pass",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 280
    },
    {
      "type": "pass",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 281
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 282,
      "hex": "H3",
      "tile": "23-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 283,
      "routes": [
        {
          "train": "4-1",
          "hexes": [
            "I4",
            "I6",
            "H7",
            "G8",
            "F9",
            "G10"
          ]
        },
        {
          "train": "3-2",
          "hexes": [
            "I4",
            "J3",
            "K4",
            "J5"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 284,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 285,
      "train": "4-3",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 286
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 287,
      "routes": [
        {
          "train": "3-1",
          "hexes": [
            "K8",
            "J9",
            "J11"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 288,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 289,
      "train": "3-3",
      "price": 260
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 290,
      "train": "5-0",
      "price": 450
    },
    {
      "type": "discard_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 291,
      "train": "3-4"
    },
    {
      "type": "discard_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 292,
      "train": "3-1"
    },
    {
      "type": "discard_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 293,
      "train": "3-2"
    },
    {
      "type": "lay_tile",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 294,
      "hex": "C10",
      "tile": "5-1",
      "rotation": 3
    },
    {
      "type": "buy_train",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 295,
      "train": "5-1",
      "price": 450
    },
    {
      "type": "buy_train",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 296,
      "train": "5-2",
      "price": 450
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 297,
      "hex": "D9",
      "tile": "8-1",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 298,
      "routes": [
        {
          "train": "4-0",
          "hexes": [
            "B7",
            "C8",
            "D9",
            "E8",
            "F9",
            "G8",
            "H7",
            "I6",
            "I4"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "B7",
            "B5",
            "B3",
            "C4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 299,
      "kind": "withhold"
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 300,
      "hex": "I2",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 301,
      "train": "6-0",
      "price": 630
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 302,
      "train": "4-1",
      "price": 369
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 303,
      "hex": "B5",
      "tile": "23-1",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 304,
      "city": "B7-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 305,
      "routes": [
        {
          "train": "4-2",
          "hexes": [
            "B7",
            "C8",
            "D9",
            "E8",
            "F9",
            "G8",
            "H7",
            "I6",
            "I4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 306,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 307,
      "train": "6-0",
      "price": 457
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 308,
      "hex": "I4",
      "tile": "492-0",
      "rotation": 1
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 309,
      "shares": [
        "IR_4"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 310,
      "shares": [
        "KO_6",
        "KO_7"
      ],
      "percent": 20
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 311,
      "train": "6-1",
      "price": 630
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 312,
      "hex": "H7",
      "tile": "611-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 313,
      "routes": [
        {
          "train": "5-0",
          "hexes": [
            "L7",
            "K8",
            "J7",
            "I8",
            "H7",
            "I6",
            "I4",
            "J3",
            "K4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 314,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 315,
      "train": "5-1",
      "price": 1
    },
    {
      "type": "lay_tile",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 316,
      "hex": "C10",
      "tile": "15-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 317,
      "routes": []
    },
    {
      "type": "buy_train",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 318,
      "train": "4-0",
      "price": 21
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 319,
      "hex": "I2",
      "tile": "15-2",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 320,
      "routes": [
        {
          "train": "4-3",
          "hexes": [
            "J1",
            "I2",
            "I4",
            "I6",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 321,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 322
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 323,
      "hex": "F9",
      "tile": "465-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 324
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 325,
      "shares": [
        "KU_1",
        "KU_2",
        "KU_3"
      ],
      "percent": 30
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 326,
      "shares": [
        "KO_8"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "michaeljb",
      "entity_type": "player",
      "id": 327,
      "shares": [
        "AR_1",
        "AR_2",
        "AR_3",
        "AR_4"
      ],
      "percent": 40
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 328,
      "train": "D-0",
      "price": 1100
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 329,
      "hex": "I2",
      "tile": "448-0",
      "rotation": 4
    },
    {
      "type": "place_token",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 330,
      "city": "611-0-0",
      "slot": 1
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 331,
      "shares": [
        "KO_1",
        "KO_2",
        "KO_3",
        "KO_4"
      ],
      "percent": 40
    },
    {
      "type": "sell_shares",
      "entity": "tripled728",
      "entity_type": "player",
      "id": 332,
      "shares": [
        "SR_1",
        "SR_2"
      ],
      "percent": 20
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 333,
      "train": "D-1",
      "price": 1100
    }
  ],
  "id": "hs_1588869248",
  "description": "Cloned from game 688",
  "user": {
    "id": 0,
    "name": "You"
  },
  "players": [
    {
      "id": 97,
      "name": "michaeljb"
    },
    {
      "id": 760,
      "name": "tripled728"
    }
  ],
  "max_players": 2,
  "title": "1889",
  "settings": {
    "seed": 2.4579973358026638e+38
  },
  "turn": 7,
  "round": "Operating Round",
  "acting": [
    760
  ],
  "result": {},
  "created_at": "2020-05-7",
  "updated_at": "2020-05-7",
  "mode": "hotseat"
}
```

### PR DESCRIPTION
**Pull request by dfannius**

### CODE REVIEW

File: lib/engine/round/operating.rb [hunk 1]
```diff
@@ -129,22 +129,28 @@ def can_act?(entity)
...
+        # Can only sell as much as you need to afford the train
         player = bundle.owner
         total_cash = bundle.price + player.cash + @current_entity.cash
         return false if total_cash >= @depot.min_depot_price + bundle.price_per_share
 
+        # Can't swap presidency
         corporation = bundle.corporation
-        # can't swap presidency
-        return true unless corporation.president?(player)
+        if corporation.president?(player)
```
Comment (HQ063) [inline lib/engine/round/operating.rb:142]: Isn't this case already covered by line 133?
