### PR TITLE
1867 bugs

### LINKED ISSUE #3110: [1867] Stray log at end of auction
Why does the log say the C&SL is up for auction again at the end of the initial auction?

{
  "id": 21288,
  "description": "Bug Hunting + Fast Async + DBAD",
  "user": {
    "id": 606,
    "name": "SmithInMN"
  },
  "players": [
    {
      "id": 1269,
      "name": "Larryp1960"
    },
    {
      "id": 4491,
      "name": "brendanm (+10:30)"
    },
    {
      "id": 606,
      "name": "SmithInMN"
    }
  ],
  "max_players": 3,
  "title": "1867",
  "settings": {
    "seed": 1444359027,
    "unlisted": false,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Stock Round",
  "acting": [
    1269
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": 1269,
      "entity_type": "player",
      "id": 1,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "bid",
      "entity": 4491,
      "entity_type": "player",
      "id": 2,
      "company": "C&SL",
      "price": 25
    },
    {
      "type": "pass",
      "entity": 606,
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "pass",
      "entity": 1269,
      "entity_type": "player",
      "id": 4
    },
    {
      "type": "bid",
      "entity": 606,
      "entity_type": "player",
      "id": 5,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "bid",
      "entity": 1269,
      "entity_type": "player",
      "id": 6,
      "company": "NFB",
      "price": 35
    },
    {
      "type": "bid",
      "entity": 4491,
      "entity_type": "player",
      "id": 7,
      "company": "NFB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": 606,
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "pass",
      "entity": 1269,
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "bid",
      "entity": 606,
      "entity_type": "player",
      "id": 10,
      "company": "MB",
      "price": 40
    },
    {
      "type": "bid",
      "entity": 1269,
      "entity_type": "player",
      "id": 11,
      "company": "MB",
      "price": 45
    },
    {
      "id": 12,
      "type": "bid",
      "price": 50,
      "entity": 4491,
      "company": "MB",
      "entity_type": "player",
      "user": 4491,
      "created_at": 1609905131
    },
    {
      "id": 13,
      "type": "undo",
      "entity": 606,
      "entity_type": "player",
      "user": 4491,
      "created_at": 1609905140
    },
    {
      "type": "bid",
      "entity": 4491,
      "entity_type": "player",
      "id": 14,
      "company": "MB",
      "price": 60
    },
    {
      "type": "bid",
      "entity": 606,
      "entity_type": "player",
      "id": 15,
      "company": "MB",
      "price": 65
    },
    {
      "id": 16,
      "type": "bid",
      "price": 70,
      "entity": 1269,
      "company": "MB",
      "entity_type": "player",
      "user": 1269,
      "created_at": 1609906235
    },
    {
      "id": 17,
      "type": "undo",
      "entity": 4491,
      "entity_type": "player",
      "user": 1269,
      "created_at": 1609906274
    },
    {
      "type": "pass",
      "entity": 1269,
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": 4491,
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "bid",
      "entity": 1269,
      "entity_type": "player",
      "id": 20,
      "company": "QB",
      "price": 50
    },
    {
      "type": "bid",
      "entity": 4491,
      "entity_type": "player",
      "id": 21,
      "company": "QB",
      "price": 60
    },
    {
      "id": 22,
      "type": "bid",
      "price": 65,
      "entity": 606,
      "company": "QB",
      "entity_type": "player",
      "user": 606,
      "created_at": 1609927908
    },
    {
      "id": 23,
      "type": "undo",
      "entity": 1269,
      "entity_type": "player",
      "user": 606,
      "created_at": 1609927956
    },
    {
      "type": "bid",
      "entity": 606,
      "entity_type": "player",
      "id": 24,
      "company": "QB",
      "price": 70
    },
    {
      "id": 25,
      "type": "pass",
      "entity": 1269,
      "entity_type": "player",
      "user": 1269,
      "created_at": 1609938330
    },
    {
      "id": 26,
      "type": "undo",
      "entity": 4491,
      "entity_type": "player",
      "user": 1269,
      "created_at": 1609938341
    },
    {
      "type": "bid",
      "entity": 1269,
      "entity_type": "player",
      "id": 27,
      "company": "QB",
      "price": 75
    },
    {
      "type": "pass",
      "entity": 4491,
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "bid",
      "entity": 606,
      "entity_type": "player",
      "id": 29,
      "company": "QB",
      "price": 80
    },
    {
      "type": "pass",
      "entity": 1269,
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "bid",
      "entity": 1269,
      "entity_type": "player",
      "id": 31,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "bid",
      "entity": 4491,
      "entity_type": "player",
      "id": 32,
      "company": "SCT",
      "price": 65
    },
    {
      "type": "pass",
      "entity": 606,
      "entity_type": "player",
      "id": 33
    },
    {
      "type": "pass",
      "entity": 1269,
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "bid",
      "entity": 606,
      "entity_type": "player",
      "id": 35,
      "corporation": "CA",
      "price": 120
    },
    {
      "type": "place_token",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 36,
      "city": "O7-2-0",
      "slot": 0
    }
  ],
  "loaded": true,
  "created_at": 1609822755,
  "updated_at": 1609971368
}

### LINKED ISSUE #3184: [1867] Clicking "Merger" automatically chooses another company owned by the active player.
Trying to create a merger with two companies owned by different players. Click on the other company, then Merge, and the system instead adds the active player's other company to the merger, not the intended company.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1610257428,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1610257436
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1610257438
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 4,
      "created_at": 1610257439
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "created_at": 1610257443,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "created_at": 1610257444
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 7,
      "created_at": 1610257445
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "created_at": 1610257446
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "created_at": 1610257447,
      "company": "MB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 10,
      "created_at": 1610257449
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "created_at": 1610257449
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "created_at": 1610257450
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 13,
      "created_at": 1610257451,
      "company": "QB",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "created_at": 1610257452
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "created_at": 1610257453
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "created_at": 1610257453
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "created_at": 1610257455,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "created_at": 1610257456
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "created_at": 1610257456
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 20,
      "created_at": 1610257457
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21,
      "created_at": 1610257527,
      "corporation": "BO",
      "price": 220
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 22,
      "created_at": 1610257529,
      "city": "J12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 23,
      "created_at": 1610257565
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 24,
      "created_at": 1610257566
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25,
      "created_at": 1610257571,
      "corporation": "BO",
      "price": 235
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 26,
      "created_at": 1610257572
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 27,
      "created_at": 1610257584,
      "corporation": "CS",
      "price": 200
    },
    {
      "type": "place_token",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 28,
      "created_at": 1610257589,
      "city": "E17-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 29,
      "created_at": 1610257594
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 30,
      "created_at": 1610257594
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "created_at": 1610257613,
      "corporation": "CV",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 32,
      "created_at": 1610257619,
      "city": "L12-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 33,
      "created_at": 1610257623
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 34,
      "created_at": 1610257626,
      "corporation": "KP",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1610257628,
      "city": "L12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 36,
      "created_at": 1610257640
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37,
      "created_at": 1610257656,
      "corporation": "OP",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 38,
      "created_at": 1610257667,
      "city": "F16-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 39,
      "created_at": 1610257670
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 40,
      "created_at": 1610257674,
      "corporation": "TN",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 41,
      "created_at": 1610257680,
      "city": "D16-1-0",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 42,
      "created_at": 1610257694,
      "hex": "J12",
      "tile": "201-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1610257707
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1610257709,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1610257710,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1610257714
    },
    {
      "type": "undo",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1610257727
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 48,
      "created_at": 1610257738,
      "hex": "E17",
      "tile": "201-1",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1610257746
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 50,
      "created_at": 1610257747,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1610257748,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1610257756,
      "hex": "L10",
      "tile": "3-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1610257765
    },
    {
      "type": "buy_train",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1610257766,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1610257775,
      "hex": "K13",
      "tile": "58-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 56,
      "created_at": 1610257780
    },
    {
      "type": "buy_train",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 57,
      "created_at": 1610257794,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1610257807,
      "hex": "G15",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 59,
      "created_at": 1610257814
    },
    {
      "type": "buy_train",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 60,
      "created_at": 1610257822,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1610257835,
      "hex": "D16",
      "tile": "621-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 62,
      "created_at": 1610257844
    },
    {
      "type": "buy_train",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 63,
      "created_at": 1610257850,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1610257888,
      "hex": "K11",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 65,
      "created_at": 1610257902
    },
    {
      "type": "run_routes",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 66,
      "created_at": 1610257915,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L10",
              "L12"
            ],
            [
              "J12",
              "K11",
              "L10"
            ]
          ],
          "hexes": [
            "L12",
            "L10",
            "J12"
          ],
          "revenue": 70,
          "revenue_str": "L12-L10-J12"
        },
        {
          "train": "2-1",
          "connections": [
            [
              "K13",
              "L12"
            ],
            [
              "J12",
              "K13"
            ]
          ],
          "hexes": [
            "L12",
            "K13",
            "J12"
          ],
          "revenue": 70,
          "revenue_str": "L12-K13-J12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1610257923
    },
    {
      "type": "run_routes",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 68,
      "created_at": 1610257932,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E17",
              "F16"
            ]
          ],
          "hexes": [
            "F16",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "F16-E17"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E17",
              "F18"
            ]
          ],
          "hexes": [
            "F18",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "F18-E17"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 69,
      "created_at": 1610257939
    },
    {
      "type": "run_routes",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 70,
      "created_at": 1610257946,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "L10",
              "K11",
              "J12"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "J12",
            "L10",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 71,
      "created_at": 1610257950
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1610257954
    },
    {
      "type": "run_routes",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 73,
      "created_at": 1610257959,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K13",
              "J12"
            ],
            [
              "L12",
              "K13"
            ]
          ],
          "hexes": [
            "J12",
            "K13",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-K13-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1610257973
    },
    {
      "type": "lay_tile",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 75,
      "created_at": 1610257981,
      "hex": "H14",
      "tile": "4-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 76,
      "created_at": 1610257984
    },
    {
      "type": "run_routes",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 77,
      "created_at": 1610257989,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "F16",
              "G15"
            ]
          ],
          "hexes": [
            "G15",
            "F16"
          ],
          "revenue": 50,
          "revenue_str": "G15-F16"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 78,
      "created_at": 1610257993
    },
    {
      "type": "lay_tile",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 79,
      "created_at": 1610258002,
      "hex": "E15",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 80,
      "created_at": 1610258005
    },
    {
      "type": "run_routes",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 81,
      "created_at": 1610258011,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "D16",
              "E15"
            ]
          ],
          "hexes": [
            "E15",
            "D16"
          ],
          "revenue": 50,
          "revenue_str": "E15-D16"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 82,
      "created_at": 1610258013
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 83,
      "created_at": 1610258034,
      "corporation": "AE",
      "price": 150
    },
    {
      "type": "place_token",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 84,
      "created_at": 1610258042,
      "city": "57-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 85,
      "created_at": 1610258046
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 86,
      "created_at": 1610258046
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 87,
      "created_at": 1610258047
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 88,
      "created_at": 1610258062,
      "corporation": "CA",
      "price": 150
    },
    {
      "type": "place_token",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 89,
      "created_at": 1610258074,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 90,
      "created_at": 1610258078
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 91,
      "created_at": 1610258079
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 92,
      "created_at": 1610258092,
      "corporation": "NO",
      "price": 150
    },
    {
      "type": "place_token",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 93,
      "created_at": 1610258099,
      "city": "O7-2-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 94,
      "created_at": 1610258103
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 95,
      "created_at": 1610258118,
      "corporation": "PM",
      "price": 150
    },
    {
      "type": "place_token",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 96,
      "created_at": 1610258125,
      "city": "M9-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 97,
      "created_at": 1610258138
    },
    {
      "type": "run_routes",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 98,
      "created_at": 1610258140,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L10",
              "L12"
            ],
            [
              "J12",
              "K11",
              "L10"
            ]
          ],
          "hexes": [
            "L12",
            "L10",
            "J12"
          ],
          "revenue": 70,
          "revenue_str": "L12-L10-J12"
        },
        {
          "train": "2-1",
          "connections": [
            [
              "K13",
              "L12"
            ],
            [
              "J12",
              "K13"
            ]
          ],
          "hexes": [
            "L12",
            "K13",
            "J12"
          ],
          "revenue": 70,
          "revenue_str": "L12-K13-J12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 99,
      "created_at": 1610258143
    },
    {
      "type": "run_routes",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 100,
      "created_at": 1610258148,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E17",
              "F16"
            ]
          ],
          "hexes": [
            "E17",
            "F16"
          ],
          "revenue": 60,
          "revenue_str": "E17-F16"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E17",
              "F18"
            ]
          ],
          "hexes": [
            "E17",
            "F18"
          ],
          "revenue": 60,
          "revenue_str": "E17-F18"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 101,
      "created_at": 1610258158,
      "hex": "I13",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 102,
      "created_at": 1610258161
    },
    {
      "type": "buy_train",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 103,
      "created_at": 1610258163,
      "train": "2-8",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 104,
      "created_at": 1610258167
    },
    {
      "type": "lay_tile",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 105,
      "created_at": 1610258175,
      "hex": "F14",
      "tile": "7-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 106,
      "created_at": 1610258178
    },
    {
      "type": "buy_train",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 107,
      "created_at": 1610258181,
      "train": "2-9",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 108,
      "created_at": 1610258184
    },
    {
      "type": "lay_tile",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 109,
      "created_at": 1610258196,
      "hex": "O7",
      "tile": "202-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 110,
      "created_at": 1610258208
    },
    {
      "type": "buy_train",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 111,
      "created_at": 1610258221,
      "train": "3-0",
      "price": 225,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 112,
      "created_at": 1610258229
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 113,
      "created_at": 1610258234
    },
    {
      "type": "lay_tile",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 114,
      "created_at": 1610258244,
      "hex": "M9",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 115,
      "created_at": 1610258249
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 116,
      "created_at": 1610258255
    },
    {
      "type": "buy_train",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 117,
      "created_at": 1610258257,
      "train": "3-1",
      "price": 225,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 118,
      "created_at": 1610258260
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 119,
      "created_at": 1610258263
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 120,
      "created_at": 1610258276,
      "hex": "L10",
      "tile": "204-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 121,
      "created_at": 1610258294
    },
    {
      "type": "run_routes",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 122,
      "created_at": 1610258296,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "L10",
              "K11",
              "J12"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "J12",
            "L10",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 123,
      "created_at": 1610258301
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 124,
      "created_at": 1610258314
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 125,
      "created_at": 1610258316
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 126,
      "created_at": 1610258330,
      "hex": "J12",
      "tile": "622-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 127,
      "created_at": 1610258349
    },
    {
      "type": "run_routes",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 128,
      "created_at": 1610258361,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K13",
              "J12"
            ],
            [
              "L12",
              "K13"
            ]
          ],
          "hexes": [
            "J12",
            "K13",
            "L12"
          ],
          "revenue": 80,
          "revenue_str": "J12-K13-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 129,
      "created_at": 1610258366
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 130,
      "created_at": 1610258378
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 131,
      "created_at": 1610258380
    },
    {
      "type": "lay_tile",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 132,
      "created_at": 1610258389,
      "hex": "F16",
      "tile": "120-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 133,
      "created_at": 1610258395
    },
    {
      "type": "run_routes",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 134,
      "created_at": 1610258405,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "F16",
              "G15"
            ]
          ],
          "hexes": [
            "F16",
            "G15"
          ],
          "revenue": 80,
          "revenue_str": "F16-G15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 135,
      "created_at": 1610258409
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 136,
      "created_at": 1610258412
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 137,
      "created_at": 1610258414
    },
    {
      "type": "lay_tile",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 138,
      "created_at": 1610258428,
      "hex": "E15",
      "tile": "14-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 139,
      "created_at": 1610258433
    },
    {
      "type": "run_routes",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 140,
      "created_at": 1610258435,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "D16",
              "E15"
            ]
          ],
          "hexes": [
            "D16",
            "E15"
          ],
          "revenue": 60,
          "revenue_str": "D16-E15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 141,
      "created_at": 1610258440
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 142,
      "created_at": 1610258442
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 143,
      "created_at": 1610258443
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 144,
      "created_at": 1610258453
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 145,
      "created_at": 1610258455
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 146,
      "created_at": 1610258455
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 147,
      "created_at": 1610258455
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 148,
      "created_at": 1610258456
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 149,
      "created_at": 1610258456
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 150,
      "created_at": 1610258456
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 151,
      "created_at": 1610258457
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 152,
      "created_at": 1610258459
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 153,
      "created_at": 1610258459
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 154,
      "created_at": 1610258471,
      "hex": "M9",
      "tile": "15-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 155,
      "created_at": 1610258478
    },
    {
      "type": "run_routes",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 156,
      "created_at": 1610258484,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L10",
              "L12"
            ],
            [
              "J12",
              "K11",
              "L10"
            ]
          ],
          "hexes": [
            "L12",
            "L10",
            "J12"
          ],
          "revenue": 80,
          "revenue_str": "L12-L10-J12"
        },
        {
          "train": "2-1",
          "connections": [
            [
              "K13",
              "L12"
            ],
            [
              "J12",
              "K13"
            ]
          ],
          "hexes": [
            "L12",
            "K13",
            "J12"
          ],
          "revenue": 80,
          "revenue_str": "L12-K13-J12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 157,
      "created_at": 1610258489
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 158,
      "created_at": 1610258491
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 159,
      "created_at": 1610258505,
      "hex": "E17",
      "tile": "207-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 160,
      "created_at": 1610258513
    },
    {
      "type": "run_routes",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 161,
      "created_at": 1610258517,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E17",
              "F16"
            ]
          ],
          "hexes": [
            "E17",
            "F16"
          ],
          "revenue": 100,
          "revenue_str": "E17-F16"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E17",
              "F18"
            ]
          ],
          "hexes": [
            "E17",
            "F18"
          ],
          "revenue": 80,
          "revenue_str": "E17-F18"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 162,
      "created_at": 1610258521
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 163,
      "created_at": 1610258525
    },
    {
      "type": "lay_tile",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 164,
      "created_at": 1610258536,
      "hex": "G15",
      "tile": "15-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 165,
      "created_at": 1610258541
    },
    {
      "type": "run_routes",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 166,
      "created_at": 1610258546,
      "routes": [
        {
          "train": "2-8",
          "connections": [
            [
              "G15",
              "F16"
            ]
          ],
          "hexes": [
            "F16",
            "G15"
          ],
          "revenue": 90,
          "revenue_str": "F16-G15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 167,
      "created_at": 1610258549
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 168,
      "created_at": 1610258557
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 169,
      "created_at": 1610258562
    },
    {
      "type": "lay_tile",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 170,
      "created_at": 1610258590,
      "hex": "D16",
      "tile": "622-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 171,
      "created_at": 1610258596
    },
    {
      "type": "run_routes",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 172,
      "created_at": 1610258613,
      "routes": [
        {
          "train": "2-9",
          "connections": [
            [
              "E15",
              "F14",
              "F16"
            ]
          ],
          "hexes": [
            "F16",
            "E15"
          ],
          "revenue": 90,
          "revenue_str": "F16-E15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 173,
      "created_at": 1610258619
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 174,
      "created_at": 1610258622
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 175,
      "created_at": 1610258623
    },
    {
      "type": "lay_tile",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 176,
      "created_at": 1610258630,
      "hex": "N8",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 177,
      "created_at": 1610258642,
      "routes": [
        {
          "train": "3-0",
          "connections": [
            [
              "O7",
              "P8"
            ]
          ],
          "hexes": [
            "P8",
            "O7"
          ],
          "revenue": 60,
          "revenue_str": "P8-O7"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 178,
      "created_at": 1610258646
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 179,
      "created_at": 1610258652
    },
    {
      "type": "pass",
      "entity": "NO",
      "entity_type": "corporation",
      "id": 180,
      "created_at": 1610258665
    },
    {
      "type": "lay_tile",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 181,
      "created_at": 1610258713,
      "hex": "O7",
      "tile": "207-1",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 182,
      "created_at": 1610258738,
      "routes": [
        {
          "train": "3-1",
          "connections": [
            [
              "M9",
              "N8",
              "O7"
            ],
            [
              "L10",
              "M9"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "O7",
            "M9",
            "L10",
            "L12"
          ],
          "revenue": 110,
          "revenue_str": "O7-M9-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 183,
      "created_at": 1610258742
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 184,
      "created_at": 1610258746
    },
    {
      "type": "pass",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 185,
      "created_at": 1610258748
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 186,
      "created_at": 1610258762,
      "hex": "L12",
      "tile": "637-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 187,
      "created_at": 1610258777
    },
    {
      "type": "undo",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 188,
      "created_at": 1610258797
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 189,
      "created_at": 1610258803,
      "hex": "M11",
      "tile": "7-1",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 190,
      "created_at": 1610258808,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "L10",
              "K11",
              "J12"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "J12",
            "L10",
            "L12"
          ],
          "revenue": 90,
          "revenue_str": "J12-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 191,
      "created_at": 1610258812
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 192,
      "created_at": 1610258821
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 193,
      "created_at": 1610258822
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 194,
      "created_at": 1610258833,
      "hex": "K13",
      "tile": "88-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 195,
      "created_at": 1610258836,
      "hex": "M13",
      "tile": "3-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 196,
      "created_at": 1610258841,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K13",
              "J12"
            ],
            [
              "L12",
              "K13"
            ]
          ],
          "hexes": [
            "J12",
            "K13",
            "L12"
          ],
          "revenue": 90,
          "revenue_str": "J12-K13-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 197,
      "created_at": 1610258847
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 198,
      "created_at": 1610258851
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 199,
      "created_at": 1610258858
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 200,
      "created_at": 1610258868
    },
    {
      "type": "run_routes",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 201,
      "created_at": 1610258874,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "F16",
              "G15"
            ]
          ],
          "hexes": [
            "F16",
            "G15"
          ],
          "revenue": 90,
          "revenue_str": "F16-G15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 202,
      "created_at": 1610258877
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 203,
      "created_at": 1610258880
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 204,
      "created_at": 1610258884
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 205,
      "created_at": 1610258892
    },
    {
      "type": "run_routes",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 206,
      "created_at": 1610258901,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "D16",
              "E17"
            ]
          ],
          "hexes": [
            "E17",
            "D16"
          ],
          "revenue": 80,
          "revenue_str": "E17-D16"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 207,
      "created_at": 1610258904
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 208,
      "created_at": 1610258906
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 209,
      "created_at": 1610258908
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 210,
      "created_at": 1610258930,
      "corporation": "AE"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 211,
      "created_at": 1610259037,
      "corporation": "OP"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 212,
      "created_at": 1610259047,
      "corporation": "PM"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 213,
      "created_at": 1610259058,
      "corporation": "CV"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 214,
      "created_at": 1610259066,
      "corporation": "NO"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 215,
      "created_at": 1610259085,
      "corporation": "KP"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 216,
      "created_at": 1610259090,
      "corporation": "CA"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 217,
      "created_at": 1610259095,
      "corporation": "CS"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 218,
      "created_at": 1610259102,
      "corporation": "TN"
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 219,
      "created_at": 1610259108,
      "corporation": "CNR"
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 220,
      "created_at": 1610259131,
      "city": "207-0-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 221,
      "created_at": 1610259132,
      "city": "622-1-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 222,
      "created_at": 1610259133,
      "city": "14-0-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 223,
      "created_at": 1610259135,
      "city": "15-1-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 224,
      "created_at": 1610259138,
      "city": "207-1-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 225,
      "created_at": 1610259140,
      "city": "15-0-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 226,
      "created_at": 1610259142,
      "city": "637-0-0",
      "slot": 0
    },
    {
      "type": "remove_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 227,
      "created_at": 1610259179,
      "city": "622-0-0",
      "slot": 0
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 228,
      "created_at": 1610259188,
      "train": "2-0"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 229,
      "created_at": 1610259189,
      "train": "2-1"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 230,
      "created_at": 1610259190,
      "train": "2-8"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 231,
      "created_at": 1610259191,
      "train": "2-9"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 232,
      "created_at": 1610259192,
      "train": "2-2"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 233,
      "created_at": 1610259194,
      "train": "2-7"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 234,
      "created_at": 1610259194,
      "train": "2-5"
    },
    {
      "type": "discard_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 235,
      "created_at": 1610259196,
      "train": "2-3"
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 236,
      "created_at": 1610259513
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 237,
      "created_at": 1610259514
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 238,
      "created_at": 1610259515
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 239,
      "created_at": 1610259516
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 240,
      "created_at": 1610259517
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 241,
      "created_at": 1610259518
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 242,
      "created_at": 1610259519
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 243,
      "created_at": 1610259520
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 244,
      "created_at": 1610259521
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 245,
      "created_at": 1610259522
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 246,
      "created_at": 1610259523
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 247,
      "created_at": 1610259524
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 248,
      "created_at": 1610259525
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 249,
      "created_at": 1610259526
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 250,
      "created_at": 1610259526
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 251,
      "created_at": 1610259527
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 252,
      "created_at": 1610259528
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 253,
      "created_at": 1610259529
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 254,
      "created_at": 1610259530
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 255,
      "created_at": 1610259531
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 256,
      "created_at": 1610259531
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 257,
      "created_at": 1610259532
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 258,
      "created_at": 1610259533
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 259,
      "created_at": 1610259534
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 260,
      "created_at": 1610259535
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 261,
      "created_at": 1610259535
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 262,
      "created_at": 1610259536
    },
    {
      "type": "undo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 263,
      "created_at": 1610259537
    },
    {
      "type": "undo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 264,
      "created_at": 1610259538
    },
    {
      "type": "undo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 265,
      "created_at": 1610259538
    },
    {
      "type": "undo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 266,
      "created_at": 1610259539
    },
    {
      "type": "undo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 267,
      "created_at": 1610259540
    },
    {
      "type": "undo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 268,
      "created_at": 1610259541
    },
    {
      "type": "undo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 269,
      "created_at": 1610259541
    },
    {
      "type": "undo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 270,
      "created_at": 1610259542
    },
    {
      "type": "redo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 271,
      "created_at": 1610259546
    },
    {
      "type": "redo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 272,
      "created_at": 1610259548
    },
    {
      "type": "redo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 273,
      "created_at": 1610259557
    },
    {
      "type": "redo",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 274,
      "created_at": 1610259563
    },
    {
      "type": "redo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 275,
      "created_at": 1610259567
    },
    {
      "type": "redo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 276,
      "created_at": 1610259569
    },
    {
      "type": "redo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 277,
      "created_at": 1610259571
    },
    {
      "type": "redo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 278,
      "created_at": 1610259574
    },
    {
      "type": "redo",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 279,
      "created_at": 1610259577
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 280,
      "created_at": 1610259605,
      "corporation": "AE"
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 281,
      "created_at": 1610259619
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 282,
      "created_at": 1610259646,
      "corporation": "AE"
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 283,
      "created_at": 1610259661
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 284,
      "created_at": 1610259680,
      "corporation": "AE"
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 285,
      "created_at": 1610259707
    },
    {
      "type": "merge",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 286,
      "created_at": 1610259735,
      "corporation": "AE"
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 287,
      "created_at": 1610259752
    }
  ],
  "id": "hs_vmteailk_1610257387",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    },
    {
      "name": "Player 4"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "4",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-09",
  "loaded": true,
  "result": {},
  "turn": 2,
  "round": "Merger Round",
  "acting": [
    "Player 1"
  ],
  "updated_at": 1610259753
}

### PR DESCRIPTION
**Pull request by jenf**
Merging when the player has one corp does not allow selection of other players corps (fixes #3184)
Stray log line after initial stock round (fixes #3110)

### CODE REVIEW

File: lib/engine/step/g_1867/single_item_auction.rb [hunk 1]
```diff
@@ -75,9 +75,9 @@ def min_increment
 
         def setup
           setup_auction
-          @companies = @game.companies.reject { |c| c.id == '3' }.sort_by(&:value)
+          @companies = @game.companies.reject { |c| c.id == '3' || c.owner&.player? }.sort_by(&:value)
 
-          auction_entity_log(@companies.first)
+          auction_entity_log(@companies.first) if @companies.any?
```
Comment (tobymao) [inline lib/engine/step/g_1867/single_item_auction.rb:80]: unless companies.empty

**Review by tobymao — APPROVED** [review]
