### PR TITLE
Fix ZigZig end movement for 60 and 62

### LINKED ISSUE #8979: Game is Locked 1860 https://18xx.games/game/111768?action=626
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #8979 

> Please minimize the amount of changes to shared `lib/engine` code, if possible

Have to touch stock_market and stock_movement

> If you are implementing a new game, please break up the changes into multiple PRs for ease of review.

### Before clicking "Create"

- [*] Branch is derived from the latest `master`
- [*] Add the `pins` label if this change will break existing games
- [*] Code passes linter with `docker compose exec rack rubocop -a`
- [*] Tests pass cleanly with `docker compose exec rack rake`

### Implementation Notes

* **Explanation of Change**

1860 and 1862 have different rules than 18CZ and EUS when reaching either end of the "ZigZag" row.

* **Screenshots**

* **Any Assumptions / Hacks**

### CODE REVIEW

File: lib/engine/stock_market.rb [hunk 1]
```diff
@@ -5,12 +5,13 @@
...
   class StockMarket
-    attr_reader :market, :par_prices, :has_close_cell, :zigzag
+    attr_reader :market, :par_prices, :has_close_cell, :zigzag, :ledge_movement
 
-    def initialize(market, unlimited_types, multiple_buy_types: [], zigzag: nil)
+    def initialize(market, unlimited_types, multiple_buy_types: [], zigzag: nil, ledge_movement: nil)
       @par_prices = []
       @has_close_cell = false
       @zigzag = zigzag
+      @ledge_movement = ledge_movement
```
Comment (crericha) [inline lib/engine/stock_market.rb:14]: We don't need to store ledge_movement or zigzag, for that matter. They are only used to create the stock_movement class during the constructor.

**Review by crericha — APPROVED** [review]

File: lib/engine/stock_market.rb (hunk 1 above)
Comment (crericha) [reply lib/engine/stock_market.rb:14]: Let me know if you want to make this change or leave as is.

Comment (roseundy) [reply lib/engine/stock_market.rb:14]: I'll change it

Comment (roseundy) [reply lib/engine/stock_market.rb:14]: Turns out the zigzag attribute is still needed. Both game/base and the stock market UI need it.

**Comment by crericha** [comment]
Merging so I can rebase with this
