### PR TITLE
The player associated with an action must be the one to make it

### LINKED ISSUE #1558: [1889] port tile illegal placement
**Please provide**
* Multiplayer? Yes
https://www.18xx.games/game/7696?action=91

**Describe the bug**
TR (owner KrzysP) was able to place port tile in G10 while Mitsubishi Ferry was hold by another player (Sir_Yaro).

### LINKED ISSUE #1725: 1889: Cannot use Mitsubishi Ferry ability if not president of any corporation
Example game: https://18xx.games/game/10498/action=57

A player owning Mitsubishi Ferry, and not being president of any corporation cannot ever lay the tile.
During SR the ability does not appear for the player owning the Ferry private.
During OR the ability is possible to display by clicking the other button, but the player cannot use the ability as the player is never the current acting player. 
It is possible, by using Master mode, to lay the tile during the OR when another player is acting, and it will show up as if the owning player had acted, but without Master mode it cannot be done.

The rules have this wording:
"Player owner may place the port tile on a coastal town without a tile on it already, outside of the operating rounds of company controlled by another player.  The player need not control a company or have connectivity to the places tile from one of their companies.  This does not close the company."

As there are no step in between ORs in 18xx.games this is not trivial.

Adding such a step is possible but it would break all existing games AND slow down future games a bit.

Making it possible to use the ability "out of turn" might be a smaller effect and should not break any game.

This is related to #1558 although that is a report on another issue.

### PR DESCRIPTION
**Pull request by michaeljb**
* if a player onws a private company with an ability that may be used out of
  turn, prevent the current player from using the ability (e.g., Mitsubishi
  Ferry and Dougo Railway in 1889)
* Master Mode can still override this

Doesn't add a new step for Mitsubishi Ferry, but does let another player activate the ability at the start of a corporation's OR turn, without that player using master mode.

[Fixes #1558] [Fixes #1725]

### CODE REVIEW

File: assets/app/view/game/actionable.rb [hunk 1]
```diff
@@ -44,6 +44,11 @@ def check_consent(player, click)
         store(:confirm_opts, opts, skip: false)
       end
 
+      def valid_actor?(action)
+        @valid_actors = @game.valid_actors(action)
+        @valid_actors.map(&:id).include?(@user['id'])
```
Comment (tobymao) [inline assets/app/view/game/actionable.rb:49]: @valid_actions.any? { |actor| actor.id == @user['id'] }

one pass

**Review by tobymao — APPROVED** [review]
