### PR TITLE
(fixes #1450) Fixes the issue where the price on the cards would not go down if there was an discount. 

### LINKED ISSUE #1450: Indicate company discount on card
In 1882, when everyone passes the price of the cheapest company decreases by 5. This is indicated in the log but the card for the company still shows just the full value. It would be nice if, when a company was available for a discount, the true selling price were indicated on the card.

Presumably this also shows up in 1846 (when people pass on the very last company in the draft) and in 1830-ish games where no one buys a private at all (although that very rarely happens).

### PR DESCRIPTION
**Pull request by captianobi**
(fixes #1450) The issue has been fixed. A new price: value has been added to show the current price of the company. I would like to request assistance for fixing the issue for 1846 as the discount includes the debt of companies like the big four.
image

### CODE REVIEW

File: assets/app/view/game/company.rb [hunk 1]
```diff
@@ -109,6 +113,14 @@ def render
             children << render_bidders
           end
 
+          if @company.discount != 0
+            children << h(
+            :div,
+            { style: current_value_style },
```
Comment (tobymao) [inline assets/app/view/game/company.rb:119]: move line 75 inline here

**Comment by captianobi** [comment]
I would like to request help with 1846 and it's debt, I'd recommend creating a new value for the display such as realDiscount and then using that to actually show the discount instead of using just @company.discount

File: assets/app/view/game/company.rb [hunk 2]
```diff
@@ -109,6 +113,14 @@ def render
             children << render_bidders
           end
 
+          if @company.discount != 0
```
Comment (tobymao) [inline assets/app/view/game/company.rb:116]: if company.discount.positive? or unless company.discount.zero?

Comment (captianobi) [reply assets/app/view/game/company.rb:116]: Unless company.discount.zero. making it positive won't help fix the 1846 issue.

Comment (dfannius) [reply assets/app/view/game/company.rb:116]: The 1846 minors can be discounted too. I'm not sure how it's implemented on this site and it may not even be correct if the implementation overloads discount and debt, since I believe the discount is supposed to apply to the buying price rather than the debt.

Comment (dfannius) [reply assets/app/view/game/company.rb:116]: (Confirmed: https://boardgamegeek.com/thread/1880571/article/27393557#27393557)

**Comment by captianobi** [comment]
So the issue with the 1846 minors is that the discount starts at -60 to implement the 60$ debt that the purchaser of the companies has to pay. So off the bat the code will display price: 100. As the value is 40 plus the 60$ debt.

**Review by tobymao — APPROVED** [review]
