### PR TITLE
validate username & email

### LINKED ISSUE #2357: Better error message on duplicate username
If I try to change my username to one that exists, I get the error "PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "users_lower(name)_index" DETAIL: Key (lower(name))=(...) already exists."

### PR DESCRIPTION
**Pull request by yzemaze**
fixes #2357

image
image

### CODE REVIEW

File: models/user.rb [hunk 1]
```diff
@@ -68,4 +63,11 @@ def to_h(for_user: false)
   def inspect
     "#{self.class.name} - id: #{id} name: #{name}"
   end
+
+  def validate
+    super
+    validates_unique(:name, :email, { message: 'is already registered' })
+    validates_format /^[^\s]+$/, :name, message: 'may not be empty'
+    validates_format /^[^@\s]+@[^@\s]+\.[^@\s]+$/, :email
```
Comment (benjaminxscott) [inline models/user.rb:71]: You may be able to use this, which is apparently a standard import

URI::MailTo::EMAIL_REGEXP

(since hand-rolled email regexes are tricky)

Comment (yzemaze) [reply models/user.rb:71]: I remember talking with Toby about the regex last year. tl;dr the simple one was good enough. But this one didn’t cross my path. Thanks.

**Review by tobymao — APPROVED** [review]

File: models/user.rb (hunk 1 above)
Comment (tobymao) [reply models/user.rb:71]: up to you, don't care
