### PR TITLE
[1822] Wierd Dividend Choice

### LINKED ISSUE #5029: 1822 game has uncaught exception in console
I'm not sure what exactly caused this but this game no longer loads after an action was taken and there is an exception in the browser console

https://18xx.games/game/37076

### PR DESCRIPTION
**Pull request by magnusfalt**
- Added an extra check when choosing dividend.

fixes #5029

This shouldnt break any games.

### CODE REVIEW

File: lib/engine/game/g_1822/step/dividend.rb [hunk 1]
```diff
@@ -114,6 +114,9 @@ def process_choose(action)
                 'withhold'
               when 'half'
                 'half pay'
+              else
+                @extra_train_choice = 'payout'
```
Comment (jenf) [inline lib/engine/game/g_1822/step/dividend.rb:118]: This should raise instead (and the broken game undone to the right point)

**Comment by magnusfalt** [comment]
Its the last action 593 that needs to be undone.

**Review by jenf — APPROVED** [review]
