### PR TITLE
18MEX: Fix sort bug for NdM shares in market pool (fixes #2467)

### LINKED ISSUE #2467: [18Mex] Selling 5% breaks NdM
Game link: https://18xx.games/game/17180?action=380

When I sold a 5% share of NdM, the game's display stuttered and smeared, and an error message was displayed, and I had to refresh. The share was successfully sold. After that point, the NdM could not be selected to buy or sell shares. We'd click on the company charter, and nothing would happen.

This is the traceback when I sold the share:
```
cash: undefined method `cash' for #<Engine::G18Mex::SharePool:0x5125e>
main.js:9     at a.$method_missing (https://18xx.games/assets/main.js:2:20031)
main.js:9     at a.n (https://18xx.games/assets/main.js:1:11652)
main.js:9     at a.$spend (https://18xx.games/assets/main.js:69:25237)
main.js:9     at a.$transfer_shares (https://18xx.games/assets/main.js:104:2991)
main.js:9     at a.$sell_shares (https://18xx.games/assets/main.js:104:1629)
main.js:9     at a.$sell_shares_and_change_price (https://18xx.games/assets/main.js:113:23613)
main.js:9     at a.$sell_shares (https://18xx.games/assets/main.js:82:1317)
main.js:9     at a.$process_sell_shares (https://18xx.games/assets/main.js:81:30220)
main.js:9     at a.$__send__ (https://18xx.games/assets/main.js:2:14965)
```

This is the message when we tried to later buy/sell shares:
```
main.js:2 Uncaught 
{name: "ArgumentError", message: "comparison of <Share: NdM 5%> with <Share: NdM 10%> failed", stack: "ArgumentError: comparison of <Share: NdM 5%> with …t e (https://18xx.games/assets/main.js:126:11911)"}
```

### PR DESCRIPTION
**Pull request by perwestling**

### CODE REVIEW

File: assets/app/view/game/buy_sell_shares.rb [hunk 1]
```diff
@@ -20,7 +20,7 @@ def render
           .map(&:first).sort.reverse
 
         @pool_shares = @game.share_pool.shares_by_corporation[@corporation].group_by(&:percent).values
-          .map(&:first).sort.reverse
+          .map(&:first).sort_by(&:percent).reverse
```
Comment (tobymao) [inline assets/app/view/game/buy_sell_shares.rb:23]: do you need to change the other shares to on line 20?

Comment (perwestling) [reply assets/app/view/game/buy_sell_shares.rb:23]: Probably not needed, but I have now followed your suggestion to make it consistent.
