### PR TITLE
[1848] fix EMR text

### LINKED ISSUE #8263: 1848 incorrect EMR message
The EMR message should not even mention how much cash the president has, nor should it say how much cash the president needs to contribute.

https://18xx.games/game/93503?action=512

Screen Shot 2022-08-31 at 18 37 05

### PR DESCRIPTION
**Pull request by bentziaxl**
fixes #8263

### CODE REVIEW

File: assets/app/view/game/buy_trains.rb [hunk 1]
```diff
@@ -281,6 +281,8 @@ def render
           children.concat(render_president_contributions)
         end
 
+        children << h(:div, @step.ebuy_custom_message(@corporation)) if @step.respond_to?(:ebuy_custom_message)
```
Comment (crericha) [inline assets/app/view/game/buy_trains.rb:284]: I'm not a fan of half solutions. If we need to move ebuy text into steps (which I do think is a good idea), let's move the default text into the train module and call it ebuy_message.

**Review by crericha — APPROVED** [review]

**Comment by tobymao** [comment]
this change has been reverted because it was untested and broke the ui
