### PR TITLE
18SJ: Fix bug after corporations made IPO (fixes #8128)

### LINKED ISSUE #8128: [18SJ] Unable to purchase IPO shares from corporations (when it is full cap).
**What's your Game ID?**
https://18xx.games/game/91159

**How to Reproduce the Bug?**
- After reaching Full Cap, clicking on any corporations (ÖSJ or BJ in affected game) during SR will not reveal the "buy" button to buy IPO shares.
- In a clone of the game to hotseat, market shares were possible to purchase. Have not investigated treasury shares.
- Seemed to happen sometime after 18:28Z yesterday (29th. July) when my auto managed to purchase a IPO share.

**Which Browser / Platform?**
- Browser Version
  - On Android and Chrome, 103.0.5060.129
  - On PC and Firefox, version 103.0

### PR DESCRIPTION
**Pull request by perwestling**
This fixes a bug that occur late in the game. If any games is broken by this fix this is probably bad as the game cannot be completed OR my fix is not correct. So if this do break any games I think I need to get this back for a revisit.

(The issue is that no shares can be bought from IPO, and occurs when game enters brown phase - and some corporations are changes from Incremental to Full cap. So it should have no effect on games that have not reached that phase.)

### CODE REVIEW

**Comment by perwestling** [comment]
Does seem to still be a problem so I need to revisit this PR.

**Comment by perwestling** [comment]
There was a need to override another IPO related method. Have tested manually on the two reported games and a fresh hotseat, and now all buy of shares from IPO/Treasury/Market seems to work.

File: lib/engine/game/g_18_sj/step/buy_sell_par_shares.rb [hunk 1]
```diff
@@ -10,6 +10,22 @@ class BuySellParShares < Engine::Step::BuySellParShares
...
             super && (@game.oscarian_era || bundle.corporation.floated?)
           end
+
+          def can_ipo_any?(entity)
+            !bought? && @game.corporations.any? do |c|
+              @game.can_par?(c, entity) && can_buy?(entity, c.ipo_shares.first&.to_bundle)
+            end
+          end
+
+          # FIXME: copied from 21moon which has "FIXME: move to common location"
```
Comment (tobymao) [inline lib/engine/game/g_18_sj/step/buy_sell_par_shares.rb:20]: can you fix it?

Comment (perwestling) [reply lib/engine/game/g_18_sj/step/buy_sell_par_shares.rb:20]: I am asking Roseundy about that comment. It might be that 21moon has duplicate methods (in buy_sell_par_shares.rb and corporation_buy_sell_shares.rb) so that the comment is for 21moon, or it might be something to be shared more widely.

Comment (perwestling) [reply lib/engine/game/g_18_sj/step/buy_sell_par_shares.rb]: @tobymao I asked Steven; the FIXME was 21moon specific. Do not see any special need to make a more generalized solution at this time.

**Review by tobymao — APPROVED** [review]
