### PR TITLE
18SJ: Fix side effects for E trains

### LINKED ISSUE #6676: [18SJ] Non E trains allowed to go through SJ token.
https://18xx.games/game/65110?action=656

My Corp has an E train and a 6 train. However if you look at the route, the 6 train is able to go through an SJ token while I believe that only the E train should be able to do it.

### PR DESCRIPTION
**Pull request by perwestling**
Contains two fixes:
- Making SJ tokens passable is now done after the token step
  so that current entity cannot affect track or token through
  a blocked city, even if SJ token is there.
- If current entity makes a non-E route it cannot pass through
  a blocked city, even if SJ token is there.

Fixes #6676

### CODE REVIEW

File: lib/engine/game/g_18_sj/game.rb [hunk 1]
```diff
@@ -1595,6 +1596,21 @@ def player_count
           # to handle setup of cash and cert limit so that it includes the bot.
           two_player_variant ? 3 : @players.size
         end
+
+        def ensure_route_does_not_passthrough_blocked_city(route, stops)
+          return if stops.size < 3 || !owns_electric_train?(route.train.owner) || route.train.name == 'E'
+
+          # Check if a stop (excluding start and stop) does not allow pass-through
+          # due to temporary passable SJ token
+          passthrough = stops.dup
```
Comment (tobymao) [inline lib/engine/game/g_18_sj/game.rb:1605]: stops[1…-1]

Comment (perwestling) [reply lib/engine/game/g_18_sj/game.rb]: Ah....
Fixed with new commit.
