### PR TITLE
Rolling Stock: fix Foreign income; fix liquidity

### LINKED ISSUE #7935: [RSS] Use total cash that could be raised in investment phase for liquidity
It'd be more helpful to know the total amount of money a player can raise in the investment phase (given the current game state) than what is currently shown as liquidity, which I believe currently shows amount of cash when not in the investment phase and cash + one share sold when in the investment phase.

### LINKED ISSUE #8057: [Rolling Stock] Foreign investor doesn't get all its income.
**What's your Game ID?**

https://18xx.games/game/85009?action=243

**How to Reproduce the Bug?**

Foreign investor gets only $5 here but should get $10 ($5 base income + $5 for SBB).

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #7935
Fixes #8057 

This will likely require pinning failing games.

### CODE REVIEW

File: lib/engine/game/g_rolling_stock/game.rb [hunk 1]
```diff
@@ -1043,6 +1043,26 @@ def movement_chart(corporation)
           chart << ['', ''] while chart.size < 5
           chart
         end
+
+        def liquidity(player, emergency: false)
+          total = player.cash
+          return(total) unless @round&.stock?
```
Comment (crericha) [inline lib/engine/game/g_rolling_stock/game.rb:1049]: What's your thoughts on always returning the stock round liquidity? I find it helpful to know when determining dividends and what to start a company at.

Comment (roseundy) [reply lib/engine/game/g_rolling_stock/game.rb:1049]: Yeah, probably makes sense.
