### PR TITLE
[1822] Lur

### LINKED ISSUE #4522: [1822] Move Card Private is Broken or Needs a UX Overhaul
https://18xx.games/game/32904?action=1176

The NER owns the "Move Card" private, but we were unable to make it work. Numerous players tried in game, and in cloned hotseat games, and we were unable to figure out when/where to click to move a card.  

Either it's broken or it needs to be easier to use.

### PR DESCRIPTION
**Pull request by magnusfalt**
- Made the LUR ability shows itself during the track lay and token step as well.

fixes #4522

This change does not affect any of the currect games.

### CODE REVIEW

File: lib/engine/game/g_1822/game.rb [hunk 1]
```diff
@@ -3451,7 +3451,7 @@ def company_choices_lcdr(company, time)
         end
 
         def company_choices_lur(company, time)
-          return {} if time != :issue || !company.owner&.corporation?
+          return {} if !(time == :token || time == :track || time == :issue) || !company.owner&.corporation?
```
Comment (jenf) [inline lib/engine/game/g_1822/game.rb:3454]: would probably split the two sides of the or into two to make it clearer
return {} unless company.owner&.corporation?

Comment (magnusfalt) [reply lib/engine/game/g_1822/game.rb]: Sure it makes sense :)
