### PR TITLE
More pointy rendering fixes - Labels and Locations. 18MEX MC upgrade …

### LINKED ISSUE #1618: 1836jr - Positioning of revenue value on brown NY tile blocks view of track
1836jr - Positioning of revenue value on brown NY tile blocks view of track. 

If the value was moved one hex point clockwise, it would block no track.

Amsterdam location label also blocks north most track exit. I have no idea for a solution there.

Affects any version of the game.

1836jr NYC

### PR DESCRIPTION
**Pull request by roseundy**
…rendering fixes.

Fixes #1618 

Old 1836Jr30 Amsterdam:
Amsterdam_before

New:
Amsterdam_new

New Mexico City upgrade tiles:
MexicoCityTilesNew

### CODE REVIEW

File: assets/app/view/game/part/location_name.rb [hunk 1]
```diff
@@ -11,6 +11,10 @@ class LocationName < Base
         BACKGROUND_COLOR = '#FFFFFF'
         BACKGROUND_OPACITY = '0.5'
 
+        def edge_at_bottom?(edge = nil)
+          edge&.zero? || edge == 5 || edge == 5.5
```
Comment (tobymao) [inline assets/app/view/game/part/location_name.rb:15]: how about edge.to_i == 5

File: assets/app/view/game/part/location_name.rb [hunk 2]
```diff
@@ -42,7 +46,29 @@ def preferred_render_locations
...
+            # flat map: if two cities, and they are on edges 0 and 3, pick the center.
+            if layout == :flat && @tile.cities.size == 2 &&
+                ([0, 3] - @tile.city_towns.map { |c| @tile.preferred_city_town_edges[c] }).empty?
+              return [center]
+            end
+
+            # pointy map: if two cities or towns, and neither of them are on edges 1 or 4 or in the center,
+            # pick the center.
+            if layout == :pointy && @tile.city_towns.size == 2 &&
+                ([1, 4] - @tile.city_towns.map { |ct| @tile.preferred_city_town_edges[ct] }).size == 2 &&
```
Comment (tobymao) [inline assets/app/view/game/part/location_name.rb:58]: should we store @tile.city-towns.map above since you call it here and on line 51

File: assets/app/view/game/part/location_name.rb [hunk 3]
```diff
@@ -11,6 +11,10 @@ class LocationName < Base
         BACKGROUND_COLOR = '#FFFFFF'
         BACKGROUND_OPACITY = '0.5'
 
+        def edge_at_bottom?(edge = nil)
```
Comment (tobymao) [inline assets/app/view/game/part/location_name.rb:14]: why is edge default nil? i don't see you calling it without args

in one case would it be nil? for the safety check on line 15?

File: assets/app/view/game/part/location_name.rb (hunk 1 above)
Comment (roseundy) [reply assets/app/view/game/part/location_name.rb:15]: OK

File: assets/app/view/game/part/location_name.rb (hunk 2 above)
Comment (roseundy) [reply assets/app/view/game/part/location_name.rb:58]: OK

File: assets/app/view/game/part/location_name.rb (hunk 3 above)
Comment (roseundy) [reply assets/app/view/game/part/location_name.rb:14]: Just being paranoid. I'll delete.
