### PR TITLE
[18mag] fix +1 train supporter

### LINKED ISSUE #9045: 18Mag +1 engineer not working
https://18xx.games/game/116943
 
 doesn’t count the town when you use the power, does with autoroute but then there’s a “nil can’t be an integer” error?

### PR DESCRIPTION
**Pull request by bentziaxl**
fixes #9045

one of the supporters converts a train into +1, for example 2+1.
this can combine with the major ability that converts into plus train. (gc major)

Need special logic to handle
2+1 (supporter only)
2+2 (plus train conversion only)
2+3 (supporter and plus train)

added
1- train conversion and train distance use a city_distance_value  in case it's a gc train
2- compute stops needs to use the updated distance, previously used distance without GC. instead of copying the entire content of compute stops i pass a dummy duplicate train with the correct distance (open to other suggestions such as adding a param or copying the entire method)
3- modified route_distance to also work if just supporter is used without gc

### CODE REVIEW

File: lib/engine/game/g_18_mag/game.rb [hunk 1]
```diff
@@ -419,12 +419,16 @@ def must_buy_train?(_entity)
...
+          full_cost = train.price if train.owner == @depot
           if price != :free && train.owner == @depot
             if multiplayer?
               corp = %w[2 4].include?(train.name) ? @ldsteg : @mavag
-              operator.spend(cost / 2, @bank)
-              operator.spend(cost / 2, corp)
-              @log << "#{corp.name} earns #{format_currency(cost / 2)}"
+              bank_cost = full_cost ? (full_cost / 2) - (full_cost - cost) : cost / 2
+              corp_cost = full_cost ? full_cost / 2 : cost / 2
+              puts("here, #{bank_cost} #{full_cost} #{bank_cost + full_cost}")
```
Comment (bentziaxl) [inline lib/engine/game/g_18_mag/game.rb:428]: code could be cleaner. 
When using the kalman kando supporter, there's a train discount. However the corp still gets the half of the full cost of the train. This code handles that case

File: lib/engine/game/g_18_mag/game.rb [hunk 2]
```diff
@@ -616,31 +620,47 @@ def check_distance(route, visits)
...
+        def compute_stops(route, train = nil)
+          train ||= route.train
+          distance = if gc_train?(route) && !other_gc_train?(route)
+                       gc_train_distance(route.train.distance)
+                     else
+                       route.train.distance
+                     end
+          train_dup = train.dup
+          train_dup.distance = distance
+
```
Comment (bentziaxl) [inline lib/engine/game/g_18_mag/game.rb:632]: When the train has been converted to +1 using the supporter, stops breaks when also adding gc (for example 2+1 turns into 2+3), the base compute_stops only returns two cities/offboards and 1 town. 
Duplicating the train and setting the correct distance fixes the issue.

Would a better alternative be to modify compute_stops to take distance=nil and pass the correct distance?
maybe copy the entire base method here and modify accordingly?

**Comment by michaeljb** [comment]
At least these games will need pins: `[116455, 116943, 117151, 117170, 117186, 117303]`

**Comment by bentziaxl** [comment]
hmm, looking why those will need to be pinned

**Comment by michaeljb** [comment]
huh, very strange, the validate script finds a `nil can't be coerced into Integer` error for each of those games. I just ran it again and go the same result, but then tried opening each one in the browser and they all load just fine there 🤔

**Comment by michaeljb** [comment]
Just did a bit more testing, with this PR's branch checked out the games I listed do appear to load fine in the browser but then the server rejects any further moves so I think the validate script is reporting things correctly, but it is weird that they don't render as broken in the browser.

The stack trace shows the `nil can't be coerced into Integer` exception coming from `compute_stops`.

**Comment by michaeljb** [comment]
I don't know 18Mag and I can't really tell if it's expected that these changes would break any games, maybe @roseundy can take a look?

File: lib/engine/game/g_18_mag/game.rb [hunk 3]
```diff
@@ -616,31 +619,47 @@ def check_distance(route, visits)
...
+              nodes: %w[town],
+              pay: town_distance_value,
+              visit: town_distance_value,
+            },
+            {
+              nodes: %w[city offboard town],
+              pay: city_distance_value,
+              visit: city_distance_value,
+            },
+
```
Comment (roseundy) [inline lib/engine/game/g_18_mag/game.rb:656]: Does changing the order between town and city,offboard,town matter?

Comment (bentziaxl) [reply lib/engine/game/g_18_mag/game.rb:656]: so as far as i know the rules of 18mag allow for a 2+2 train (after upgrade from the major) to run 1 city and 3 towns.
If that's the case than the correct order should be town then city/town/offboard.

File: lib/engine/game/g_18_mag/game.rb [hunk 4]
```diff
@@ -419,12 +419,15 @@ def must_buy_train?(_entity)
...
           @train_bought = true if train.owner == @depot # No idea if this is what Lonny wants
           cost = price || train.price
+          full_cost = train.price if train.owner == @depot
           if price != :free && train.owner == @depot
             if multiplayer?
               corp = %w[2 4].include?(train.name) ? @ldsteg : @mavag
-              operator.spend(cost / 2, @bank)
-              operator.spend(cost / 2, corp)
-              @log << "#{corp.name} earns #{format_currency(cost / 2)}"
+              bank_cost = full_cost ? (full_cost / 2) - (full_cost - cost) : cost / 2
```
Comment (michaeljb) [inline lib/engine/game/g_18_mag/game.rb:426]: I find it hard to read that formula, how about this?

```suggestion
              bank_cost = full_cost ? cost - (full_cost / 2)  : cost / 2
```

File: lib/engine/game/g_18_mag/game.rb [hunk 5]
```diff
@@ -616,31 +619,47 @@ def check_distance(route, visits)
...
+          distance = if gc_train?(route) && !other_gc_train?(route)
+                       gc_train_distance(route.train.distance)
+                     else
+                       route.train.distance
+                     end
+          train_dup = train.dup
+          train_dup.distance = distance
+
+          super(route, train_dup)
+        end
```
Comment (michaeljb) [inline lib/engine/game/g_18_mag/game.rb:633]:
```suggestion
        def compute_stops(route, train = nil)
          return super if !gc_train?(route) || other_gc_train?(route)
          
          train ||= route.train
          gc_train = train.dup
          gc_train.distance = gc_train_distance(train.distance)

          super(route, gc_train)
        end
```

File: lib/engine/game/g_18_mag/game.rb [hunk 6]
```diff
@@ -616,31 +619,47 @@ def check_distance(route, visits)
...
-              },
+            {
+              nodes: %w[town],
+              pay: town_distance_value,
+              visit: town_distance_value,
+            },
+            {
+              nodes: %w[city offboard town],
+              pay: city_distance_value,
+              visit: city_distance_value,
```
Comment (michaeljb) [inline lib/engine/game/g_18_mag/game.rb:654]: I found the source of the validation errors, the classic server/client string/symbol issue. The base method expects the keys in these `distance` hashes to be strings: https://github.com/tobymao/18xx/blob/6310b539085311620e4382d7ec38958def286e7e/lib/engine/game/base.rb#L1373

In the compiled JS (client side / hotseat mode), symbols and strings are equivalent, but in the server side Ruby (and in `validate.rb`) they are not, so you need to use strings instead of symbols:

```suggestion
              'nodes' => %w[town],
              'pay' => town_distance_value,
              'visit' => town_distance_value,
            },
            {
              'nodes' => %w[city offboard town],
              'pay' => city_distance_value,
              'visit' => city_distance_value,
```

File: lib/engine/game/g_18_mag/game.rb (hunk 2 above)
Comment (michaeljb) [reply lib/engine/game/g_18_mag/game.rb:631]: No need to do that, but I think this method can be cleaned up while keeping the same logic--I'll post my suggested code.

**Review by michaeljb — CHANGES_REQUESTED** [review]

**Review by michaeljb — APPROVED** [review]
