### PR TITLE
1873: prohibit all illegal compulsory train buys

### LINKED ISSUE #4997: [Harzbahn 1873] NWE must not buy 1T as its compulsory train
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/35738

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

https://18xx.games/game/35738?action=469

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In the above action the NWE bought a 1T train from the HBE.
- This should not have been allowed since at this step the NWE was obliged to buy, as its first train purchase, a train that qualifies as its compulsory train, and the 1T doesn't (see the respective "Special feature" in Rule 4.4.7).
- All the remainder of the insolvency and recapitalization procedures are correct.

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #4997

### CODE REVIEW

**Comment by roseundy** [comment]
There is a slight chance this will require pins for some games.

File: lib/engine/game/g_1873/step/buy_train.rb [hunk 1]
```diff
@@ -127,6 +133,13 @@ def illegal_depot_buy?(train, entity)
           end
 
           def illegal_other_buy?(train, entity)
+            if @game.concession_pending?(entity) &&
```
Comment (jenf) [inline lib/engine/game/g_1873/step/buy_train.rb:136]: can we de-duplicate this code?

Comment (roseundy) [reply lib/engine/game/g_1873/step/buy_train.rb]: Good point. Yes.
