### PR TITLE
1817 Fixes

### LINKED ISSUE #2391: 1817: Corporations that can acquire shows up on Take Loans step
Will add link when my game hits it

### LINKED ISSUE #2392: 1817: can sell corporation in acquisition in cash crisis
Will add a link when i hit it in real game.

### LINKED ISSUE #2395: 1817 twenty 2 trains isn't enough
The physical game comes with twenty 2 trains and instructions to "use a substitute if you run out." This of course doesn't work on 18xx.games. Here's a player report (copied from Slack):

_In the player counts where 12 companies often start 20 2Ts is causing non 2Ts to export and 2+ trains to be offered for sale in OR1.1_

### LINKED ISSUE #2398: [1817] Players not given the chance to sell shares after merger
https://18xx.games/game/16672?action=903

SR merged with R, but the game just seems to have skipped the post conversion buy/sell phase altogether

### PR DESCRIPTION
**Pull request by jenf**
Allow sell of shares after merger if players cannot buy (fixes #2398)
Up train limits of 2 and 8 trains (fixes #2395)
Disable selling of corps in acquisition/liquidation in cash crisis (fixes #2392)
Don't show potential acquiring corps in take loans step (fixes #2391)

Needs a migration for #2398, and pinning one game cheating for #2392.

### CODE REVIEW

File: migrate_game.rb [hunk 1]
```diff
@@ -192,7 +197,7 @@ def attempt_repair(actions)
       begin
         game.process_action(action)
       rescue Exception => e
-        puts e.backtrace
+        #puts e.backtrace
```
Comment (tobymao) [inline migrate_game.rb:200]: uncomment

**Comment by tobymao** [comment]
fell free to merge and pin
