### PR TITLE
18CZ Fixed more bugs

### LINKED ISSUE #3994: [18CZ] Buying a corporation with token in same hex blocks game
https://gist.github.com/Zwergenpunk/d9fce0f6fee969cca1f8d2a84ebea26e

The step to remove the tokens is activated but the token in Praha is already removed.

Maybe regression bug? I think it worked 2 days ago

### LINKED ISSUE #4004: [18CZ] Company unable to cross-buy train
https://18xx.games/game/28590?action=259

The EKJ has no train and wants to cross-buy the 4T out of the BN, but for some reason this is not allowed.

### PR DESCRIPTION
**Pull request by Zwergenpunk**
closes #4004
closes #3994

### CODE REVIEW

File: lib/engine/step/g_18_cz/buy_corporation.rb [hunk 1]
```diff
@@ -58,7 +58,8 @@ def process_buy_corporation(action)
           end
 
           remove_duplicate_tokens(entity, corporation)
```
Comment (benjaminxscott) [inline lib/engine/step/g_18_cz/buy_corporation.rb:60]: do we still need to do the remove_dupe_tokens call if we're handling that below?
(notably we'd want to move the token price logic into here if we get rid of that function call)

Comment (Zwergenpunk) [reply lib/engine/step/g_18_cz/buy_corporation.rb:60]: yeah the duplicate removes automatic if there are 2 tokens in 1 city.

File: lib/engine/step/g_18_cz/reduce_tokens.rb [hunk 2]
```diff
@@ -6,6 +6,10 @@ module Engine
   module Step
     module G18CZ
       class ReduceTokens < ReduceTokens
+        def description
```
Comment (benjaminxscott) [inline lib/engine/step/g_18_cz/reduce_tokens.rb:9]: This doesn't seem to be showing up in the step description, in the testcase
