### PR TITLE
[1848] fix ghan visit logic and 8256

### LINKED ISSUE #8235: 1848: 2E incorrectly allows ending route from non-tokened location, and doesn't calculate revenue correctly
https://18xx.games/game/94160?action=595

In the game, the 2E is currently correctly routed and paying the correct revenue (start + end).
However, the implementation allows running the 2E from Perth, to Adelaide, to Alice Springs, for 120 (I think it's counting Perth and Adelaide for 60+60) which is illegal since VR doesn't have a token in Perth. 
Also, if VR routes the 2E (legally) from Melbourne to Adelaide to Alice Springs, the implementation also counts the revenue incorrectly as 120 (I think it's counting Melbourne and Adelaide for 60+60)

RAW: 8.2.5:
```
. A route for the 2E consists of two
locations: it starts at one of the
company’s own station tokens
and ends at the Alice Springs
off-board location. Any number
of intervening stations may be skipped, but the route may not go
through a city that is completely blocked by the station tokens
of other companies.
...

“The Ghan” train only counts Alice Springs and the city where
it starts.
```

FWIW I'm not sure if all 2Es are considered "The Ghan", or only the one purchased with the corresponding private

### LINKED ISSUE #8256: [1848] unable to upgrade 4 to D
https://18xx.games/game/95369?action=632

Corp has enough cash for upgrade, all 6s are sold, but when he clicks the button to upgrade the 4 to a D, he gets an error saying "not a buyable train".

image
image

### PR DESCRIPTION
**Pull request by bentziaxl**
fixes #8235
fixed #8256
fix typos (guage vs gauge)

### CODE REVIEW

File: lib/engine/game/g_1848/game.rb [hunk 1]
```diff
@@ -312,7 +312,7 @@ class Game < Game::Base
             min_price: 1,
             max_price: 40,
             revenue: 5,
-            desc: 'No special abilities. Can be bought for £1-£60',
+            desc: 'No special abilities. Can be bought for £1-£40',
```
Comment (benjaminxscott) [inline lib/engine/game/g_1848/game.rb:315]: this is already fixed fwiw
