### PR TITLE
[1880] fix minors not getting owner abilities

### LINKED ISSUE #8778: [1880] Foreign Investors do not benefit from Chinese Rivers Ferry Corporation
Belgian is owned by player with Chinese Rivers Ferry Corporation.
In OR 1.2, Belgian attempted to lay track on  I5 and was declined as it does not have Y20.
In OR 2.3, Belgian laid I5 and paid Y20.
German, owned by player with Yanda Ferry Company does correctly receive benefit.
[hs_udsptkwz_1675291853.json.txt](https://github.com/tobymao/18xx/files/10562876/hs_udsptkwz_1675291853.json.txt)

### PR DESCRIPTION
**Pull request by bentziaxl**
fix #8778

### CODE REVIEW

File: lib/engine/game/g_1880/minor.rb [hunk 1]
```diff
@@ -13,6 +13,18 @@ def num_shares_of(corporation, ceil: true)
           ceil ? num.ceil : num
         end
 
+        def all_abilities
+          all_abilities = @abilities
+          if owner.respond_to?(:companies)
+            all_abilities += owner.companies&.flat_map do |c|
+              c.all_abilities.select do |a|
+                a.when.to_s.include? 'owning_player'
```
Comment (tobymao) [inline lib/engine/game/g_1880/minor.rb:21]: always use parenthesis on method calls

Comment (bentziaxl) [reply lib/engine/game/g_1880/minor.rb]: done

**Review by tobymao — APPROVED** [review]
