### PR TITLE
Fix problems with Buy and Sell button changes

### LINKED ISSUE #2316: After recent GUI changes in 18MEX: Can buy 20% share from market
https://www.18xx.games/game/16134?action=374

When a player bought a share of B&O in the next SR, two buttons were offered for the next share purchase:  [Buy 10% share from market] and [Buy 20% share from market].  I'm not entirely sure why there are two buttons, as they did the same thing and you can't buy a pres share directly from the market.

image

### PR DESCRIPTION
**Pull request by perwestling**
Previous commit introduced possibility to show non-standard
percentage in 18MEX, but it introduced problems in other
titles. So this commit improves the solution and solves
a couple of issues.

Disregard president shares for pool shares if there are other
shares that can be bought. This means it will not be possible
to buy president's share directly from the market unless it
is the last one. (And the title need to handle that case.)

Do not let Treasury or Short share presence affect GUI
presentation. Before this fix, the "Buy a 10% Market share"
appeared when Treasury share was present, instead of just
"Buy Market Share".

Also, do not use 10% as the standard share size. Instead use
the share_percent of the corporation in question. This solves
the problem of 20% appearing for 5 share corporations in 1817.

Similar fixes for Sell view. Problem reported in issue #2325.

Fixes #2316 and #2325

### CODE REVIEW

**Comment by perwestling** [comment]
After this fix the situation in #2325 looks like before the original change:
image

**Comment by perwestling** [comment]
And after the fix the problem reported in #2316 now looks good:

image

**Comment by perwestling** [comment]
And in 18MEX the 10% shares are handled as normal shares:
image

If the player has 5% shares they get a "Sell a 5% Share" at a time. That is because selling 5% shares does not change the stock price. And it is a game specific bundler in 18MEX that achieves that only one is bundled at a time.
image

And finally, if there is a choice in market what can be bought, then both percentages is shown. This is general code but it might only affect 18MEX currently.
image

File: assets/app/view/game/buy_sell_shares.rb [hunk 1]
```diff
@@ -30,15 +30,17 @@ def render
           end
 
           # Put up one buy button for each buyable percentage share type in market.
-          # In case there are more than one type of percentages in market or if shares are not 10%
-          # (e.g. 18MEX), show percentage type on button.
-          pool_shares
+          # In case there are more than one type of percentages in market or if shares are not the
+          # standard percent (e.g. 5% in 18MEX), show percentage type on button.
+          # Do skip president's share in case there are other shares available.
+          buyables = pool_shares
```
Comment (tobymao) [inline assets/app/view/game/buy_sell_shares.rb:36]: one statement buyable = pool_shares.select do ...

Comment (perwestling) [reply assets/app/view/game/buy_sell_shares.rb:36]: I think it needs to be done in two steps, as I use the size of pool_shares (line 38) and buyable (line 40).

**Review by tobymao — APPROVED** [review]
