### PR TITLE
18Ireland merger fixes:

### LINKED ISSUE #5196: 18Ireland Users who could have proposed a merger were autopassed
In [this game](https://18xx.games/game/39559?action=327), at the linked step, all users were auto-passed instead of being able to offer mergers. Having clarified the rules with the book and in the general chat, I feel satisified that this is a bug and autopass is not working as intended here.

### LINKED ISSUE #5220: 18Ireland — Merger round ended prematurely
**What's your Game ID?**
https://18xx.games/game/39912?action=346

**How to Reproduce the Bug?**

The merger round didn't enter a second round.  All players have not passed in succession in the merger-proposing round.  May be related to other bugs filed on this game (5218 and 5219).  Apologies for the large number of issue reports, I'm fairly sure they're independent bugs but it's not clear.

### PR DESCRIPTION
**Pull request by jenf**
Merger code ignored corporations where player didn't own shares (fixes #5196)
Merger should allow multiple rounds until all players pass (fixes #5220)

I'm gonna migrate the existing games for the 5220 fix

### CODE REVIEW

File: migrate_game.rb [hunk 1]
```diff
@@ -62,44 +62,47 @@ def repair(game, original_actions, actions, broken_action)
     actions.insert(action_idx, home_token_h)
     return
   elsif broken_action['type'] == 'pass' &&
-    game.active_step.is_a?(Engine::Step::G1817::BuySellParShares) &&
+    game.active_step.is_a?(Engine::Game::G1817::Step::BuySellParShares) &&
```
Comment (michaeljb) [inline migrate_game.rb:65]: Sorry I missed all these with the original bundle change!

**Review by michaeljb — APPROVED** [review]
