### PR TITLE
[System18] Russia and Mississippi fixes

### LINKED ISSUE #12016: [System18: Russia] Game end later than expected
Hotseat game:
https://gist.github.com/ianwilson156/60c963d0edfbaf0571442373cbf00d16

The first 8-train was exported at the end of OR5.2, but the game continued to OR7.2 - it should have ended at OR6.2

The rule is:
"Sphinx takes the next new train at the end of each set of ORs."
which was meant to mean "at the end of the second OR of a set", not "at the beginning of an SR".
Apologies for the ambiguity.

### LINKED ISSUE #12023: [System18: Russia] Autopass gives error
When trying to pass the round and subsequent ones using the Autopass button, the server throws a reproducible "actions did not match" error. 

Normal passing worked 

https://18xx.games/game/223556

Passing after https://18xx.games/game/223556?action=97

**How to Reproduce the Bug?**
Click on auto-pass

Image

### LINKED ISSUE #12025: [System18: Mississippi] Warranty for train bought across
https://18xx.games/game/223378

OR5.1 KKN has bought across a 'used' 3-train from SPX and gets a warranty.
One should only get a warranty when buying a new train from the Bank.

### LINKED ISSUE #12028: [System18: Mississippi] Priority deal incorrect
https://18xx.games/game/223378

In SR5, I was the last to deal, but I got priority for SR6. 
That is very strange.

### LINKED ISSUE #12032: [System18: Russia] Can't pass buying train or emergency fund a train. Game stuck.
https://18xx.games/game/223556

https://18xx.games/game/223556?action=294

The company has no train. Shares were issued but still too little cash.

When pressing Done (Trains) the error message will shop up instead of emergency refinancing or nationalisation. When presesing Buy a message appears that the company has too little money.

Image

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #12016
Fixes #12023 
Fixes #12025 
Fixes #12028
Fixes #12032 

Will likely require pins.

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### Explanation of Change

For Russia map:
1. Fixed game ending too late when 8 train was exported
2. Fixed issue when auto-passing immediately after a minor was auctioned in a SR
3. Fixed problems with nationalizing a corp with shares in market and/or more tokens than SPX could take

For Mississippi map:
1. Fixed player ordering that wasn't happening after a SR
2. Fixed bug with giving "used" trains warranties

### CODE REVIEW

File: lib/engine/game/g_system18/step/buy_sell_par_bid_merge.rb [hunk 1]
```diff
@@ -45,6 +45,9 @@ def win_bid(winner, _company)
             @game.bank.spend(share_price.price * 2, entity)
 
             action = Action::Par.new(entity, corporation: corporation, share_price: share_price)
+            # give the generated Par action the same time stamp as the action that triggered the auction win
+            # this prevents problems with a programmed pass triggering on the Par
+            action.created_at = @game.actions.last.created_at
```
Comment (michaeljb) [inline lib/engine/game/g_system18/step/buy_sell_par_bid_merge.rb:50]: Nice! I wonder if this sort of fix would apply to any [other auto_action bugs](https://github.com/tobymao/18xx/issues?q=is%3Aissue%20state%3Aopen%20(label%3Aauto-skip%20OR%20label%3A%22auto%20actions%22)) out there 🤔

File: lib/engine/game/g_system18/map_ms_customization.rb [hunk 2]
```diff
@@ -245,14 +245,18 @@ def map_ms_init_round
         end
 
         def map_ms_reorder_players
-          return unless @players.any? { |p| !p.companies.empty? }
+          # call base game method if players have no privates
+          return self.class.superclass.instance_method(:reorder_players).bind_call(self) unless @players.any? do |p|
```
Comment (michaeljb) [inline lib/engine/game/g_system18/map_ms_customization.rb]: Hmmm I don't love needing `bind_call` but it's of course tricky with the metaprogramming already in place.

IMO this is at least a little easier to understand, take it or leave it:

```suggestion
          return Engine::Game::Base.instance_method(:reorder_players).bind_call(self) unless @players.any? do |p|
```

**Review by michaeljb — APPROVED** [review]

File: lib/engine/game/g_system18/map_ms_customization.rb [hunk 3]
```diff
@@ -245,14 +245,18 @@ def map_ms_init_round
         end
 
         def map_ms_reorder_players
-          return unless @players.any? { |p| !p.companies.empty? }
+          # call base game method if players have no privates
+          return Engine::Game::Base.instance_method(:reorder_players).bind_call(self) unless @players.any? do |p|
+                                                                                                  !p.companies.empty?
+                                                                                                end
```
Comment (michaeljb) [inline lib/engine/game/g_system18/map_ms_customization.rb]: rubocop

```suggestion
                                                                                               !p.companies.empty?
                                                                                             end
```

File: lib/engine/game/g_system18/map_ms_customization.rb (hunk 2 above)
Comment (roseundy) [reply lib/engine/game/g_system18/map_ms_customization.rb]: Yeah, it's probably better to reference Game explicitly.
