### PR TITLE
Auto-router support 1-stop Local trains

### LINKED ISSUE #5862: [1822] Auto Routing does not recognize that L trains can run "within" a station token.
Hotseat game: https://gist.github.com/Arctem/b20581f20818bba049d0cae441398b18

**How to Reproduce the Bug?**

- When running trains for 5 (or any other company without a connection to a second city) click "Auto".
- Observe that no route is created.
- Manually select the tile that the L train will run to and observe that the game does allow an L to run within a single city. (you might have to click "Reset" for this to work).

image

image

**Which Browser / Platform?**
Chrome 91.0.4472.114
Laptop, Debian variant

### LINKED ISSUE #6525: [1822+] Autorouting gets Confused by an LP and a 2T
https://18xx.games/game/62650?action=404

Here auto-routing runs the LP from London to the dit, not leaving a route for the 2T. The LP should run London alone, leaving London to the dit for the 2T route.

### PR DESCRIPTION
**Pull request by JoeB989**
They're already handled in Route and Game; the auto-router node walk was rejecting 1-stop paths
Fixes #6525
Fixes #5862

### CODE REVIEW

File: lib/engine/auto_router.rb [hunk 1]
```diff
@@ -96,7 +96,12 @@ def compute(corporation, **opts)
             assign.call(a, b) if a || b
           end
 
-          next if chains.empty?
+          # a 1-city Local train will have no chains but will have a left; route.revenue will reject if not valid for game
+          if chains.empty?
+            next if left.nil?
```
Comment (tobymao) [inline lib/engine/auto_router.rb:101]: next unless left
