### PR TITLE
Fix displayed stock price movement at end of market

### LINKED ISSUE #8536: [1817] Stock moves show "1 right" when at end of stock market
image

https://18xx.games/game/86792?action=1835

### PR DESCRIPTION
**Pull request by michaeljb**
No step actually implements `movement_str`, so I removed the check for it when defining `direction`.

Fixes #8536, which is actually applicable to more games than just 1817.

### CODE REVIEW

File: assets/app/view/game/dividend.rb [hunk 1]
```diff
@@ -37,24 +37,31 @@ def render
...
 
-              moves.map do |times, dir|
-                times.times { new_share = @game.stock_market.find_relative_share_price(new_share, dir) }
+              movement_str =
+                moves.map do |times, dir|
+                  real_moves = 0
+                  times.times do
+                    prev_price = new_share_price
+                    new_share_price = @game.stock_market.find_relative_share_price(new_share_price, dir)
+                    real_moves += 1 unless prev_price == new_share_price
```
Comment (crericha) [inline assets/app/view/game/dividend.rb:50]: Do you think we should break out if price doesn't change?
