### PR TITLE
Remove tile reservation to allow tile lays on NWR special

### LINKED ISSUE #1310: 82 neutral token can’t lay yellow tile bc neutral token
error says it says no implicit conversion of NilClass into integer
* 1882, issue with laying yellow tile i think bc private was used and moved token and replaced with neutral token

action number: 256

json:

{
  "id": 5521,
  "description": "Quick Live Game only play if can play fast ",
  "user": {
    "id": 24,
    "name": "Jac"
  },
  "players": [
    {
      "id": 24,
      "name": "Jac"
    },
    {
      "id": 738,
      "name": "mOCHU"
    },
    {
      "id": 1027,
      "name": "TIE53"
    },
    {
      "id": 523,
      "name": "MontyBrewster71"
    }
  ],
  "max_players": 4,
  "title": "1882",
  "settings": {
    "seed": 5.760232951369271e+37
  },
  "status": "active",
  "turn": 6,
  "round": "Operating Round",
  "acting": [
    738
  ],
  "result": {},
  "actions": [
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 1,
      "message": "hi everyone!!!"
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 2,
      "company": "TB",
      "price": 145
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 3,
      "message": "Good morning!"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 4,
      "message": "hi!"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 5,
      "message": "I haven't finished my coffee yet, so I'll blame my bad play on that :P"
    },
    {
      "type": "bid",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 6,
      "company": "SC",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 7,
      "company": "TB",
      "price": 150
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 8,
      "message": "good mornign!"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 9,
      "message": "i want coffee now "
    },
    {
      "type": "bid",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 10,
      "company": "NWR",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 11,
      "company": "SC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 12,
      "company": "NWR",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 13,
      "company": "SC",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 14,
      "company": "CP",
      "price": 185
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 15,
      "company": "HB",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 16,
      "company": "SC",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 17,
      "company": "SC",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "bid",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 19,
      "company": "SC",
      "price": 85
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 22,
      "company": "TB",
      "price": 155
    },
    {
      "type": "bid",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 23,
      "company": "TB",
      "price": 160
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 24,
      "company": "TB",
      "price": 165
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 26,
      "message": "guess I'm going the no privates route"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 27,
      "message": "i’m going no company route lol"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 28,
      "message": "(route not yet built, must be forged)"
    },
    {
      "type": "par",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 29,
      "corporation": "CPR",
      "share_price": "100,0,3"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 30,
      "message": "lol"
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "CPR_2"
      ]
    },
    {
      "type": "par",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 32,
      "corporation": "GT",
      "share_price": "71,4,3"
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "CPR_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 34,
      "shares": [
        "CPR_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "CPR_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 37,
      "shares": [
        "CPR_6"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 38,
      "shares": [
        "CPR_7"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 39,
      "shares": [
        "GT_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 40,
      "shares": [
        "GT_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 41,
      "shares": [
        "GT_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 42,
      "shares": [
        "GT_5"
      ]
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 43,
      "hex": "I5",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 44
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 45
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 46,
      "hex": "L8",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 47,
      "message": "u can place 2 tiles.. just saying.."
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 48,
      "message": "or am i mistaken?"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 49,
      "message": "No, I can, for $20. I'm good."
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 50,
      "hex": "K9",
      "tile": "55-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 51,
      "city": "J10-0-0",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 52,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 53,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 54,
      "message": "ah ok"
    },
    {
      "id": 55,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 56,
      "message": "trying the friendly double dit lay this time. we'll see how that goes"
    },
    {
      "id": 57,
      "type": "undo",
      "entity": "MontyBrewster71",
      "entity_type": "player"
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 58,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 59
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 60,
      "shares": [
        "GT_6"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 62,
      "message": "sorry, wanted 3 trains"
    },
    {
      "type": "sell_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 63,
      "shares": [
        "CPR_1",
        "CPR_4",
        "CPR_7"
      ],
      "percent": 30
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 64,
      "message": "np"
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 65,
      "shares": [
        "GT_7"
      ]
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 66
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 67
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 68
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 69
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 70,
      "shares": [
        "GT_8"
      ]
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 75,
      "message": "you know CPR didn’t buy trains right so won’t run "
    },
    {
      "type": "par",
      "entity": "Jac",
      "entity_type": "player",
      "id": 76,
      "corporation": "QLL",
      "share_price": "90,1,3"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 77,
      "message": "it'll run eventually!"
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 78
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 83,
      "hex": "J4",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "buy_train",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 85,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 86,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 87
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 88,
      "hex": "M7",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 89
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 90
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 91,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L8",
              "M7",
              "N6"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "L8",
              "K9"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "J10",
              "K9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 92,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 93
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 94,
      "shares": [
        "CPR_1"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "sell_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 97,
      "shares": [
        "GT_6"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 98,
      "shares": [
        "CPR_4"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 99
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 100
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 101
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 102,
      "shares": [
        "CPR_7"
      ]
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 103
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 104
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 105
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 106
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 107
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 108,
      "hex": "M5",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 109
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 111,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L8",
              "M7",
              "N6"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "L8",
              "K9"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "J10",
              "K9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 112,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 114,
      "hex": "K3",
      "tile": "57-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 115
    },
    {
      "type": "place_token",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 116,
      "city": "57-2-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 117,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 118,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 119
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 120,
      "shares": [
        "GT_6"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 121
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 122,
      "shares": [
        "CPR_8"
      ]
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 123
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 124
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 125
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 126
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 127
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 128,
      "hex": "L4",
      "tile": "9-3",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 129
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 130
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 131,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L8",
              "M7",
              "N6"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "L8",
              "K9"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "J10",
              "K9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 132,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 133
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 134,
      "hex": "H6",
      "tile": "9-4",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 136
    },
    {
      "type": "run_routes",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 137,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 138,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 139
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 140,
      "message": "This is so weird. The players with the companies have no privates, so they have no reason to push the trains."
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 141
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 142
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 143
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 144
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 145
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 146
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 147,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L8",
              "M7",
              "N6"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "L8",
              "K9"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "J10",
              "K9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 148,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 149
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 150,
      "hex": "G7",
      "tile": "57-3",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 151
    },
    {
      "type": "place_token",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 152,
      "city": "57-3-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 153,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 154,
      "kind": "payout"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 155,
      "message": "Just 9 more ORs and I'll end the game on stock value if nothing changes!"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 156,
      "message": "lol"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 157
    },
    {
      "type": "sell_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 158,
      "shares": [
        "CPR_2",
        "CPR_5",
        "CPR_1"
      ],
      "percent": 30
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 159,
      "shares": [
        "QLL_1"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 160
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 161
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 162,
      "message": "What? Selling my shares?!?"
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 163,
      "shares": [
        "CPR_2"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 164
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 165,
      "message": ":D"
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 166,
      "shares": [
        "QLL_2"
      ]
    },
    {
      "type": "sell_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 167,
      "shares": [
        "GT_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 168
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 169,
      "shares": [
        "QLL_3"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 170
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 171,
      "shares": [
        "CPR_5"
      ]
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 172
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 173,
      "shares": [
        "QLL_4"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 174
    },
    {
      "type": "buy_shares",
      "entity": "Jac",
      "entity_type": "player",
      "id": 175,
      "shares": [
        "QLL_5"
      ]
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 176
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 177,
      "shares": [
        "QLL_6"
      ]
    },
    {
      "type": "sell_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 178,
      "shares": [
        "QLL_1",
        "QLL_3",
        "QLL_6"
      ],
      "percent": 30
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 179
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 180
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 181
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 182
    },
    {
      "type": "par",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 183,
      "corporation": "HBR",
      "share_price": "90,1,3"
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 184
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 185,
      "message": "autopass unless any sells "
    },
    {
      "type": "buy_shares",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 186,
      "shares": [
        "CPR_1"
      ]
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 187
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 188
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 189
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 190,
      "shares": [
        "HBR_1"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 191
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 192
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 193
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 194
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 195,
      "shares": [
        "HBR_2"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 196
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 197
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 198
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 199
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 200,
      "shares": [
        "HBR_3"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 201
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 202
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 203
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 204
    },
    {
      "type": "sell_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 205,
      "shares": [
        "GT_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 206,
      "shares": [
        "HBR_4"
      ]
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 207
    },
    {
      "type": "pass",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 208
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 209
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 210
    },
    {
      "type": "pass",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 211
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 212
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 213
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 214,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L8",
              "M7",
              "N6"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "L8",
              "K9"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "J10",
              "K9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 215,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 216
    },
    {
      "type": "pass",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 217
    },
    {
      "type": "buy_train",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 218,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 219,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 220
    },
    {
      "type": "buy_company",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 221,
      "company": "NWR",
      "price": 160
    },
    {
      "id": 222,
      "type": "pass",
      "entity": "HBR",
      "entity_type": "corporation"
    },
    {
      "id": 223,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 224,
      "message": "why am i unable to use HBR's power to move my station marker?"
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 225,
      "message": "*NWR's power"
    },
    {
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company",
      "id": 226,
      "city": "G11-2-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company",
      "id": 227
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 228,
      "message": "you should be able to"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 229,
      "message": "It let me do it"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 230,
      "message": "and upgrade the new tile"
    },
    {
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company",
      "id": 231,
      "city": "G11-2-0",
      "slot": 0
    },
    {
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company",
      "id": 232,
      "city": "E5-0-1",
      "slot": 0
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 233,
      "message": "sometimes i have issues but someone else can always do it for em"
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 234,
      "message": "figured it out"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 235,
      "message": "now just click on tile "
    },
    {
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company",
      "id": 236
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 237,
      "message": "and can upgrade too"
    },
    {
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company",
      "id": 238,
      "city": "E5-0-0",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "NWR",
      "entity_type": "company",
      "id": 239,
      "hex": "E5",
      "tile": "59-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 240,
      "city": "59-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "HBR",
      "entity_type": "corporation",
      "id": 241
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 242,
      "hex": "F8",
      "tile": "2-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 243
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 244
    },
    {
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 245
    },
    {
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 246
    },
    {
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 247
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 248,
      "hex": "K3",
      "tile": "15-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 249
    },
    {
      "type": "run_routes",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 250,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 251,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 252,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 253
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 254
    },
    {
      "type": "place_token",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 255,
      "city": "J10-0-1",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 256,
      "hex": "I11",
      "tile": "1-0",
      "rotation": 0
    },
    {
      "type": "buy_company",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 257,
      "company": "HB",
      "price": 40
    },
    {
      "type": "buy_company",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 258,
      "company": "TB",
      "price": 280
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 259,
      "message": "can’t lay that yellow tile"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 260,
      "message": "Wadena?"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 261,
      "message": "yes"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 262,
      "message": "I can't either"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 263,
      "message": "My guess is it is a bug related to the NWR"
    },
    {
      "type": "message",
      "entity": "TIE53",
      "entity_type": "player",
      "id": 264,
      "message": "yep"
    },
    {
      "type": "message",
      "entity": "mOCHU",
      "entity_type": "player",
      "id": 265,
      "message": "eh?"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 266,
      "message": "\"no implicit conversionof NilClass into Integer\""
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 267,
      "message": "it says no implicit conversion of NilClass into integer"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 268,
      "message": "missed a space in there\\"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 269,
      "message": "File the bug report. We'll wait."
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 270,
      "message": "i’m filing "
    }
  ],
  "loaded": true,
  "created_at": 1596382987,
  "updated_at": 1596386468
}

### PR DESCRIPTION
**Pull request by jenf**
fixes #1310

### CODE REVIEW

File: lib/engine/part/city.rb [hunk 1]
```diff
@@ -49,6 +49,10 @@ def add_reservation!(entity, slot = nil)
         end
       end
 
+      def remove_reservation!(entity)
```
Comment (tobymao) [inline lib/engine/part/city.rb:52]: unecessary since resarvations is public

can just do action.city.reservations.delete in specialnwr unless you play to do other stuff in this helper
