### PR TITLE
[front page] Reset filters button clears selection

### LINKED ISSUE #7998: "Reset filters" doesn't reset input field
On the main page, in the Filters pulldown, select 1830. Only 1830 games are displayed (correctly)

Click Reset filters. All games are displayed again (correctly). But the pulldown still shows 1830 (incorrectly).

### PR DESCRIPTION
**Pull request by philcampeau**
Fixes #7998

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### Explanation of Change

Currently, if you filter for a game on the homepage of the site, and then click the `Reset filters` button, it clears the filter, but  leaves the previously selected filter game in the drop-down menu. 

This corrects that so that clicking `Reset filters` also clears the drop-down selection and resets it to (All titles)

### CODE REVIEW

File: assets/app/view/game_row_filters.rb [hunk 1]
```diff
@@ -41,7 +41,12 @@ def render_title(url_search_params)
 
     def render_reset
       attrs = {
-        on: { click: -> { update_filters('') } },
+        on: {
+          click: lambda do |_|
+            `document.querySelector('#game_filters select').value = ''`
```
Comment (michaeljb) [inline assets/app/view/game_row_filters.rb]: We should avoid writing raw JS like this when possible. Up in `render` you could capture the return value for `render_title`, pass that element as a new argument to `render_reset`, and then use the `Native` API to get to the value directly (there are a few examples of using `Native` and `elm` like this throughout the view codebase):

```suggestion
          click: lambda do
            Native(title_elm)&.elm&.value = ''`
```

Comment (philcampeau) [reply assets/app/view/game_row_filters.rb]: Thanks, done!

**Review by michaeljb — APPROVED** [review]
