### PR TITLE
[1880] fix end game code

### LINKED ISSUE #8755: [1880] The game didn't end
https://18xx.games/game/111595

As you see, it says that it ends at the end of OR 10.15 of QSR, but for some reason it didn't end.

### PR DESCRIPTION
**Pull request by bentziaxl**
fix #8755

### CODE REVIEW

File: assets/app/view/game/par_chart.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ class ParChart < Snabberb::Component
 
       def render
         @step = @game.round.active_step
-        @current_entity = @step.current_entity
+        @current_entity = @step&.current_entity
         @current_operator = @game.respond_to?(:current_operator) ? @game.current_operator : nil
```
Comment (bentziaxl) [inline assets/app/view/game/par_chart.rb:19]: at end game the market view fails as there is no @step current entity. This is used for parring logic only

File: lib/engine/round/operating.rb [hunk 2]
```diff
@@ -46,9 +46,13 @@ def after_process(action)
           return if entity.owner&.player? || entity.receivership?
         end
 
-        next_entity!
+        after_end_of_turn(action)
+
+        next_entity! unless @game.finished
       end
```
Comment (bentziaxl) [inline lib/engine/round/operating.rb:52]: needed, otherwise logs says:
**--- end game ... ----** 
player operates corp

**Review by crericha — APPROVED** [review]
