### PR TITLE
18CZ Fixed Upgrade And Discard Step

### LINKED ISSUE #3875: [18CZ] Cannot upgrade a train after acquisition if the acquisition puts the acquiring company over the train limit
https://18xx.games/game/27945?action=450

**How to Reproduce the Bug?**
NWB has just acquired VWB and is now over the train limit, and must discard at the train discard screen: 

Screen Shot 2021-02-14 at 8 05 11 PM

However after discarding down to the train limit, the acquisition is resolved and there is no longer an option to upgrade the acquired trains.

### PR DESCRIPTION
**Pull request by Zwergenpunk**
closes #3875

### CODE REVIEW

File: lib/engine/step/g_18_cz/buy_corporation.rb [hunk 1]
```diff
@@ -47,12 +47,14 @@ def process_buy_corporation(action)
           receiving << "companies (#{companies.join(', ')})" if companies.any?
 
           trains = @game.transfer(:trains, corporation, entity)
-          receiving << "trains (#{trains.map(&:name)})" if trains.any?
+          if trains.any?
```
Comment (jenf) [inline lib/engine/step/g_18_cz/buy_corporation.rb:50]: if !trains.empty?
