### PR TITLE
fix method missing error for can_merge?

### LINKED ISSUE #2939: [1817] - undefined method `can_merge?'
Link: https://18xx.games/game/20758

Player started bidding on a new company, but was unable to place its home station. When we reloaded the page, the console shows:
```
Uncaught 
a
args: Array(2)
0: a {$$id: 6740, id: 4227, name: "gatesman", cash: 2, companies: Array(0), …}
1: a {$$id: 7458, name: "SR", id: "SR", full_name: "Strasburg Railroad", shares_by_corporation: a, …}
length: 2
__proto__: t(0)
message: "undefined method `can_merge?' for #<Engine::Step::G1817::BuySellParShares:0x14e14>"
name: "can_merge?"
stack: "can_merge?: undefined method `can_merge?' for #<Engine::Step::G1817::BuySellParShares:0x14e14>↵    at a.$method_missing (https://18xx.games/assets/main.js:2:20031)↵    at a.n (https://18xx.games/assets/main.js:1:11652)↵    at a.$render_merge (https://18xx.games/assets/main.js:134:19904)↵    at a.$render (https://18xx.games/assets/main.js:134:13934)↵    at a.$h (https://18xx.games/assets/main.js:68:13843)↵    at a.$render_input (https://18xx.games/assets/main.js:142:32653)↵    at e (https://18xx.games/assets/main.js:142:32356)↵    at Object.I.yield1 (https://18xx.games/assets/main.js:1:13260)↵    at Array.$collect (https://18xx.games/assets/main.js:5:27210)↵    at Object.I.send (https://18xx.games/assets/main.js:1:15202)"
__proto__: a
```

My one guess is the player was trying to set the new railroad's home to the same as the home of one of their other railroads.

### PR DESCRIPTION
**Pull request by michaeljb**
[Fixes #2939]

### CODE REVIEW

File: assets/app/view/game/buy_sell_shares.rb [hunk 1]
```diff
@@ -161,6 +161,7 @@ def render_share_exchange(shares, company, source: 'Market')
 
       def render_merge
         return [] unless @step.current_actions.include?('choose')
+        return [] unless @step.respond_to?(:can_merge)
```
Comment (crericha) [inline assets/app/view/game/buy_sell_shares.rb:164]: Do you need a question mark at the end of :can_merge? to match the method in question on line 165?

Comment (crericha) [reply assets/app/view/game/buy_sell_shares.rb:164]: Tried it locally and it worked on the broken game, so I guess not.

Comment (crericha) [reply assets/app/view/game/buy_sell_shares.rb:164]: Recommend changing it to include the question mark, all the same.

Comment (michaeljb) [reply assets/app/view/game/buy_sell_shares.rb:164]: > Tried it locally and it worked on the broken game, so I guess not.

I'm guessing this is caused by however Opal handles function names with question marks, since you can't have that in JS. Definitely better to actually have it though
