### PR TITLE
Correct price for 5% shares (on the server side)

### LINKED ISSUE #1939: 18MEX: Crash after selling 0.5 NdM share during emergency buy
I tried to sell some shares including my 0.5 share of NdM to emergency buy a 4D and it let me buy it, but I got an error message saying I didn't have the money. The other players couldn't go forward and every time I refreshed the page it went back to my corp's train buy phase.
https://gist.github.com/nigelsandwich/221c409da1195ba6b500566429c44b9f

### LINKED ISSUE #1955: 18Mex - Error when purchasing floating share for UdY
https://www.18xx.games/game/12993

{
  "id": 12993,
  "description": "Private - SFCC 4P",
  "user": {
    "id": 33,
    "name": "jehayward"
  },
  "players": [
    {
      "id": 1591,
      "name": "pezinator"
    },
    {
      "id": 2306,
      "name": "Angst"
    },
    {
      "id": 33,
      "name": "jehayward"
    },
    {
      "id": 211,
      "name": "Mrichard"
    }
  ],
  "max_players": 4,
  "title": "18MEX",
  "settings": {
    "seed": 2.471653576009311e+38
  },
  "user_settings": null,
  "status": "active",
  "turn": 4,
  "round": "Stock Round",
  "acting": [
    2306
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 1,
      "company": "MIR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "Angst",
      "entity_type": "player",
      "id": 2,
      "company": "C",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 3,
      "company": "KCMO",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 4,
      "company": "KCMO",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 5,
      "company": "MCAR",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 6,
      "company": "KCMO",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 7,
      "company": "KCMO",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "Angst",
      "entity_type": "player",
      "id": 9,
      "company": "A",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 10,
      "company": "MIR",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 11,
      "company": "B",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 12,
      "company": "MIR",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 13,
      "company": "MIR",
      "price": 120
    },
    {
      "type": "bid",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 14,
      "company": "MIR",
      "price": 125
    },
    {
      "type": "bid",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 15,
      "company": "MIR",
      "price": 130
    },
    {
      "type": "bid",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 16,
      "company": "MIR",
      "price": 135
    },
    {
      "type": "bid",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 17,
      "company": "MIR",
      "price": 140
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "bid",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 19,
      "company": "MNR",
      "price": 140
    },
    {
      "type": "par",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 20,
      "corporation": "NdM",
      "share_price": "90,0,5"
    },
    {
      "type": "par",
      "entity": "Angst",
      "entity_type": "player",
      "id": 21,
      "corporation": "PAC",
      "share_price": "75,1,4"
    },
    {
      "type": "par",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 22,
      "corporation": "CHI",
      "share_price": "90,0,5"
    },
    {
      "type": "par",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 23,
      "corporation": "MC",
      "share_price": "75,1,4"
    },
    {
      "type": "par",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 24,
      "corporation": "TM",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 25,
      "shares": [
        "PAC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "CHI_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "MC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "TM_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "PAC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "CHI_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "MC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "TM_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "PAC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 34,
      "shares": [
        "MC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "TM_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 39
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 40,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "minor",
      "id": 41
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 42,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "C",
      "entity_type": "minor",
      "id": 43
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 44,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 45,
      "hex": "C6",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 46,
      "hex": "G6",
      "tile": "8-0",
      "rotation": 3
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 47,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 48,
      "hex": "C2",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 49,
      "hex": "D3",
      "tile": "57-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 50
    },
    {
      "type": "buy_train",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 51,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 52
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 53,
      "hex": "I8",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "id": 54,
      "hex": "H7",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 55,
      "type": "buy_train",
      "price": 100,
      "train": "2-5",
      "entity": "MC",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 56,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 57,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 58,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 59,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 60,
      "hex": "K8",
      "tile": "58-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 61,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 62
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 63,
      "hex": "J11",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 64,
      "hex": "K10",
      "tile": "8-2",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 65,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player",
      "id": 67
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 68
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 69
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 70,
      "shares": [
        "TM_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 75
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 76
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 77,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "minor",
      "id": 78
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 79,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "C",
      "entity_type": "minor",
      "id": 80
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 81,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 82,
      "hex": "H7",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 83
    },
    {
      "type": "run_routes",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 84,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 85,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 86,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 87
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 88,
      "hex": "F3",
      "tile": "8-3",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 89,
      "hex": "G4",
      "tile": "8-4",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 90
    },
    {
      "type": "run_routes",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 91,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "B1",
              "C2",
              "B3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 92,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 93,
      "train": "2-8",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 94
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 95,
      "hex": "L7",
      "tile": "8-5",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 96,
      "hex": "K6",
      "tile": "471-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 97,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K6",
              "L7",
              "K8"
            ],
            [
              "K8",
              "I8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 98,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 99,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 101
    },
    {
      "id": 102,
      "hex": "H11",
      "tile": "8-6",
      "type": "lay_tile",
      "entity": "TM",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 103,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 104,
      "hex": "H11",
      "tile": "8-6",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 105,
      "hex": "F11",
      "tile": "9-3",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "run_routes",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 107,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "I12",
              "H11",
              "F11",
              "D11"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 108,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 109,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_company",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 110,
      "company": "MCAR",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 111
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 112
    },
    {
      "type": "buy_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 113,
      "shares": [
        "MC_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player",
      "id": 114
    },
    {
      "type": "buy_shares",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 115,
      "shares": [
        "TM_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 116
    },
    {
      "type": "buy_shares",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 117,
      "shares": [
        "CHI_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 118
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 119,
      "shares": [
        "PAC_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 120
    },
    {
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player",
      "id": 121
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 122
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 123
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 124
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 125
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 126,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "B",
      "entity_type": "minor",
      "id": 127,
      "hex": "K6",
      "tile": "476-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 128,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ],
            [
              "K6",
              "L7",
              "K8"
            ],
            [
              "K8",
              "I8"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "C",
      "entity_type": "minor",
      "id": 129,
      "hex": "S12",
      "tile": "6-1",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 130,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 131,
      "hex": "I8",
      "tile": "14-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 132,
      "city": "14-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 133,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ]
          ]
        },
        {
          "train": "2-7",
          "connections": [
            [
              "K6",
              "L7",
              "K8"
            ],
            [
              "I8",
              "K8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 134,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 135,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 136
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 137,
      "hex": "D3",
      "tile": "15-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 138
    },
    {
      "type": "run_routes",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 139,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "B1",
              "C2",
              "B3"
            ]
          ]
        },
        {
          "train": "2-8",
          "connections": [
            [
              "D3",
              "B3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 140,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 141,
      "train": "3-3",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 142
    },
    {
      "id": 143,
      "hex": "E6",
      "tile": "15-1",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 144,
      "type": "buy_company",
      "price": 60,
      "entity": "MC",
      "company": "KCMO",
      "entity_type": "corporation"
    },
    {
      "id": 145,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 146,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 147,
      "hex": "E6",
      "tile": "15-1",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 148,
      "type": "buy_company",
      "price": 60,
      "entity": "MC",
      "company": "KCMO",
      "entity_type": "corporation"
    },
    {
      "id": 149,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 150,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 151,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 152,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "type": "buy_company",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 153,
      "company": "KCMO",
      "price": 60
    },
    {
      "type": "lay_tile",
      "entity": "KCMO",
      "entity_type": "company",
      "id": 154,
      "hex": "F5",
      "tile": "470-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 155,
      "hex": "E6",
      "tile": "15-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 156
    },
    {
      "type": "run_routes",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 157,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K6",
              "L7",
              "K8"
            ],
            [
              "I8",
              "K8"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ],
            [
              "E6",
              "G6",
              "H7",
              "I8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 158,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 159,
      "train": "3'-0",
      "price": 180,
      "variant": "3'"
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 160
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 161,
      "hex": "M10",
      "tile": "57-1",
      "rotation": 0
    },
    {
      "id": 162,
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 163,
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 164,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 165,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 166
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 167
    },
    {
      "id": 168,
      "type": "run_routes",
      "entity": "TM",
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "I12",
              "H11",
              "F11",
              "D11"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "M10",
              "O10"
            ],
            [
              "M10",
              "K10",
              "J11",
              "I12"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 169,
      "kind": "payout",
      "type": "dividend",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 170,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 171,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "type": "run_routes",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 172,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "I12",
              "H11",
              "F11",
              "D11"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "P11",
              "O10"
            ],
            [
              "M10",
              "O10"
            ],
            [
              "M10",
              "K10",
              "J11",
              "I12"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 173,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 174
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 175
    },
    {
      "id": 176,
      "hex": "J9",
      "tile": "9-4",
      "type": "lay_tile",
      "entity": "CHI",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 177,
      "type": "undo",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 178,
      "hex": "D5",
      "tile": "7-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 179
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 180
    },
    {
      "type": "run_routes",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 181,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ],
            [
              "E6",
              "D5",
              "F5"
            ]
          ]
        },
        {
          "train": "2-7",
          "connections": [
            [
              "E6",
              "G6",
              "H7",
              "I8"
            ],
            [
              "E6",
              "F5"
            ]
          ]
        },
        {
          "train": "3-2",
          "connections": [
            [
              "I8",
              "K8"
            ],
            [
              "K6",
              "L7",
              "K8"
            ],
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 182,
      "kind": "payout"
    },
    {
      "type": "buy_company",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 183,
      "company": "MIR",
      "price": 150
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 184,
      "hex": "I4",
      "tile": "6-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 185,
      "hex": "J5",
      "tile": "4-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 186,
      "city": "476-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 187,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "B1",
              "C2",
              "B3"
            ]
          ]
        },
        {
          "train": "2-8",
          "connections": [
            [
              "D3",
              "B3"
            ]
          ]
        },
        {
          "train": "3-3",
          "connections": [
            [
              "I8",
              "K8"
            ],
            [
              "K6",
              "L7",
              "K8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 188,
      "kind": "payout"
    },
    {
      "id": 189,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 190,
      "type": "undo",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 191,
      "hex": "J9",
      "tile": "8-7",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 192,
      "hex": "I10",
      "tile": "57-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 193
    },
    {
      "type": "run_routes",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 194,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K6",
              "L7",
              "K8"
            ],
            [
              "I8",
              "K8"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ],
            [
              "E6",
              "G6",
              "H7",
              "I8"
            ]
          ]
        },
        {
          "train": "3'-0",
          "connections": [
            [
              "I10",
              "J9",
              "I8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 195,
      "kind": "payout"
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 196,
      "hex": "O10",
      "tile": "479MC-0",
      "rotation": 0
    },
    {
      "id": 197,
      "city": "479MC-0-0",
      "slot": 1,
      "type": "place_token",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "id": 198,
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation"
    },
    {
      "type": "place_token",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 199,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 200,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "I12",
              "H11",
              "F11",
              "D11"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "P11",
              "O10"
            ],
            [
              "O10",
              "M10"
            ],
            [
              "M10",
              "K10",
              "J11",
              "I12"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 201,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 202
    },
    {
      "type": "sell_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 203,
      "shares": [
        "NdM_7"
      ],
      "percent": 5
    },
    {
      "type": "par",
      "entity": "Angst",
      "entity_type": "player",
      "id": 204,
      "corporation": "UdY",
      "share_price": "75,1,4"
    },
    {
      "type": "buy_shares",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 205,
      "shares": [
        "CHI_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 206
    },
    {
      "type": "buy_shares",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 207,
      "shares": [
        "NdM_7"
      ],
      "percent": 5
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 208
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 209,
      "shares": [
        "MC_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 210
    },
    {
      "type": "buy_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 211,
      "shares": [
        "UdY_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player",
      "id": 212
    },
    {
      "type": "buy_shares",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 213,
      "shares": [
        "NdM_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "jehayward",
      "entity_type": "player",
      "id": 214
    },
    {
      "type": "buy_shares",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 215,
      "shares": [
        "NdM_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Mrichard",
      "entity_type": "player",
      "id": 216
    },
    {
      "type": "buy_shares",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 217,
      "shares": [
        "NdM_3"
      ],
      "percent": 10
    },
    {
      "id": 218,
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player"
    },
    {
      "id": 219,
      "type": "pass",
      "entity": "Angst",
      "entity_type": "player"
    },
    {
      "id": 220,
      "type": "undo",
      "entity": "jehayward",
      "entity_type": "player"
    },
    {
      "id": 221,
      "type": "undo",
      "entity": "Angst",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "pezinator",
      "entity_type": "player",
      "id": 222
    },
    {
      "type": "buy_shares",
      "entity": "Angst",
      "entity_type": "player",
      "id": 223,
      "shares": [
        "UdY_2"
      ],
      "percent": 10
    }
  ],
  "loaded": true,
  "created_at": 1603040749,
  "updated_at": 1603211447
}

### LINKED ISSUE #1978: 18MEX: Error when buying 5th share in MEX corporation
We are having issues with our game. It seems I cannot buy my 5th share in #13502
It marksan error code
Screen Shot 2020-10-22 at 10 47 40 PM

### LINKED ISSUE #2006: 18Mex Force Buy Issue
I had to force buy...but it says I don't have the money and now game is 'out of synce'

image

https://www.18xx.games/game/13258

### PR DESCRIPTION
**Pull request by perwestling**
share.rb and share_bundle.rb gave 0 as price for share counts
not evenly divisable by 10. This caused the 5% of NdM in 18MEX
to be excluded from the value (on the server side).

When paying out revenue, use float for num_shares to handle
the NdM case.

In both cases ceil is used to round up.

This might fix several problems that has been reported, although it is hard to verify.
But I think the following might be solved:

- Fixes #1978 
- Fixes #1939 
- Fixes #1955 
- Fixes #2006 

If this PR is approved I intend to close the issues.

### CODE REVIEW

**Comment by perwestling** [comment]
@tobymao and @jenf : I took the 1817 change for revenue one step further. This is needed to handle float numbers for number of shares.
With this fix buying/selling 5% shares will get the correct price. And odd number of 5% shares now give the right revenue. (Before it gave 0.)
And the server should also have the correct value of corporations when comparing final result.

It did pass all existing tests. There might be more places that might need similar corrections, but I have not stumbled upon any more. The name of the method (_float) might be a bad one.

File: lib/engine/step/dividend.rb [hunk 1]
```diff
@@ -95,8 +95,8 @@ def payout(entity, revenue)
       end
 
       def dividends_for_entity(entity, holder, per_share)
-        # 1817 2 share half pay uses floats
-        (holder.num_shares_of(entity) * per_share).to_i
+        # 1817 2 share half pay uses floats, for 18MEX num_shares can be a float for NdM
+        (holder.num_shares_of_float(entity) * per_share).ceil
```
Comment (jenf) [inline lib/engine/step/dividend.rb:99]: This won't break 1817, if other games needs to do it differently can subclass.

**Review by jenf — COMMENTED** [review]
Looks fine

File: lib/engine/step/dividend.rb (hunk 1 above)
Comment (perwestling) [reply lib/engine/step/dividend.rb:99]: An alternative could be to subclass this method in 18MEX. Do not know how many other titles there are that uses 5% shares?
(Think there are a few, but not that many.)

Anyway, I was considering if there is a situation where the player gets their revenue rounded up, while revenue for the corporation would get rounded down? 
But maybe this is a very rare situation, so a potential 1$ might not have that much effect so it is worth considering?

File: lib/engine/share.rb [hunk 2]
```diff
@@ -29,7 +29,11 @@ def id
     end
 
     def num_shares
-      @percent / corporation.share_percent
+      num_shares_float.ceil
```
Comment (tobymao) [inline lib/engine/share.rb:32]: can we do the inverse? keep num_shares the raw value

@percent.to_f / corporation.share_percent

File: lib/engine/share.rb [hunk 3]
```diff
@@ -38,7 +42,7 @@ def price_per_share
     end
 
     def price
-      price_per_share * num_shares
+      (price_per_share * num_shares_float).ceil
```
Comment (tobymao) [inline lib/engine/share.rb:45]: (price_per_share * num_shares).ceil

File: lib/engine/share.rb (hunk 2 above)
Comment (tobymao) [reply lib/engine/share.rb:32]: you could do def num_shares(ceil: true / false)

num = @percent.to_f / corporation.share_percent
ceil ? num.ceil : num

File: lib/engine/share.rb (hunk 3 above)
Comment (perwestling) [reply lib/engine/share.rb:45]: Updated

File: lib/engine/share.rb (hunk 2 above)
Comment (perwestling) [reply lib/engine/share.rb:32]: Ok, updated

**Comment by perwestling** [comment]
@tobymao Have now handled your review comments.

File: lib/engine/share_bundle.rb [hunk 4]
```diff
@@ -43,7 +44,7 @@ def price_per_share
     end
 
     def price
-      price_per_share * num_shares
+      (price_per_share.to_f * num_shares(ceil: false)).ceil
```
Comment (tobymao) [inline lib/engine/share_bundle.rb:47]: i don't think you need to_f here

File: lib/engine/share_holder.rb [hunk 5]
```diff
@@ -27,7 +27,11 @@ def presidencies
     end
 
     def num_shares_of(corporation)
```
Comment (tobymao) [inline lib/engine/share_holder.rb:29]: let's change this section too?

File: lib/engine/share_bundle.rb (hunk 4 above)
Comment (perwestling) [reply lib/engine/share_bundle.rb]: Correct, updated

File: lib/engine/share_holder.rb (hunk 5 above)
Comment (perwestling) [reply lib/engine/share_holder.rb]: Ok, updated

**Comment by perwestling** [comment]
@tobymao Updated version pushed

**Review by tobymao — APPROVED** [review]
