### PR TITLE
[18CZ] Optimized EMR Info

### LINKED ISSUE #4100: 18CZ EMR text needs UI improvement
https://18xx.games/game/27956?action=535

NWB is required to buy a train. The text below about selling shares and declaring bankruptcy is incorrect, and should be suppressed. Buying the train results in the appropriate loan being taken.

NWB has K170.
ChrisShaffer must contribute K180 for NWB to afford a train from the Depot.
ChrisShaffer has K99 in cash.
ChrisShaffer has K0 in sellable shares.
ChrisShaffer must sell shares to raise at least K81.
ChrisShaffer does not have enough liquidity to contribute towards NWB buying a train from the Depot. NWB must buy a train from another corporation, or ChrisShaffer must declare bankruptcy.

### PR DESCRIPTION
**Pull request by Zwergenpunk**
Adjusted the buy_train presidency_contribution to show the correct infos for 18cz.

Added a global constant to allow selling shares, which will then hide all the selling shares information.

Also needed to add a overload for the cheapest price since in 18CZ the cheapest variant of a type is needed.

closes #4100

### CODE REVIEW

File: lib/engine/game/g_18_cz/step/buy_train.rb [hunk 1]
```diff
@@ -74,6 +74,18 @@ def train_available?(entity, train)
...
+          def cheapest_train_price(corporation)
+            cheapest_train = @depot.min_depot_train.variants.values.find do |item|
+              @game.train_of_size?(item, corporation.type)
+            end
+            cheapest_train[:price]
+          end
+
+          def must_take_loan?(corporation)
+            price = cheapest_train_price(corporation)
+            @game.buying_power(corporation) < price
```
Comment (michaeljb) [inline lib/engine/game/g_18_cz/step/buy_train.rb:87]: This shows the loan message even when the president has enough cash

Screenshot 2021-03-12 212403

gist - https://gist.github.com/michaeljb/bcb8e0a1ad8644ae0d3c32e8301baa40


Looks like this fixes it:

```suggestion
            (@game.buying_power(corporation) + corporation.owner.cash) < price
```

Comment (michaeljb) [reply lib/engine/game/g_18_cz/step/buy_train.rb:87]: Once this is fixed, I think the PR is good to go 👍

File: assets/app/view/game/buy_trains.rb [hunk 2]
```diff
@@ -16,56 +16,61 @@ class BuyTrains < Snabberb::Component
...
+        cheapest_train_price = if step.respond_to?(:cheapest_train_price)
+                                 step.cheapest_train_price(@corporation)
+                               else
+                                 @depot.min_depot_price
+                               end
         cash = @corporation.cash + player.cash
-        share_funds_required = @depot.min_depot_price - cash
+        share_funds_required = cheapest_train_price - cash
         share_funds_allowed = if @game.class::EBUY_DEPOT_TRAIN_MUST_BE_CHEAPEST
                                 share_funds_required
```
Comment (michaeljb) [inline assets/app/view/game/buy_trains.rb:33]: Instead of having multiple conditionals that check `@game.class::EBUY_CAN_SELL_SHARES`, maybe `share_funds_allowed` could just be set to 0? Something like this:

```suggestion
        share_funds_allowed = if @game.class::EBUY_CAN_SELL_SHARES
                                0
                              elsif @game.class::EBUY_DEPOT_TRAIN_MUST_BE_CHEAPEST
                                share_funds_required
```

File: lib/engine/game/g_18_cz/step/buy_train.rb (hunk 1 above)
Comment (Zwergenpunk) [reply lib/engine/game/g_18_cz/step/buy_train.rb:87]: thanks for double checking :)

File: assets/app/view/game/buy_trains.rb (hunk 2 above)
Comment (Zwergenpunk) [reply assets/app/view/game/buy_trains.rb:33]: When I just set share_funds_allowed to 0 , 
```
 if share_funds_required.positive?
            children << h(:div, "#{player.name} #{verb} sell shares to raise at least "\
                                "#{@game.format_currency(share_funds_required)}.")
          end
 ```
 still is true. I made an big if around all of the texts
