### PR TITLE
[18USA] Bug fixes

### LINKED ISSUE #7331: 18USA Phase 3 doesn't start after 2+ Trains Exported
In the Rulebook 6.4 
End of the operating round 2: Export all remaining 2+
trains and begin phase 3 (do not export a 3-train).

HOTSEAT GAME
https://gist.github.com/Narvinyar/d76e46d1a2599303a21cc7ca012c4ea5

### LINKED ISSUE #7338: 18USA Force discard Pullmans during M&A
Please fill out the bug report title with the game name and description

Pullmans are force discarded with no way to bypass during M&A rounds. Nowhere in the rulebook does it say that Pullmans must be discarded during M&A. 

**What's your Game ID?**

https://18xx.games/game/74773

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

https://18xx.games/game/74773?action=1353

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

https://gist.github.com/Narvinyar/dbd3f8bb98161cf13844b65dc971631f

### PR DESCRIPTION
**Pull request by crericha**
Fixes #7331 
Fixes #7338

### CODE REVIEW

**Comment by crericha** [comment]
One game may need to be archived

File: lib/engine/game/g_18_usa/step/scrap_train_module.rb [hunk 1]
```diff
@@ -41,7 +41,6 @@ def scrap_train(train)
             @game.bank.spend(pullman_scrap_value, train.owner)
             @game.log << "#{train.owner.name} scraps a pullman for #{@game.format_currency(pullman_scrap_value)}"
             @game.depot.reclaim_train(train)
-            # @game.reset_crowded_corps
```
Comment (tobymao) [inline lib/engine/game/g_18_usa/step/scrap_train_module.rb:44]: can you delete this comment?
