### PR TITLE
[1824] Correct president share assignment and ownership of national

### LINKED ISSUE #12226: [1824] Incorrect cert counts
Game :https://18xx.games/game/228694

The four players all have 16 certs, and two presidencies. We should all have 18 shares. But I have 17 shares and player TheFlow has 19 shares. 

Somewhere along the way the cert count got derailed! 

I'm not sure how I can check where exactly it went wrong.

Thanks!

### PR DESCRIPTION
**Pull request by perwestling**
Fixes #12226, #12063, #12243

## Before clicking "Create"

- [X] Branch is derived from the latest `master`
- [X] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [X] Code passes linter with `docker compose exec rack rubocop -a`
- [X] Tests pass cleanly with `docker compose exec rack rake`

This does affect at least some games, even completed ones. Do pin / archive as appropriate.

This PR is derived from #12325 which has the fixtures and unit tests, and is therefor in Draft.
So when #12325 is merged I will rebase and publish this for review.

## Implementation Notes
Have revisited merge method to make it more robust.

Changed assignment of president share. This caused an issue during formation as president share was given to the owner of primary pre-staatsbahn, and then transfer was done, which might mess up ownership.

Have created 4 unit tests for formation; one for each national, and then one where presidency goes to a player that do not own primary pre-staatsbahn.

### Explanation of Change
Some differences in how minors are handled in 1824 and 1837 requires the code to be split. 

### Screenshots
N/A

### Any Assumptions / Hacks
N/A

### CODE REVIEW

**Comment by perwestling** [comment]
Have now rebased this to latest version of master. Ready for review.

File: lib/engine/game/g_1824/game.rb
Comment (ollybh) [inline lib/engine/game/g_1824/game.rb]: This isn't part of the current PR, but I noticed this block: these three lines can be replaced with a single statement: `tie_breaker |= @players`.

Comment (ollybh) [inline lib/engine/game/g_1824/game.rb]: The `|| -1` isn't needed, is it? You've just added any missing players to `tie_breaker`.

File: lib/engine/game/g_1824/game.rb [hunk 1]
```diff
@@ -226,8 +226,10 @@ def set_national_president!(national, tie_breaker)
           return unless current_president != president
```
Comment (ollybh) [inline lib/engine/game/g_1824/game.rb]: I'm surprised Rubocop doesn't object to the double negative:
```suggestion
          return if current_president == president
```

File: lib/engine/game/g_1824/game.rb [hunk 2]
```diff
@@ -617,14 +619,12 @@ def merge_minor!(minor, corporation, allow_president_change: true)
...
           @log << "#{owner.name} receives #{num_shares} share#{num_shares > 1 ? 's' : ''} of #{corporation.name}"
           share.buyable = true
-
-          # 1824 fix. We explicitly set allow_president_change to true here as we otherwise get a strange
-          # behavior when presidency decided for nationals. Might need revisiting.
-          @share_pool.transfer_shares(share.to_bundle, owner, allow_president_change: true)
-
+          @share_pool.transfer_shares(ShareBundle.new([share]), owner, allow_president_change: allow_president_change)
+          minor_share = owner.shares_by_corporation[minor].first
+          @share_pool.transfer_shares(ShareBundle.new([minor_share]), minor, allow_president_change: false)
```
Comment (ollybh) [inline lib/engine/game/g_1824/game.rb]: Is this needed? You're about to close the minor and they can't be restarted.
