### PR TITLE
Fix issue checking playercount 

### LINKED ISSUE #11064: Unable to import hotseat game
It is no longer possible to import a JSON game file. Attempting to do this gives an error:
```Uncaught title: undefined method `title' for nil```

The error is occurring here:
https://github.com/tobymao/18xx/blob/edc5f9e1b9ad202232e4e7d896fcbd74cc7d0050/assets/app/view/create_game.rb#L411

Reverting commit a0ced7ac74 makes it possible to import hotseat games again.

[CC @benjaminxscott]

### PR DESCRIPTION
**Pull request by benjaminxscott**
Fixes #11064

After this change, JSON import and game creation all work

In the case of imported games, `selected_game_or_variant` is Nil so the code was bailing when `title` was set.

This was due to where I was checking playercount, as part of a codepath that handled all 3 game types (multi, hotseat, json)

Now it only checks playercount for multiplayer 

I refactored this function to be (hopefully) more readable. 

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [NA] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### Screenshots

To confirm that game creation and import works:

[import game.webm](https://github.com/user-attachments/assets/9ee0e72c-4961-4c59-8d4b-eae3a65ee0fd)

[create_multi_and_hotseat.webm](https://github.com/user-attachments/assets/095cf2d8-aad1-46b1-b21e-9977cc94f31c)

### CODE REVIEW

File: assets/app/view/create_game.rb [hunk 1]
```diff
@@ -408,44 +408,47 @@ def render_game_type
...
+          game_data = JSON.parse(game_params['game_data'])
+        rescue JSON::ParserError => e
+          return store(:flash_opts, e.message)
+        end
       end
 
+      players = game_params
+      .select { |k, _| k.start_with?('player_') }
+      .values
+      .map { |name| name.gsub(/\s+/, ' ').strip }
```
Comment (ollybh) [inline assets/app/view/create_game.rb:448]:
```suggestion
      .map { |_, name| name.gsub(/\s+/, ' ').strip }
```

File: assets/app/view/create_game.rb [hunk 2]
```diff
@@ -408,44 +408,47 @@ def render_game_type
...
-      if game_params[:min_players].to_i < @min_p[title] || game_params[:max_players].to_i > @max_p[title]
-        return store(:flash_opts,
-                     'Invalid playercount')
-      end
 
-      if @mode == :multi
+      title = selected_game_or_variant&.title
+
+      case @mode
+      when :multi
```
Comment (ollybh) [inline assets/app/view/create_game.rb:418]:
```suggestion

      case @mode
      when :multi
        title = selected_game_or_variant&.title
```

**Review by ollybh — COMMENTED** [review]
I've tested this locally and confirm it fixes #11064 for me. Thanks!
The rest of the changes look mostly OK, though I'm not familiar with this bit of the codebase.

File: assets/app/view/create_game.rb (hunk 1 above)
Comment (benjaminxscott) [reply assets/app/view/create_game.rb]: Sweet yeah I didn't tweak this LoC but I grok this being easier to read while we're refactoring stuff
