### PR TITLE
[18CZ] allow purple upgrade from double-dit to green dit

### LINKED ISSUE #3874: [18CZ] Could not upgrade tile F21 from #2 (yellow double town) to #887p (green purple-edged single town)
https://18xx.games/game/27945?action=231

**How to Reproduce the Bug?**
At this point in the game, BCB tried to use the private ability to upgrade tile F21 from #2 to #887p. This should should be permitted as per the tile upgrade chart:
Screen Shot 2021-02-14 at 6 02 26 PM

However no tiles upgrade options were available after selecting the private company and then clicking on tile F21.

Screen Shot 2021-02-14 at 7 42 17 PM

### LINKED ISSUE #3882: [18CZ] Cannot upgrade double-town tiles with Local Railway
Or at least tile #55 in this instance. All of the double-town tiles are upgradable with purple-edge tiles according to the tile upgrade chart.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 1,
      "created_at": 1613382027,
      "company": "S1",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "Fred",
      "entity_type": "player",
      "id": 2,
      "created_at": 1613382035,
      "company": "S3",
      "price": 35
    },
    {
      "type": "undo",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 3,
      "created_at": 1613382041
    },
    {
      "type": "bid",
      "entity": "Fred",
      "entity_type": "player",
      "id": 4,
      "created_at": 1613382045,
      "company": "S2",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 5,
      "created_at": 1613382072,
      "company": "S3",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "Velma",
      "entity_type": "player",
      "id": 6,
      "created_at": 1613382079,
      "company": "L1",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Velma",
      "entity_type": "player",
      "id": 7,
      "created_at": 1613382082,
      "company": "L2",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 8,
      "created_at": 1613382105,
      "company": "M1",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Fred",
      "entity_type": "player",
      "id": 9,
      "created_at": 1613382110,
      "company": "S4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 10,
      "created_at": 1613382136,
      "company": "M2",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 11,
      "created_at": 1613382142,
      "company": "S5",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Fred",
      "entity_type": "player",
      "id": 12,
      "created_at": 1613382153,
      "company": "M3",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 13,
      "created_at": 1613382181,
      "company": "S6",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Velma",
      "entity_type": "player",
      "id": 14,
      "created_at": 1613382379,
      "company": "L3",
      "price": 65
    },
    {
      "type": "undo",
      "entity": "Velma",
      "entity_type": "player",
      "id": 15,
      "created_at": 1613382516
    },
    {
      "type": "bid",
      "entity": "Velma",
      "entity_type": "player",
      "id": 16,
      "created_at": 1613382610,
      "company": "M4",
      "price": 55
    },
    {
      "type": "pass",
      "entity": "Velma",
      "entity_type": "player",
      "id": 17,
      "created_at": 1613382628
    },
    {
      "type": "bid",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 18,
      "created_at": 1613382642,
      "company": "L4",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Fred",
      "entity_type": "player",
      "id": 19,
      "created_at": 1613382646,
      "company": "L6",
      "price": 80
    },
    {
      "type": "undo",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 20,
      "created_at": 1613382654
    },
    {
      "type": "undo",
      "entity": "Fred",
      "entity_type": "player",
      "id": 21,
      "created_at": 1613382656
    },
    {
      "type": "bid",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 22,
      "created_at": 1613382668,
      "company": "L3",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "Fred",
      "entity_type": "player",
      "id": 23,
      "created_at": 1613382675,
      "company": "L4",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 24,
      "created_at": 1613382786,
      "company": "L5",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 25,
      "created_at": 1613382792
    },
    {
      "type": "pass",
      "entity": "Fred",
      "entity_type": "player",
      "id": 26,
      "created_at": 1613382793
    },
    {
      "type": "pass",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 27,
      "created_at": 1613382795
    },
    {
      "type": "par",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 28,
      "created_at": 1613382853,
      "corporation": "BCB",
      "share_price": "55,0,4"
    },
    {
      "type": "par",
      "entity": "Fred",
      "entity_type": "player",
      "id": 29,
      "created_at": 1613382865,
      "corporation": "VBW",
      "share_price": "55,0,4"
    },
    {
      "type": "par",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 30,
      "created_at": 1613382881,
      "corporation": "OFE",
      "share_price": "50,0,2"
    },
    {
      "type": "par",
      "entity": "Velma",
      "entity_type": "player",
      "id": 31,
      "created_at": 1613383092,
      "corporation": "MW",
      "share_price": "50,0,2"
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 32,
      "created_at": 1613383100,
      "hex": "E16",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 33,
      "created_at": 1613383110,
      "hex": "E14",
      "tile": "55-0",
      "rotation": 1
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 34,
      "created_at": 1613383118
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1613383150
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 36,
      "created_at": 1613383157,
      "hex": "E16",
      "tile": "5-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 37,
      "created_at": 1613383165,
      "hex": "E14",
      "tile": "55-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 38,
      "created_at": 1613383171,
      "train": "2a-0",
      "price": 70,
      "variant": "2a"
    },
    {
      "type": "buy_train",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1613383176,
      "train": "2a-1",
      "price": 70,
      "variant": "2a"
    },
    {
      "type": "pass",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 40,
      "created_at": 1613383185
    },
    {
      "type": "lay_tile",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 41,
      "created_at": 1613383245,
      "hex": "I10",
      "tile": "5-1",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 42,
      "created_at": 1613383250,
      "hex": "I12",
      "tile": "201-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1613383253
    },
    {
      "type": "buy_train",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1613383255,
      "train": "2a-2",
      "price": 70,
      "variant": "2a"
    },
    {
      "type": "buy_train",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1613383257,
      "train": "2a-3",
      "price": 70,
      "variant": "2a"
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1613383260
    },
    {
      "type": "lay_tile",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1613383276,
      "hex": "C26",
      "tile": "201-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 48,
      "created_at": 1613383280,
      "hex": "C24",
      "tile": "5-2",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1613383287
    },
    {
      "type": "buy_train",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 50,
      "created_at": 1613383289,
      "train": "2a-4",
      "price": 70,
      "variant": "2a"
    },
    {
      "type": "buy_train",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1613383291,
      "train": "2b-0",
      "price": 70,
      "variant": "2b"
    },
    {
      "type": "buy_company",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1613383358,
      "company": "S3",
      "price": 40
    },
    {
      "type": "buy_company",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1613383363,
      "company": "S6",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1613383367
    },
    {
      "type": "lay_tile",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1613383380,
      "hex": "F23",
      "tile": "57-0",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 56,
      "created_at": 1613383384,
      "hex": "G24",
      "tile": "5-3",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 57,
      "created_at": 1613383386
    },
    {
      "type": "buy_train",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1613383387,
      "train": "2b-1",
      "price": 70,
      "variant": "2b"
    },
    {
      "type": "buy_train",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 59,
      "created_at": 1613383390,
      "train": "2b-2",
      "price": 70,
      "variant": "2b"
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 60,
      "created_at": 1613383430
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1613383434
    },
    {
      "type": "buy_shares",
      "entity": "Velma",
      "entity_type": "player",
      "id": 62,
      "created_at": 1613383457,
      "shares": [
        "OFE_1"
      ],
      "percent": 25
    },
    {
      "type": "par",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 63,
      "created_at": 1613383479,
      "corporation": "EKJ",
      "share_price": "50,0,2"
    },
    {
      "type": "buy_shares",
      "entity": "Fred",
      "entity_type": "player",
      "id": 64,
      "created_at": 1613383498,
      "shares": [
        "OFE_2"
      ],
      "percent": 25
    },
    {
      "type": "buy_shares",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 65,
      "created_at": 1613383506,
      "shares": [
        "MW_1"
      ],
      "percent": 25
    },
    {
      "type": "buy_shares",
      "entity": "Velma",
      "entity_type": "player",
      "id": 66,
      "created_at": 1613383515,
      "shares": [
        "MW_2"
      ],
      "percent": 25
    },
    {
      "type": "pass",
      "entity": "Fred",
      "entity_type": "player",
      "id": 67,
      "created_at": 1613383523
    },
    {
      "type": "pass",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 68,
      "created_at": 1613383524
    },
    {
      "type": "pass",
      "entity": "Velma",
      "entity_type": "player",
      "id": 69,
      "created_at": 1613383525
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 70,
      "created_at": 1613383555
    },
    {
      "type": "pass",
      "entity": "Velma",
      "entity_type": "player",
      "id": 71,
      "created_at": 1613383663
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1613383709
    },
    {
      "type": "redo",
      "entity": "Velma",
      "entity_type": "player",
      "id": 73,
      "created_at": 1613383742
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1613383748,
      "hex": "E12",
      "tile": "8889-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 75,
      "created_at": 1613383750,
      "city": "8889-0-1",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 76,
      "created_at": 1613383759,
      "routes": [
        {
          "train": "2a-0",
          "connections": [
            [
              "E12",
              "E14"
            ]
          ],
          "hexes": [
            "E14",
            "E12"
          ],
          "revenue": 40,
          "revenue_str": "E14-E12"
        },
        {
          "train": "2a-1",
          "connections": [
            [
              "E16",
              "E14"
            ]
          ],
          "hexes": [
            "E14",
            "E16"
          ],
          "revenue": 30,
          "revenue_str": "E14-E16"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 77,
      "created_at": 1613383763,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 78,
      "created_at": 1613383767
    },
    {
      "type": "pass",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 79,
      "created_at": 1613383771
    },
    {
      "type": "buy_company",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 80,
      "created_at": 1613383786,
      "company": "S2",
      "price": 45
    },
    {
      "type": "lay_tile",
      "entity": "S2",
      "entity_type": "company",
      "id": 81,
      "created_at": 1613383797,
      "hex": "H11",
      "tile": "7-0",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 82,
      "created_at": 1613383810,
      "routes": [
        {
          "train": "2a-2",
          "connections": [
            [
              "I10",
              "H11",
              "I12"
            ]
          ],
          "hexes": [
            "I12",
            "I10"
          ],
          "revenue": 50,
          "revenue_str": "I12-I10"
        },
        {
          "train": "2a-3",
          "connections": [
            [
              "I10",
              "I12"
            ]
          ],
          "hexes": [
            "I12",
            "I10"
          ],
          "revenue": 50,
          "revenue_str": "I12-I10"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 83,
      "created_at": 1613383815,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 84,
      "created_at": 1613383820
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 85,
      "created_at": 1613383823
    },
    {
      "type": "lay_tile",
      "entity": "EKJ",
      "entity_type": "corporation",
      "id": 86,
      "created_at": 1613383839,
      "hex": "D5",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "EKJ",
      "entity_type": "corporation",
      "id": 87,
      "created_at": 1613383843,
      "hex": "D7",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "EKJ",
      "entity_type": "corporation",
      "id": 88,
      "created_at": 1613383849,
      "train": "3c-0",
      "price": 120,
      "variant": "3c"
    },
    {
      "type": "pass",
      "entity": "EKJ",
      "entity_type": "corporation",
      "id": 89,
      "created_at": 1613383863
    },
    {
      "type": "pass",
      "entity": "EKJ",
      "entity_type": "corporation",
      "id": 90,
      "created_at": 1613383873
    },
    {
      "type": "lay_tile",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 91,
      "created_at": 1613383881,
      "hex": "B25",
      "tile": "7-1",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 92,
      "created_at": 1613383883
    },
    {
      "type": "run_routes",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 93,
      "created_at": 1613383890,
      "routes": [
        {
          "train": "2a-4",
          "connections": [
            [
              "C26",
              "C24"
            ]
          ],
          "hexes": [
            "C24",
            "C26"
          ],
          "revenue": 50,
          "revenue_str": "C24-C26"
        },
        {
          "train": "2b-0",
          "connections": [
            [
              "C24",
              "B25",
              "C26"
            ]
          ],
          "hexes": [
            "C26",
            "C24"
          ],
          "revenue": 50,
          "revenue_str": "C26-C24"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 94,
      "created_at": 1613383899,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 95,
      "created_at": 1613383940
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 96,
      "created_at": 1613383943
    },
    {
      "type": "lay_tile",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 97,
      "created_at": 1613383956,
      "hex": "E22",
      "tile": "6-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 98,
      "created_at": 1613383961
    },
    {
      "type": "run_routes",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 99,
      "created_at": 1613383998,
      "routes": [
        {
          "train": "2b-1",
          "connections": [
            [
              "F23",
              "E22"
            ]
          ],
          "hexes": [
            "E22",
            "F23"
          ],
          "revenue": 40,
          "revenue_str": "E22-F23"
        },
        {
          "train": "2b-2",
          "connections": [
            [
              "F23",
              "G24"
            ]
          ],
          "hexes": [
            "G24",
            "F23"
          ],
          "revenue": 40,
          "revenue_str": "G24-F23"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 100,
      "created_at": 1613384001,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 101,
      "created_at": 1613384005
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 102,
      "created_at": 1613384006
    },
    {
      "type": "buy_shares",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 103,
      "created_at": 1613384087,
      "shares": [
        "VBW_1"
      ],
      "percent": 25
    },
    {
      "type": "buy_shares",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 104,
      "created_at": 1613384134,
      "shares": [
        "VBW_2"
      ],
      "percent": 25
    },
    {
      "type": "sell_shares",
      "entity": "Fred",
      "entity_type": "player",
      "id": 105,
      "created_at": 1613384143,
      "shares": [
        "OFE_2"
      ],
      "percent": 25
    },
    {
      "type": "par",
      "entity": "Fred",
      "entity_type": "player",
      "id": 106,
      "created_at": 1613384201,
      "corporation": "NWB",
      "share_price": "70,0,10"
    },
    {
      "type": "sell_shares",
      "entity": "Velma",
      "entity_type": "player",
      "id": 107,
      "created_at": 1613384266,
      "shares": [
        "OFE_1"
      ],
      "percent": 25
    },
    {
      "type": "par",
      "entity": "Velma",
      "entity_type": "player",
      "id": 108,
      "created_at": 1613384275,
      "corporation": "KFN",
      "share_price": "60,0,6"
    },
    {
      "type": "pass",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 109,
      "created_at": 1613384281
    },
    {
      "type": "buy_shares",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 110,
      "created_at": 1613384315,
      "shares": [
        "EKJ_1"
      ],
      "percent": 25
    },
    {
      "type": "buy_shares",
      "entity": "Fred",
      "entity_type": "player",
      "id": 111,
      "created_at": 1613384326,
      "shares": [
        "NWB_1"
      ],
      "percent": 20
    },
    {
      "type": "buy_shares",
      "entity": "Velma",
      "entity_type": "player",
      "id": 112,
      "created_at": 1613384340,
      "shares": [
        "KFN_1"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "Shaggy",
      "entity_type": "player",
      "id": 113,
      "created_at": 1613384376
    },
    {
      "type": "pass",
      "entity": "Daphne",
      "entity_type": "player",
      "id": 114,
      "created_at": 1613384379
    },
    {
      "type": "pass",
      "entity": "Fred",
      "entity_type": "player",
      "id": 115,
      "created_at": 1613384379
    },
    {
      "type": "pass",
      "entity": "Velma",
      "entity_type": "player",
      "id": 116,
      "created_at": 1613384380
    },
    {
      "type": "lay_tile",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 117,
      "created_at": 1613384393,
      "hex": "F13",
      "tile": "58-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 118,
      "created_at": 1613384399,
      "hex": "G12",
      "tile": "57-2",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 119,
      "created_at": 1613384412
    },
    {
      "type": "pass",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 120,
      "created_at": 1613384425
    },
    {
      "type": "buy_train",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 121,
      "created_at": 1613384433,
      "train": "3c-2",
      "price": 120,
      "variant": "3c"
    },
    {
      "type": "buy_train",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 122,
      "created_at": 1613384443,
      "train": "3c-3",
      "price": 80,
      "variant": "2+2c"
    },
    {
      "type": "pass",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 123,
      "created_at": 1613384470
    },
    {
      "type": "pass",
      "entity": "NWB",
      "entity_type": "corporation",
      "id": 124,
      "created_at": 1613384475
    },
    {
      "type": "lay_tile",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 125,
      "created_at": 1613384486,
      "hex": "G20",
      "tile": "621-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 126,
      "created_at": 1613384493,
      "hex": "G22",
      "tile": "4-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 127,
      "created_at": 1613384502
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 128,
      "created_at": 1613384545
    },
    {
      "type": "buy_train",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 129,
      "created_at": 1613384555,
      "train": "3d-0",
      "price": 180,
      "variant": "3+3d"
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 130,
      "created_at": 1613385161
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 131,
      "created_at": 1613385163
    },
    {
      "type": "lay_tile",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 132,
      "created_at": 1613385320,
      "hex": "I12",
      "tile": "208-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 133,
      "created_at": 1613385325
    },
    {
      "type": "run_routes",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 134,
      "created_at": 1613385349,
      "routes": [
        {
          "train": "2a-2",
          "connections": [
            [
              "I10",
              "H11",
              "I12"
            ]
          ],
          "hexes": [
            "I10",
            "I12"
          ],
          "revenue": 60,
          "revenue_str": "I10-I12"
        },
        {
          "train": "2a-3",
          "connections": [
            [
              "I10",
              "I12"
            ]
          ],
          "hexes": [
            "I10",
            "I12"
          ],
          "revenue": 60,
          "revenue_str": "I10-I12"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 135,
      "created_at": 1613385357,
      "kind": "payout"
    },
    {
      "type": "sell_company",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 136,
      "created_at": 1613385419,
      "company": "S2",
      "price": 50
    },
    {
      "type": "buy_train",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 137,
      "created_at": 1613385430,
      "train": "3c-2",
      "price": 90
    },
    {
      "type": "buy_company",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 138,
      "created_at": 1613385451,
      "company": "S1",
      "price": 20
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 139,
      "created_at": 1613385485
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 140,
      "created_at": 1613385493,
      "hex": "E12",
      "tile": "8891-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 141,
      "created_at": 1613385502,
      "routes": [
        {
          "train": "2a-0",
          "connections": [
            [
              "E12",
              "E14"
            ]
          ],
          "hexes": [
            "E12",
            "E14"
          ],
          "revenue": 50,
          "revenue_str": "E12-E14"
        },
        {
          "train": "2a-1",
          "connections": [
            [
              "E16",
              "E14"
            ]
          ],
          "hexes": [
            "E16",
            "E14"
          ],
          "revenue": 30,
          "revenue_str": "E16-E14"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 142,
      "created_at": 1613385505,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 143,
      "created_at": 1613385531
    },
    {
      "type": "pass",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 144,
      "created_at": 1613385534
    },
    {
      "type": "lay_tile",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 145,
      "created_at": 1613385543,
      "hex": "F23",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 146,
      "created_at": 1613385552
    },
    {
      "type": "run_routes",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 147,
      "created_at": 1613385556,
      "routes": [
        {
          "train": "2b-1",
          "connections": [
            [
              "F23",
              "E22"
            ]
          ],
          "hexes": [
            "F23",
            "E22"
          ],
          "revenue": 50,
          "revenue_str": "F23-E22"
        },
        {
          "train": "2b-2",
          "connections": [
            [
              "F23",
              "G24"
            ]
          ],
          "hexes": [
            "F23",
            "G24"
          ],
          "revenue": 50,
          "revenue_str": "F23-G24"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 148,
      "created_at": 1613385560,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 149,
      "created_at": 1613385599
    },
    {
      "type": "pass",
      "entity": "MW",
      "entity_type": "corporation",
      "id": 150,
      "created_at": 1613385601
    },
    {
      "type": "lay_tile",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 151,
      "created_at": 1613385610,
      "hex": "C26",
      "tile": "207-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 152,
      "created_at": 1613385612
    },
    {
      "type": "run_routes",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 153,
      "created_at": 1613385614,
      "routes": [
        {
          "train": "2a-4",
          "connections": [
            [
              "C26",
              "C24"
            ]
          ],
          "hexes": [
            "C26",
            "C24"
          ],
          "revenue": 60,
          "revenue_str": "C26-C24"
        },
        {
          "train": "2b-0",
          "connections": [
            [
              "C24",
              "B25",
              "C26"
            ]
          ],
          "hexes": [
            "C24",
            "C26"
          ],
          "revenue": 60,
          "revenue_str": "C24-C26"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "S3",
      "entity_type": "company",
      "id": 154,
      "created_at": 1613385637,
      "hex": "C24",
      "tile": "14p-0",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 155,
      "created_at": 1613385658
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 156,
      "created_at": 1613385668
    },
    {
      "type": "lay_tile",
      "entity": "S3",
      "entity_type": "company",
      "id": 157,
      "created_at": 1613385922,
      "hex": "C24",
      "tile": "14p-0",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 158,
      "created_at": 1613385933
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 159,
      "created_at": 1613385941
    },
    {
      "type": "lay_tile",
      "entity": "S3",
      "entity_type": "company",
      "id": 160,
      "created_at": 1613385969,
      "hex": "C24",
      "tile": "14p-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 161,
      "created_at": 1613385977
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 162,
      "created_at": 1613385990
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 163,
      "created_at": 1613386077
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 164,
      "created_at": 1613386083
    },
    {
      "type": "lay_tile",
      "entity": "S3",
      "entity_type": "company",
      "id": 165,
      "created_at": 1613386094,
      "hex": "C24",
      "tile": "14p-0",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 166,
      "created_at": 1613386106
    },
    {
      "type": "lay_tile",
      "entity": "S3",
      "entity_type": "company",
      "id": 167,
      "created_at": 1613386117,
      "hex": "C24",
      "tile": "15p-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 168,
      "created_at": 1613386127,
      "hex": "C26",
      "tile": "207-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 169,
      "created_at": 1613386134
    },
    {
      "type": "undo",
      "entity": "OFE",
      "entity_type": "corporation",
      "id": 170,
      "created_at": 1613386579,
      "action_id": 140
    },
    {
      "type": "buy_company",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 171,
      "created_at": 1613386585,
      "company": "S1",
      "price": 20
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 172,
      "created_at": 1613386653
    },
    {
      "type": "undo",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 173,
      "created_at": 1613386785,
      "action_id": 125
    },
    {
      "type": "lay_tile",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 174,
      "created_at": 1613386794,
      "hex": "G22",
      "tile": "4-0",
      "rotation": 1
    },
    {
      "type": "buy_company",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 175,
      "created_at": 1613386798,
      "company": "M4",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 176,
      "created_at": 1613387947
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 177,
      "created_at": 1613387954
    },
    {
      "type": "buy_train",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 178,
      "created_at": 1613387957,
      "train": "3d-0",
      "price": 180,
      "variant": "3+3d"
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 179,
      "created_at": 1613387962
    },
    {
      "type": "pass",
      "entity": "KFN",
      "entity_type": "corporation",
      "id": 180,
      "created_at": 1613387964
    },
    {
      "type": "sell_company",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 181,
      "created_at": 1613387994,
      "company": "S2",
      "price": 50
    },
    {
      "type": "lay_tile",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 182,
      "created_at": 1613388001,
      "hex": "I12",
      "tile": "208-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 183,
      "created_at": 1613388008
    },
    {
      "type": "buy_company",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 184,
      "created_at": 1613388019,
      "company": "S4",
      "price": 50
    },
    {
      "type": "lay_tile",
      "entity": "S4",
      "entity_type": "company",
      "id": 185,
      "created_at": 1613388035,
      "hex": "I10",
      "tile": "15p-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 186,
      "created_at": 1613388039,
      "routes": [
        {
          "train": "2a-2",
          "connections": [
            [
              "I10",
              "H11",
              "I12"
            ]
          ],
          "hexes": [
            "I10",
            "I12"
          ],
          "revenue": 70,
          "revenue_str": "I10-I12"
        },
        {
          "train": "2a-3",
          "connections": [
            [
              "I10",
              "I12"
            ]
          ],
          "hexes": [
            "I10",
            "I12"
          ],
          "revenue": 70,
          "revenue_str": "I10-I12"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 187,
      "created_at": 1613388062,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 188,
      "created_at": 1613388071
    },
    {
      "type": "pass",
      "entity": "VBW",
      "entity_type": "corporation",
      "id": 189,
      "created_at": 1613388072
    },
    {
      "type": "lay_tile",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 190,
      "created_at": 1613388084,
      "hex": "F15",
      "tile": "7-2",
      "rotation": 2
    },
    {
      "type": "buy_company",
      "entity": "BCB",
      "entity_type": "corporation",
      "id": 191,
      "created_at": 1613388090,
      "company": "S1",
      "price": 20
    }
  ],
  "id": "hs_lzpolckw_1613382019",
  "players": [
    {
      "name": "Daphne"
    },
    {
      "name": "Fred"
    },
    {
      "name": "Shaggy"
    },
    {
      "name": "Velma"
    }
  ],
  "title": "18CZ",
  "description": "",
  "max_players": "4",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-02-15",
  "loaded": true,
  "result": {},
  "turn": 3,
  "round": "Operating Round",
  "acting": [
    "Daphne"
  ],
  "updated_at": 1613388090
}

### PR DESCRIPTION
**Pull request by benjaminxscott**
fixes #3874, resolves #3882

### CODE REVIEW

**Comment by benjaminxscott** [comment]
fixes #3882

File: lib/engine/game/g_18_cz.rb [hunk 1]
```diff
@@ -329,6 +329,7 @@ def place_home_token(corporation)
 
       def upgrades_to?(from, to, special = false)
         return true if from.color == :white && to.color == :red
+        return true if purple_tile?(to) && from.towns.size == 2 && to.towns.any? && to.color == :green
```
Comment (jenf) [inline lib/engine/game/g_18_cz.rb:332]: !to.towns.empty?

Comment (benjaminxscott) [reply lib/engine/game/g_18_cz.rb]: gotcha, is it easier to read or like a style thing?

Comment (tobymao) [reply lib/engine/game/g_18_cz.rb]: performance

Comment (jenf) [reply lib/engine/game/g_18_cz.rb]: Any will go through the elements to see if anything is not nil. Empty just sees if the container is empty
