### PR TITLE
zigzag stock market: fix box_height

### LINKED ISSUE #4321: [zigzag markets] When more than 3 medium tokens are on the same market price in the top row, the 4th token is obscured by the bottom row
https://18xx.games/game/28521?action=416#market

For example:
Screen Shot 2021-03-04 at 11 12 13 PM

### PR DESCRIPTION
**Pull request by yzemaze**
fixes #4321

### CODE REVIEW

File: assets/app/view/game/stock_market.rb [hunk 1]
```diff
@@ -72,6 +72,13 @@ def box_style_1d
         }
       end
 
+      def box_height_1d
+        token_height = @game.stock_market.market.first.map do |p|
+          p.corporations.sum { |c| TOKEN_SIZES[@game.corporation_size(c)] + VERTICAL_TOKEN_PAD }
+        end.push(MIN_NUM_TOKENS * (TOKEN_SIZE + VERTICAL_TOKEN_PAD)).max
```
Comment (tobymao) [inline assets/app/view/game/stock_market.rb:78]: i don't like this style and don't use push

maybe something like
 (map { p.sum } + [constan]).max

Comment (yzemaze) [reply assets/app/view/game/stock_market.rb:78]: just copy & pasted, will check later
