### PR TITLE
Fix river partitions rendering on map URL

### LINKED ISSUE #7387: river partitions don't render on the /map URL
The river partition in 1870 doesn't render on the map at https://18xx.games/map/1870 but it does render in game.

### PR DESCRIPTION
**Pull request by andrewzwicky**
Fixes #7387

1. Tile in RHL had two of the same label on it.

image -----> image

2. In the map view, `@game` is nil, so CitySlot needs to handle a nil game (18Rhl map view was previously throwing an undefined method error)

image

3. In the map view, `@game` is nil, so partitions should render if that's the case, so they appear on the map view.
image

### CODE REVIEW

File: assets/app/view/game/part/partitions.rb [hunk 1]
```diff
@@ -54,7 +54,7 @@ def render_part
 
           @tile.partitions.each do |partition|
             next if partition.type != :divider && partition.blockers.none? do |blocker|
-              @game&.abilities(blocker, :blocks_partition)&.blocks?(partition.type)
+              @game.nil? || @game&.abilities(blocker, :blocks_partition)&.blocks?(partition.type)
```
Comment (tobymao) [inline assets/app/view/game/part/partitions.rb:57]: !@game
