### PR TITLE
18Mag: K-tile bug fix; end-game bug fix

### LINKED ISSUE #3462: [18Mag] Unable to place #6 tile on Kolozsvar (F23)
**What's your Game ID?**

https://18xx.games/game/23603
(pinned to version e9ae9a4e)

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

I clicked on Kolozsvar (F23) during minor company #5's track-laying turn.
I expected to be able to place a #5, #6, or #57 tile (all are available), but only the #5 and #57 appear as options.

Please include screenshots (you can drag and drop or upload them into this issue)

Screenshot 2021-01-22 141641

**Which Browser / Platform?**
Google Chrome 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)
Desktop

### LINKED ISSUE #3482: 18Mag: end-game bug from Lonny
The phase change at the game end wasn't right.

### PR DESCRIPTION
**Pull request by roseundy**
- Clearing 'K' label on outgoing yellow tile required new method in Engine::Tile
- Fixed error introduced with new end-game rule where triggering OR wasn't followed by an SR correctly

Common file changes: Engine::Tile add clear_label! method

Fixes #3462 
Fixes #3482 

This is likely to require pins.

### CODE REVIEW

File: lib/engine/tile.rb [hunk 1]
```diff
@@ -456,6 +456,10 @@ def label=(label_name)
       @label = Part::Label.new(label_name)
     end
 
+    def clear_label!
```
Comment (tobymao) [inline lib/engine/tile.rb:459]: remove this, and change the setter to handle nil

Comment (roseundy) [reply lib/engine/tile.rb:459]: Gotcha!

**Review by tobymao — APPROVED** [review]
