### PR TITLE
Fix phases init in 1822 scenarios

### LINKED ISSUE #9914: [1822NRS] Game inaccessible by link
**What's your Game ID?**

https://18xx.games/game/141822

**How to Reproduce the Bug?**

Create a **1822NRS** game and start it. The game is then accessible from main page, but shows error when opened directly by the link:
```
{"error":"Scenario: uninitialized constant Engine::Game::G1822::Scenario"}
```

**Which Browser / Platform?**

Anywhere

### PR DESCRIPTION
**Pull request by vandamm**
Fixes #9914 

### Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### CODE REVIEW

File: lib/engine/game/g_1822_nrs/game.rb [hunk 1]
```diff
@@ -12,6 +12,7 @@ class Game < G1822::Game
         include_meta(G1822NRS::Meta)
         include Entities
         include Map
+        include G1822::Scenario
```
Comment (michaeljb) [inline lib/engine/game/g_1822_nrs/game.rb:15]: I notice this file doesn't have `require_relative '../g_1822/scenario'` like the others do, does it still resolve the issue without adding it?

Comment (michaeljb) [reply lib/engine/game/g_1822_nrs/game.rb:15]: Just tested locally, without the require line I still get the error, but with it the error is gone.

Comment (michaeljb) [reply lib/engine/game/g_1822_nrs/game.rb:15]: Will merge and push this line separately.
