### PR TITLE
[1824] Fix capitalization for unsold, fixes #12324

### LINKED ISSUE #12024: [1824] Missing unit tests
There should be unit tests added to verify that some things work, and some things are not allowed.

E.g. there should be a unit test that shows that optional MR exchange is possible.

Preferably there should be unit tests that verify fixed Issues.

I put this as an issue to remind myself.

### LINKED ISSUE #12290: [1824] No fixture files
PR #12080 breaks all the existing fixture files for 1824, and all the completed games in the database (other than ones that were manually ended).

To allow that pull request to be merged, 1824 is being added to the `SKIP_ALPHA` set in `fixtures_required_spec.rb`. This should be reverted as soon as possible, once there are new completed games that can be added to the fixtures.

### LINKED ISSUE #12324: [1824] Incorrect staatsbahn capitalization when unsold pre-staatsbahn
This was discovered when I added a unit test.

UG1 was unsold during SR1. When UG where to be formed UG gets 5 times share price, instead of the expected 9 times.

**What's your Game ID?**

235932, but game has not reached formation of UG yet.

**How to Reproduce the Bug?**

1. Pre-staatsbahn unsold during SR1.
2. Form connected staatsbahn.
3. Check capitalization.

**Which Browser / Platform?**
N/A

### PR DESCRIPTION
**Pull request by perwestling**
Fixes a bug when adjusting capitalization count for unsold during SR1.

Also adds a fixture for 1824, which is an ongoing game which I have cloned and ended prematurely.
This fixes #12290

Adds some unit tests for 1824. More will be added in the future. This fixes #12024

Fixes #12324
Fixes #12290 
Fixes #12024

## Before clicking "Create"

- [X] Branch is derived from the latest `master`
- [X] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [X] Code passes linter with `docker compose exec rack rubocop -a`
- [X] Tests pass cleanly with `docker compose exec rack rake`

There was a bug in which SD, KK, UG could get too low capitalization, in case any pre-staatsbahn of theirs was unsold during SR1. These games might now be broken - in case change of money do change possible actions.
So in case any game breaks, pin or archive it - 1824 is still in Alpha.

## Implementation Notes
The added fixture is a not yet completed game of 1824 which will have an UG formation with shortness of money, as the game continues. I have taken that and made a manual end, and is using that fixture to do some unit tests. I cannot fully test the capitalization for UG with this fixture as game has not reach that yet but is testing the internal state prior to this.

I might change fixture, possibly with the completed game, in the future.

Also added some test cases for first to operate in SR1, priority deal, SD formation. More might be added in the future.

### Explanation of Change
Found an error in the code when adding a unit test. This has now been corrected. No other code changes.

### Screenshots
N/A

### Any Assumptions / Hacks
N/A

### CODE REVIEW

File: spec/lib/engine/game/1824/game_spec.rb [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+      expect(get_token_owners_in_hex(game, innsbruck)).to eq([['SD3', nil]])
+
+      # Check trains before formation
+      [sd1, sd2, sd3].each { |corp| expect(corp.trains.map(&:name)).to eq(%w[3]) }
+      expect(sd.trains).to be_empty
+
+      game = fixture_at_action(281) # OR 5.2 started, SD formed at end of OR 5.1
+
+      # Check cash and status after formation
+      expect(sd.cash).to eq(720 + 47 + 0 + 15)
```
Comment (perwestling) [inline spec/lib/engine/game/1824/game_spec.rb]: Could write (6*120) instead of 720 to make it clearer that this is based on capitalization. Or use a local variable for this?

File: spec/lib/engine/game/1824/game_spec.rb [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+    it 'SD formation' do
+      game = fixture_at_action(280) # Before last action in OR 5.1
+
+      sd = game.corporation_by_id('SD')
+      sd1 = game.corporation_by_id('SD1')
+      sd2 = game.corporation_by_id('SD2')
+      sd3 = game.corporation_by_id('SD3')
+
+      expect(sd.floated?).to be false
+      expect(sd1.closed?).to be false
```
Comment (perwestling) [inline spec/lib/engine/game/1824/game_spec.rb]: do an SDx-each loop here and on line 96-98.

**Review by ollybh — APPROVED** [review]

**Comment by perwestling** [comment]
@ollybh I added a completed 1824 game (completed 2025-12-30) so that 1824 now complies with the alpha game requirement. Have also removed 1824 from SKIP_ALPHA to fix #12290.

**Comment by perwestling** [comment]
Added two more unit test cases, for UG and KK formation as well.
