### PR TITLE
[1850] fix mesabi token buying when not connected

### LINKED ISSUE #8877: [1850] Buying Mesabi Tokens
https://18xx.games/game/114095
In game ID 114095 the RI was able to buy a Mesabi token when there was no connection.

### PR DESCRIPTION
**Pull request by bentziaxl**
fix #8877 8877

### CODE REVIEW

File: lib/engine/game/g_1850/step/track.rb [hunk 1]
```diff
@@ -69,12 +69,20 @@ def buy_mesabi_token(corporation)
             corporation.mesabi_token = true
           end
 
+          def hex_neighbors(entity, hex)
+            connected = super
+            @game.clear_token_graph_for_entity(entity)
+            connected
```
Comment (bentziaxl) [inline lib/engine/game/g_1850/step/track.rb:75]: I had to add graph clearing as i ran into an issue:
The hex neighbors check caches the graph when it runs, however it seem to happen prior to a corporation placing its home token when floating, resulting in the corp not being able to lay a tile.
This seems like a bad idea, as it will mean often refreshes of the graph, and bad performance.
Is there a better place to clear the graph? maybe right after home token placement?
