### PR TITLE
[1822 family] force train discard at start of OR if SR export changes train limit

### LINKED ISSUE #11544: [1822 family] train discard due to phase change at end of SR after start of 1st companies OR
In this game, a phase change got triggered from 4 to 5 because the leftmost minor did not get bought during the last SR. This triggered one of the majors to have to discard one of their 3 trains. this should have happened immediately upon start of the SR. Instead, first a minor's "Acquire private companies" step triggered, and the discard step only triggered after that.

**What's your Game ID?**
https://18xx.games/game/194049?action=1018

**How to Reproduce the Bug?**
Hit "skip" here for 17 and then the game moves into the discard step for CMPS.

**Which Browser / Platform?**

- Browser: Firefox 135.0 
- Platform: Desktop

### PR DESCRIPTION
**Pull request by michaeljb**
* Rename 1822 fixture `36685` to `discard_trains_after_sr_export` to specifically note this feature being tested by it; at action 583, phase 5 starts due to a train export at the end of the stock round, and two companies are forced to discard trains right away. As originally played out, first Minor 8 did its acquire company steps.

    * some of the other fixtures needed migrating because the active major just acquired a private company with a train, forcing the major to discard before passing out of the acquisition step

Fixes #11544

----

Locally this was found to break 504/1876 (~27%) of games in the 1822 family. Since the other outstanding 1822PNW need pins, it might be best to wait for those PRs to be deployed and games pinned before merging and migrating this one (or vice versa).

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### CODE REVIEW

File: scripts/migrate_1822_discard_trains.rb [hunk 1]
```diff
@@ -0,0 +1,408 @@
...
+      require 'pry-byebug'
+      binding.pry
+
+      raise Exception, 'Could not find discard_train_action'
+    end
+
+    actions.delete(discard_train_action)
+    actions.insert(broken_action_idx, discard_train_action)
+    return
+  end
```
Comment (michaeljb) [inline scripts/migrate_1822_discard_trains.rb:115]: This script is a copy of `migrate_game.rb` except for this section

**Comment by michaeljb** [comment]
Migration succeeded locally for these games:

`[183524, 183621, 183642, 183667, 183702, 183873, 184173, 184408, 184602, 184760, 185028, 185143, 185164, 185244, 185265, 185323, 185377, 185649, 186021, 186068, 186143, 186554, 186566, 186575, 186633, 186736, 186831, 186852, 186929, 187017, 187101, 187178, 187394, 187481, 187545, 187631, 187910, 187922, 188275, 188457, 188631, 188721, 189007, 189044, 189426, 189441, 189618, 189814, 189879, 189943, 190049, 190245, 190254, 190423, 190582, 190798, 190906, 190989, 191022, 191149, 191292, 191483, 191508, 191509, 191513, 191515, 191560, 191633, 191815, 191833, 191854, 192018, 192051, 192125, 192270, 192280, 192415, 192597, 192664, 192681, 192834, 192886, 192900, 193064, 193140, 193166, 193189, 193257, 193269, 193384, 193387, 193491, 193594, 193619, 193676, 193723, 193778, 193857, 194024, 194181, 194346, 194427, 194452, 194486, 194516, 194549, 194735, 194793, 194826, 194839, 194925, 195473, 195479, 195484, 195515, 195641, 195720, 195750, 195794, 195858, 196017, 196159, 196213, 196271, 196323, 196398, 196515, 196573, 196599, 196601, 196602, 196609, 196610, 196690, 196753, 196764, 196900, 197076, 197106, 197157, 197292, 197440, 197483, 197627, 197632, 197788, 197803, 198285, 198468, 198499, 198626, 198636, 198666, 198791, 198794, 199007, 199022, 199102, 199328, 199363, 199407, 199415, 199505, 199515, 199516, 199567, 199651, 199725, 199815, 199845, 199987, 200227, 200296, 200433, 200459, 200667, 200713, 200737, 200821, 200866, 200884, 200885, 200953, 200996, 201035, 201051, 201090, 201091, 201201, 201245, 201296, 201305, 201440, 201463, 201479, 201635, 201751, 201823, 201842, 201899, 201906, 201912, 201956, 202007, 202025, 202095, 202210, 202231, 202240, 202242, 202304, 202309, 202417, 202434, 202668, 202678, 202680, 202684, 202752, 202779, 202783, 202895, 202907, 202916, 202938, 202942, 202955, 203054, 203234, 203267, 203284, 203303, 203467, 203519, 203570, 203703, 203714, 203954, 204001, 204107, 204263, 204274, 204510, 204552, 204595, 204681, 204761, 204780, 204788, 204841, 204843, 204961, 204976, 204985, 205044, 205081, 205082, 205119, 205248, 205350, 205562, 205574, 205586, 205601, 205665, 205732, 205741, 205790, 205803, 205809, 205883, 205916, 205919, 206107, 206135, 206152, 206270, 206276, 206277, 206334, 206374, 206442, 206534, 206613, 206621, 206741, 206837, 207017, 207056, 207070, 207143, 207155, 207246, 207364, 207393, 207465, 207571, 207621, 207748, 207802, 207895, 207939, 208112, 208191, 208221, 208273, 208419, 208493, 208563, 208599, 208665, 208792, 208805, 208821, 208848, 208854, 208855, 208965, 208971, 209015, 209079, 209081, 209206, 209280, 209336, 209524, 209635, 209696, 209785, 209949, 209991, 210324, 210616, 210706, 210737, 210810, 211023, 211115, 211217, 211220, 211311, 211336, 211369, 211379, 211432, 211498, 211682, 211696, 211709, 211729, 211832, 211942, 212078, 212260, 212448, 212553, 212720, 212844, 213032, 213068, 213191, 213222, 213258, 213309, 213677, 213848, 214079, 214124, 214148, 214193, 214256, 214319, 214346, 214374, 214492, 214511, 214530, 214554, 214606, 214682, 214718, 214800, 214856, 214878, 214983, 214984, 215001, 215210, 215423, 215444, 215456, 215468, 215480, 215735, 215736, 215825, 215981, 216238, 216320, 216331, 216332, 216364, 216490, 216696, 216710, 216858, 216986, 217007, 217126, 217221, 217281, 217293, 217379, 217403, 217455, 217464, 217482, 217490, 217499, 217686, 217715, 217793, 217857, 217981, 217999, 218095, 218131, 218235, 218244, 218254, 218287, 218298, 218323, 218489, 218558, 218762, 218843, 218879, 219190, 219337, 219734, 219782, 219838, 219872, 219951, 219977, 220146, 220185, 220227, 220315, 220362, 220607, 220626, 220679, 220691, 220737, 220908, 221025, 221082, 221155, 221183, 221370, 221424, 221940, 222055, 222117, 222134, 222137, 222257, 222294, 222412, 222487, 222622, 222930, 222931, 222986, 223021, 223501, 223595, 223783, 223809, 223961, 224086, 224270, 224537, 224579, 224741, 224954, 225130, 225262, 225278, 225408, 225481, 225497, 225777, 225891, 225906, 225942, 226481, 226804, 227059, 227459, 227963]`

Failed for : `[225533]`

**Comment by michaeljb** [comment]
> Failed for: `[225533]`

The migration actually succeeds for this game, it only failed my follow up validation with `strict: true` due to #12155
