### PR TITLE
18TN: Fix "company buy during OR1" bug (fixes #1887)

### LINKED ISSUE #1887: 18TN: Incorrect handling of OR1 buy-in of privates
In the first operating round, each company is supposed to be allowed to buy in one private. The bug is that after the first company in the round buys in a private, the remaining companies are not given the option to buy-in a private (the privates do not display at the bottom of the screen).

I created an example hot-seat game. In example, the L&N went first and bought in a private. Now the IC goes, but it is not shown the privates so it cannot buy one in. If you continue the IC turn, at the end it does say "IC skips buy companies", so the problem seems to be that it just doesn't show the privates.

Here is the example hot-seat game:
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "LNR",
      "price": 180
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "TCC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "ETWCR",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 4,
      "company": "MCR",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 5,
      "company": "OWR",
      "price": 100
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "corporation": "L&N",
      "share_price": "90,1,4"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 7,
      "corporation": "IC",
      "share_price": "70,2,3"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 8,
      "corporation": "SR",
      "share_price": "65,3,3"
    },
    {
      "type": "par",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 9,
      "corporation": "TC",
      "share_price": "65,3,3"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "L&N_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "IC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "SR_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "TC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "IC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "IC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "SR_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 17,
      "shares": [
        "TC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "IC_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "SR_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "TC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 21,
      "shares": [
        "SR_4"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 22,
      "hex": "B15",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 23,
      "hex": "E10",
      "tile": "58-0",
      "rotation": 3
    },
    {
      "type": "buy_company",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 24,
      "company": "OWR",
      "price": 100
    },
    {
      "type": "buy_train",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 25,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    }
  ],
  "id": "hs_nikuchsx_1602812559",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    },
    {
      "name": "Player 4"
    }
  ],
  "title": "18TN",
  "description": "Private Buy-in Bug",
  "max_players": "4",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-15",
  "loaded": true,
  "result": {}
}

### PR DESCRIPTION
**Pull request by perwestling**
Buy remembering all buys during a round, it is possible to do
a correct check for private buys during OR 1.

Reuse the company_seller round attribute, but change it to a
list instead of a nil/player attribute. This ment refactoring
its use in 1889 a bit. Renamed it to company_sellers to reflect
its changed use.
I do believe it can just contain one value in 1889 so the effect
should be the same.

### CODE REVIEW

File: lib/engine/step/g_1889/special_track.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def blocking?
         def process_lay_tile(action)
           return super unless action.entity == @company
 
-          lay_tile(action, spender: @round.company_seller)
+          lay_tile(action, spender: @round.company_sellers.any? ? @round.company_sellers.first : nil)
```
Comment (michaeljb) [inline lib/engine/step/g_1889/special_track.rb:22]:
```suggestion
          lay_tile(action, spender: @round.company_sellers.first)
```

`[].first` is `nil`, so this code should have the same effect

File: lib/engine/step/g_18_tn/buy_company.rb [hunk 2]
```diff
@@ -20,6 +20,18 @@ def can_buy_company?(entity)
...
+        private
+
+        def already_bought_in_turn_one?(entity)
+          return false if @game.turn != 1 || !entity.corporation?
+
+          # A corporation may buy at most one company during turn 1
+          return true if entity.companies.any?
+
+          # A player may sell at most one company during turn 1
+          @round.company_sellers.include?(entity.owner)
```
Comment (michaeljb) [inline lib/engine/step/g_18_tn/buy_company.rb:33]: Is a corporation allowed to buy a company from a player other than the corporation's president? I'll test this real quick, but I think this line would break that. (though I'm sure even if allowed, this would be a rare case...)

Comment (michaeljb) [reply lib/engine/step/g_18_tn/buy_company.rb:33]: Confirmed: michaeljb3 is president of L&N, which buys Memphis & Charleston from michaeljb2. Then michaeljb2 is president of SR, which does not have the option to buy a company from anyone, though it should be able to buy from a player other than michaeljb2.

https://gist.github.com/michaeljb/1e72c407aa61102a67f66f51e6486785

File: lib/engine/step/g_1889/special_track.rb (hunk 1 above)
Comment (perwestling) [reply lib/engine/step/g_1889/special_track.rb:22]: Fixed

File: lib/engine/step/g_18_tn/buy_company.rb (hunk 2 above)
Comment (michaeljb) [reply lib/engine/step/g_18_tn/buy_company.rb:33]: Another contrived example where Player 2 gets two presidencies in the first round, the first corporation buys a company from Player 2, and then the second corporation doesn't have the option to buy the private from any other players - https://gist.github.com/michaeljb/db071715e6c6d9fcfc364f7ad8721965

File: lib/engine/step/g_1889/special_track.rb (hunk 1 above)
Comment (michaeljb) [reply lib/engine/step/g_1889/special_track.rb]: `@round.company_sellers.any? ? @round.company_sellers.first` is a broken ternary (which broke the build) rather than just `@round.company_sellers.first`

File: lib/engine/step/g_18_tn/buy_company.rb (hunk 2 above)
Comment (perwestling) [reply lib/engine/step/g_18_tn/buy_company.rb]: Good catch.

In 18TN the following is allowed in first turn:
1. Players can buy from other players during SR1
2. Corporations can buy at most one private
3. Players can sell at most one private to a corporation

Have now improved the code so it will just stop buy of company if it is breaking the rules of OR1. So it should not affect SR1 or later ORs.

Comment (michaeljb) [reply lib/engine/step/g_18_tn/buy_company.rb]: With e10fd174 checked out, in both of the hotseat games I linked in my prior comments, SR is still unable to buy a company in OR1. L&N bought a company from the SR's president, but SR should still be allowed to buy from another player.

I think the logic for corporation buying one and player selling one need to be separated in order to handle this edge case correctly.

**Comment by perwestling** [comment]
I do not know if the tools handle the extra passes that is added by this correction?

Anyway, if any buy ins of privates breaking the rules this would require pin. But that should be rare.

File: lib/engine/step/g_18_tn/buy_company.rb (hunk 2 above)
Comment (perwestling) [reply lib/engine/step/g_18_tn/buy_company.rb]: @michaeljb Try again.
SR buy not available was a major bug in 18TN.

**Comment by tobymao** [comment]
is this ready to merge?

**Comment by perwestling** [comment]
Waiting for approval from @michaeljb

**Review by michaeljb — APPROVED** [review]

**Comment by michaeljb** [comment]
The 2 games I shared in gists here now show the expected behavior, but running `validate_all('18TN')` reports 62 broken out of 74 total games - https://gist.github.com/michaeljb/87456e0394ef80f3982e934ff711e992

**Comment by perwestling** [comment]
62 out of 74 was quite a lot. Does it cater for the extra passes needed during SR as the buy-private-during-SR was introduced?

@michaeljb Do you have a couple of game ids so I can investigate?

So, if it is OK breaks, should we pin the games?
