### PR TITLE
18TN: Use non-routed trains for Civil War resolution (fixes #1683)

### LINKED ISSUE #1683: 18TN: Inactive trains should take the effect of the Civil War
Consider the included hot seat game.
L&N has two 2 trains, and one 3 train.
Runs one 2 train for $80, runs one 2 train for $40 and does not run last train.
As it is Civil War one train should give no income.
As one train was passive that should be used for Civil War effect, but in the game the $40 revenue is removed.

{
  "status": "active",
  "actions": [
    {
      "type": "message",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 1,
      "message": "OK, here we go! Have Fun guys! I trust the developer can help out in case of any rules ambiguities ;)"
    },
    {
      "type": "bid",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 2,
      "company": "LNR",
      "price": 180
    },
    {
      "type": "message",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 3,
      "message": "ximega, are you in the 18xx slack? We're using a private conversation there to discuss this game, we can add you if you'd like"
    },
    {
      "type": "bid",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 4,
      "company": "ETWCR",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "xigema",
      "entity_type": "player",
      "id": 5,
      "company": "OWR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 6,
      "company": "LNR",
      "price": 185
    },
    {
      "id": 7,
      "type": "bid",
      "price": 190,
      "entity": "kdlecluy",
      "company": "LNR",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "undo",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "bid",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 10,
      "company": "TCC",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "bid",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 12,
      "company": "MCR",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 13,
      "company": "LNR",
      "price": 190
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "par",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 15,
      "corporation": "L&N",
      "share_price": "90,1,4"
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "par",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 17,
      "corporation": "SR",
      "share_price": "65,3,3"
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 20
    },
    {
      "id": 21,
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "type": "buy_shares",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 23,
      "shares": [
        "SR_1"
      ],
      "percent": 10
    },
    {
      "type": "message",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 24,
      "message": "SR will float this SR or next"
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 25,
      "message": "I will have enough to start my own next SR so buying in for me would result in a net loss"
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 28,
      "message": "@xigema we have been discussing a bit on the slack, but Per pointed out that it is not perhaps fair to discuss the game with not all present."
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 29,
      "message": "I was giving my thought process on why I'm not starting a company, perhaps I should, but I just doubted someone would buy in so I'd rather be close to priority."
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 30,
      "message": "kdlcecluy might not invest out of fear of having L&N taken away from him, Per is starting his own and needs the money. Xigema didn't buy in SR"
    },
    {
      "type": "buy_shares",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "SR_2"
      ],
      "percent": 10
    },
    {
      "type": "message",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 32,
      "message": "No fear! :)"
    },
    {
      "type": "message",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 33,
      "message": "Thanks"
    },
    {
      "type": "message",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 34,
      "message": "Auto order, I will buy SR until it floats"
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 35,
      "message": "Yeah, I will have 390$ in SR2 so I need to hold on to my money, or own the shares for an extra round"
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 36,
      "message": "My mistake is maybe I should have tries starting my own now"
    },
    {
      "type": "buy_shares",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 37,
      "shares": [
        "SR_3"
      ],
      "percent": 10
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 38,
      "message": "i think i can support u one share"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 39,
      "message": "u can start the company"
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "par",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 41,
      "corporation": "GMO",
      "share_price": "65,3,3"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 42,
      "message": "great"
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 43,
      "message": "👍"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 44,
      "message": "u can help me buy one and then auto pass this sr"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 45,
      "message": "i would like to enjoy the game to see what would happen"
    },
    {
      "type": "buy_shares",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 46,
      "shares": [
        "L&N_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 47,
      "shares": [
        "SR_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 48,
      "shares": [
        "GMO_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 49,
      "shares": [
        "GMO_2"
      ],
      "percent": 10
    },
    {
      "id": 50,
      "type": "buy_shares",
      "entity": "kdlecluy",
      "shares": [
        "GMO_3"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 51,
      "type": "undo",
      "entity": "xigema",
      "entity_type": "player"
    },
    {
      "id": 52,
      "type": "buy_shares",
      "entity": "kdlecluy",
      "shares": [
        "L&N_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 53,
      "type": "undo",
      "entity": "xigema",
      "entity_type": "player"
    },
    {
      "id": 54,
      "type": "buy_shares",
      "entity": "kdlecluy",
      "shares": [
        "GMO_3"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 55,
      "type": "undo",
      "entity": "xigema",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 56,
      "shares": [
        "L&N_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 57,
      "shares": [
        "L&N_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 58,
      "shares": [
        "GMO_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 59,
      "shares": [
        "L&N_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 60,
      "shares": [
        "GMO_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 61,
      "shares": [
        "L&N_5"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 62,
      "hex": "B15",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "id": 63,
      "hex": "E10",
      "tile": "58-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 64,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "L&N",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 65,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 66,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 67,
      "hex": "E10",
      "tile": "3-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 68,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "message",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 69,
      "message": "wow, I'm making good use of that undo button :D"
    },
    {
      "type": "message",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 70,
      "message": "lucky we're not playing live :p"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 71,
      "message": "get u turn this right"
    },
    {
      "type": "buy_company",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 72,
      "company": "ETWCR",
      "price": 40
    },
    {
      "type": "lay_tile",
      "entity": "ETWCR",
      "entity_type": "company",
      "id": 73,
      "hex": "F19",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 74,
      "hex": "F17",
      "tile": "5-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 75,
      "hex": "E18",
      "tile": "8-1",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 76,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 78,
      "hex": "H7",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 79,
      "hex": "I6",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 80
    },
    {
      "type": "buy_train",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 81,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 82
    },
    {
      "type": "buy_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 83,
      "shares": [
        "SR_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 85
    },
    {
      "type": "buy_shares",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 86,
      "shares": [
        "SR_6"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "message",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 88,
      "message": "I'm not used to this 'buy only one train per OR' rule. It's throwing off my timing completely."
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 90
    },
    {
      "type": "message",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 91,
      "message": "@kdlecluy: Check out the Info page. There you can when this rule apply. The \"More Info\" link will lead to the wiki page with rule highlights."
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 93
    },
    {
      "id": 94,
      "hex": "D9",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 95,
      "hex": "C8",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 96,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 97,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 98,
      "hex": "D9",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 99,
      "hex": "D7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 100,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B15",
              "B13"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 101,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 102,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 103
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 104,
      "hex": "E20",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 105,
      "hex": "F21",
      "tile": "8-3",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 106,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "E22",
              "E20",
              "E18",
              "F17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 107,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 108,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 109
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 110,
      "hex": "F7",
      "tile": "8-4",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 111,
      "hex": "F9",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "id": 112,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 113,
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 114
    },
    {
      "type": "run_routes",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 115,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "G6",
              "H7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 116,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 117,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_company",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 118,
      "company": "MCR",
      "price": 105
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 119
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 120
    },
    {
      "type": "sell_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 121,
      "shares": [
        "L&N_3",
        "L&N_4",
        "L&N_5"
      ],
      "percent": 30
    },
    {
      "type": "sell_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 122,
      "shares": [
        "GMO_1"
      ],
      "percent": 10
    },
    {
      "id": 123,
      "type": "buy_shares",
      "entity": "xigema",
      "shares": [
        "SR_7"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 124,
      "type": "undo",
      "entity": "ingovals",
      "entity_type": "player"
    },
    {
      "type": "par",
      "entity": "xigema",
      "entity_type": "player",
      "id": 125,
      "corporation": "IC",
      "share_price": "65,3,3"
    },
    {
      "type": "buy_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 126,
      "shares": [
        "SR_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 127
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 128
    },
    {
      "type": "buy_shares",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 129,
      "shares": [
        "L&N_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 130
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 131,
      "shares": [
        "IC_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 132
    },
    {
      "type": "buy_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 133,
      "shares": [
        "SR_8"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 134
    },
    {
      "type": "message",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 135,
      "message": "Unless any shenanigans, selling shares for example, is going on feel free to pass for me rest of this SR if able."
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 136
    },
    {
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 137
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 138,
      "shares": [
        "IC_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 139
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 140
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 141
    },
    {
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 142
    },
    {
      "type": "buy_shares",
      "entity": "xigema",
      "entity_type": "player",
      "id": 143,
      "shares": [
        "IC_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 144
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 145,
      "message": "as i feel.  I  would like to help u"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 146,
      "message": " pass this sr"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 147,
      "message": "so if it is wrong u"
    },
    {
      "type": "message",
      "entity": "xigema",
      "entity_type": "player",
      "id": 148,
      "message": "can undo"
    },
    {
      "type": "pass",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "pass",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 151
    },
    {
      "type": "pass",
      "entity": "xigema",
      "entity_type": "player",
      "id": 152
    },
    {
      "id": 153,
      "hex": "C6",
      "tile": "8-5",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 154,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 155,
      "hex": "D7",
      "tile": "619-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 156,
      "city": "619-0-0",
      "slot": 1,
      "type": "place_token",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 157,
      "type": "run_routes",
      "entity": "L&N",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B15",
              "B13"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E10",
              "D9",
              "D7"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 158,
      "kind": "payout",
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 159,
      "type": "buy_train",
      "price": 180,
      "train": "3-1",
      "entity": "L&N",
      "variant": "3",
      "entity_type": "corporation"
    },
    {
      "id": 160,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 161,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 162,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 163,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 164,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 165,
      "hex": "D7",
      "tile": "619-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 166,
      "city": "619-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 167,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B15",
              "B13"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E10",
              "D9",
              "D7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 168,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 169,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 170
    },
    {
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 172,
      "hex": "F17",
      "tile": "14-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 173,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "E22",
              "E20",
              "E18",
              "F17"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "E22",
              "F21",
              "F19",
              "F17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 174,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 175,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 176
    },
    {
      "type": "buy_company",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 177,
      "company": "TCC",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "id": 179,
      "hex": "C6",
      "tile": "8-5",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 180,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 181,
      "hex": "C6",
      "tile": "8-5",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 182
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 183,
      "train": "3'-0",
      "price": 180,
      "variant": "3'"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 184
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 185
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 186,
      "hex": "F11",
      "tile": "6-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 187,
      "hex": "E12",
      "tile": "9-4",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 188
    },
    {
      "type": "run_routes",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 189,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "G6",
              "F7",
              "F9",
              "F11"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "H7",
              "I6",
              "J5"
            ],
            [
              "G6",
              "H7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 190,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 191
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 192
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 193,
      "hex": "G16",
      "tile": "9-5",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 194
    },
    {
      "type": "run_routes",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 195,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "E22",
              "E20",
              "E18",
              "F17"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "E22",
              "F21",
              "F19",
              "F17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 196,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 197
    },
    {
      "id": 198,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 199,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 200
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 201,
      "hex": "D11",
      "tile": "142-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 202,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B15",
              "B13"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "B13",
              "C12",
              "D11"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "E10",
              "D9",
              "D7"
            ],
            [
              "C4",
              "C6",
              "D7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 203,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 204,
      "train": "3'-1",
      "price": 180,
      "variant": "3'"
    },
    {
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 205
    },
    {
      "type": "lay_tile",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 206,
      "hex": "F11",
      "tile": "TN2-0",
      "rotation": 4
    },
    {
      "type": "place_token",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 207,
      "city": "TN2-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 208,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "G6",
              "F7",
              "F9",
              "F11"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "H7",
              "I6",
              "J5"
            ],
            [
              "G6",
              "H7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 209,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 210
    },
    {
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 211
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 212,
      "hex": "E10",
      "tile": "141-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 213,
      "routes": [
        {
          "train": "3'-0",
          "connections": [
            [
              "C4",
              "C6",
              "D7"
            ],
            [
              "D7",
              "D9",
              "E10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 214,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 215,
      "train": "4-0",
      "price": 300,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 216
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 217,
      "company": "OWR",
      "price": 150
    },
    {
      "type": "sell_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 218,
      "shares": [
        "SR_5",
        "SR_7",
        "SR_8"
      ],
      "percent": 30
    },
    {
      "type": "sell_shares",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 219,
      "shares": [
        "GMO_2"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 220,
      "corporation": "TC",
      "share_price": "90,1,4"
    },
    {
      "type": "sell_shares",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 221,
      "shares": [
        "SR_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 222,
      "shares": [
        "IC_4"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 223,
      "shares": [
        "SR_1"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 224,
      "corporation": "NC&StL",
      "share_price": "80,2,4"
    },
    {
      "type": "undo",
      "entity": "xigema",
      "entity_type": "player",
      "id": 225
    },
    {
      "type": "undo",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 226
    },
    {
      "type": "undo",
      "entity": "Swedish-Per (GMT+2)",
      "entity_type": "player",
      "id": 227
    },
    {
      "type": "undo",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 228
    },
    {
      "type": "undo",
      "entity": "kdlecluy",
      "entity_type": "player",
      "id": 229
    },
    {
      "type": "undo",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 230
    },
    {
      "type": "undo",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 231
    },
    {
      "type": "undo",
      "entity": "ingovals",
      "entity_type": "player",
      "id": 232
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 233
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 234
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 235
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 236
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 237
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 238
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 239
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 240
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 241
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 242
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 243
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 244
    },
    {
      "type": "redo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 245
    },
    {
      "type": "redo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 246
    },
    {
      "type": "redo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 247
    },
    {
      "type": "redo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 248
    },
    {
      "type": "redo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 249
    },
    {
      "type": "redo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 250
    },
    {
      "type": "redo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 251
    },
    {
      "type": "redo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 252
    },
    {
      "type": "redo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 253
    },
    {
      "type": "redo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 254
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 255
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 256
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 257
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 258
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 259
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 260
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 261
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 262
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 263
    },
    {
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation",
      "id": 264
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 265
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 266
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 267
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 268
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 269
    },
    {
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 270
    },
    {
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 271
    },
    {
      "type": "redo",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 272
    },
    {
      "type": "redo",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 273
    },
    {
      "type": "redo",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 274
    },
    {
      "type": "redo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 275
    },
    {
      "type": "redo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 276
    },
    {
      "type": "redo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 277
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 278
    },
    {
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 279
    },
    {
      "type": "run_routes",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 280,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B15",
              "B13"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E10",
              "D9",
              "D7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 281,
      "kind": "payout"
    }
  ],
  "id": "hs_ywlbkdmt_9608",
  "description": "Cloned from game hs_tidfqxzl_9608",
  "user": {
    "id": 0,
    "name": "You"
  },
  "players": [
    {
      "id": 3330,
      "name": "kdlecluy"
    },
    {
      "id": 1048,
      "name": "Swedish-Per (GMT+2)"
    },
    {
      "id": 4024,
      "name": "xigema"
    },
    {
      "id": 3199,
      "name": "ingovals"
    }
  ],
  "max_players": 4,
  "title": "18TN",
  "settings": {
    "seed": 3.105446111274124e+38
  },
  "user_settings": null,
  "turn": 4,
  "round": "Stock Round",
  "acting": [
    4024
  ],
  "result": {},
  "loaded": true,
  "created_at": "2020-09-17",
  "updated_at": 1600338987,
  "mode": "hotseat"
}

### PR DESCRIPTION
**Pull request by perwestling**
If not all trains in a corporation is routed, the non-active trains
are used as the Civil War candidate trains.

### CODE REVIEW

File: lib/engine/game/g_18_tn.rb [hunk 1]
```diff
@@ -80,10 +80,13 @@ def operating_round(round_num)
       def routes_revenue(routes)
         total_revenue = super
 
-        abilities = routes.first&.corporation&.abilities(:civil_war)
+        corporation = routes.first&.corporation
 
-        return total_revenue if !abilities || abilities.empty?
+        abilities = corporation&.abilities(:civil_war)
 
+        return total_revenue if !abilities || abilities.empty? || routes.size < corporation&.trains&.size
```
Comment (tobymao) [inline lib/engine/game/g_18_tn.rb:87]: why don't you do a return unless corporation first

routes.size < corporations&trins&.size will crash if there is no corporation

3 < nil is undefined

Comment (perwestling) [reply lib/engine/game/g_18_tn.rb:87]: Ah, I thought &. would short cut the comparision.

Anyway, it could never happen as if corporation is nil, then abilities would be nil from line 85.
So I have removed both &. in that last one.

Or do you prefer to add a
  return total_revenue unless corporation
before line 85, and remove &. from line 85?

**Review by tobymao — APPROVED** [review]
