### PR TITLE
Fix private exchange when at cert limit.

### LINKED ISSUE #1435: 1836jr - not able to use ability of GCB
Player Bob who owned the GCB was not able to convert it to a share during a stock round - in between player turns of the stock round - or even during the OR. Clearly we missed something obvious in the process. This was our first play of 1836jr. 

{
  "id": 6427,
  "description": "GDoR",
  "user": {
    "id": 285,
    "name": "Panzerlied"
  },
  "players": [
    {
      "id": 2395,
      "name": "theriap"
    },
    {
      "id": 285,
      "name": "Panzerlied"
    },
    {
      "id": 2139,
      "name": "jmay"
    },
    {
      "id": 2111,
      "name": "Bob Theriault"
    }
  ],
  "max_players": 4,
  "title": "1836Jr30",
  "settings": {
    "seed": 1.1298111691408398e+38
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Auction Round",
  "acting": [
    2395
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "theriap",
      "entity_type": "player",
      "id": 1,
      "company": "ACC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 2,
      "company": "E-SF",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "jmay",
      "entity_type": "player",
      "id": 3,
      "company": "CdH",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 4,
      "company": "GCB",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "theriap",
      "entity_type": "player",
      "id": 5,
      "company": "CFL",
      "price": 160
    },
    {
      "type": "bid",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 6,
      "company": "CFLV",
      "price": 220
    },
    {
      "type": "par",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 7,
      "corporation": "Nord",
      "share_price": "90,1,6"
    },
    {
      "type": "par",
      "entity": "jmay",
      "entity_type": "player",
      "id": 8,
      "corporation": "NFL",
      "share_price": "67,5,6"
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 9,
      "shares": [
        "Nord_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "NFL_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "NFL_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "NFL_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "NFL_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "NFL_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "NFL_6"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 17,
      "shares": [
        "NFL_7"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "NFL_8"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "Nord_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 23,
      "hex": "B10",
      "tile": "57-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 24
    },
    {
      "type": "buy_train",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 25,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 29
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 30,
      "hex": "C11",
      "tile": "7-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 31,
      "city": "57-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 32,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 33,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "undo",
      "entity": "theriap",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "sell_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 38,
      "shares": [
        "NFL_1",
        "NFL_4",
        "NFL_8"
      ],
      "percent": 30
    },
    {
      "type": "par",
      "entity": "theriap",
      "entity_type": "player",
      "id": 39,
      "corporation": "HSM",
      "share_price": "82,2,6"
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 40,
      "shares": [
        "HSM_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 43,
      "shares": [
        "HSM_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 45,
      "shares": [
        "HSM_3"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 47,
      "shares": [
        "NFL_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "sell_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 49,
      "shares": [
        "Nord_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 50,
      "shares": [
        "NFL_4"
      ]
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "sell_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 52,
      "shares": [
        "Nord_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 53,
      "shares": [
        "HSM_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 55,
      "shares": [
        "HSM_5"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 57
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 58,
      "shares": [
        "HSM_6"
      ]
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 59
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 60,
      "shares": [
        "NFL_8"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 62
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 64
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 65
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 66,
      "hex": "E7",
      "tile": "57-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "buy_train",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 68,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 70,
      "hex": "B12",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 71,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "A13",
              "B12",
              "C11",
              "B10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 72,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 73
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 75,
      "shares": [
        "HSM_7"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 77
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 78
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 81
    },
    {
      "type": "run_routes",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 82,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "A13",
              "B12",
              "C11",
              "B10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 83,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 85,
      "hex": "F8",
      "tile": "8-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 86,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 88
    },
    {
      "type": "run_routes",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 89,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 90,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 91,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 92
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 93,
      "shares": [
        "HSM_8"
      ]
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "sell_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 97,
      "shares": [
        "NFL_5",
        "NFL_1"
      ],
      "percent": 20
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 98,
      "shares": [
        "Nord_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 99
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 100
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 101,
      "shares": [
        "NFL_5"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 102
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 103,
      "shares": [
        "NFL_1"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 104
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 105,
      "shares": [
        "Nord_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 106
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 107
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 108
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 109
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 110,
      "shares": [
        "Nord_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 111
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 112
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 113
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 114
    },
    {
      "type": "sell_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 115,
      "shares": [
        "HSM_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 116,
      "shares": [
        "Nord_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 117
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 118
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 119
    },
    {
      "type": "sell_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 120,
      "shares": [
        "NFL_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 121,
      "shares": [
        "HSM_1"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 122
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 123
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 124
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 125
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 126
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 127,
      "hex": "F10",
      "tile": "58-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 128,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 129,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E7",
              "F8",
              "F10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 130,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "lay_tile",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 132,
      "hex": "I5",
      "tile": "7-1",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 133,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 134,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "buy_company",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 136,
      "company": "E-SF",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 137
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 138,
      "hex": "B10",
      "tile": "14-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 139,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "A13",
              "B12",
              "C11",
              "B10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 140,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 141,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 142
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 143
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 144,
      "shares": [
        "NFL_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 145
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 146,
      "shares": [
        "Nord_5"
      ]
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 147
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 148,
      "shares": [
        "Nord_6"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 150,
      "shares": [
        "Nord_7"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 151
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 152
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 153
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 154
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 155
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 156,
      "hex": "E5",
      "tile": "59-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 157,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "D6",
              "E5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 158,
      "kind": "payout"
    },
    {
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 159
    },
    {
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 160
    },
    {
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 161
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 162,
      "hex": "E5",
      "tile": "59-0",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 163,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "D6",
              "E5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 164,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 165,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_company",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 166,
      "company": "ACC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 167
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 168
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 169,
      "hex": "A11",
      "tile": "8-1",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 170,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "A13",
              "B12",
              "C11",
              "B10"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "B10",
              "A11",
              "A13"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 171,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 172
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 173
    },
    {
      "type": "lay_tile",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 174,
      "hex": "H4",
      "tile": "57-2",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 175,
      "city": "57-2-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 176,
      "routes": [
        {
          "train": "3-0",
          "connections": [
            [
              "I3",
              "J2"
            ],
            [
              "I3",
              "I5",
              "H4"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 177,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 179
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 180,
      "hex": "D6",
      "tile": "54-0",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 181,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E7",
              "D6"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E5",
              "D6"
            ]
          ]
        },
        {
          "train": "3-2",
          "connections": [
            [
              "E7",
              "F8",
              "F10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 182,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 183
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 184
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 185,
      "hex": "C9",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 186,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "A13",
              "B12",
              "C11",
              "B10"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "B10",
              "A11",
              "A13"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 187,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 188
    },
    {
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 189
    },
    {
      "type": "lay_tile",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 190,
      "hex": "H4",
      "tile": "14-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 191,
      "routes": [
        {
          "train": "3-0",
          "connections": [
            [
              "I3",
              "J2"
            ],
            [
              "I3",
              "I5",
              "H4"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "H6",
              "H4"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 192,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 193
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 194
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 195
    },
    {
      "type": "par",
      "entity": "jmay",
      "entity_type": "player",
      "id": 196,
      "corporation": "NBDS",
      "share_price": "90,1,6"
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 197
    },
    {
      "type": "par",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 198,
      "corporation": "B",
      "share_price": "90,1,6"
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 199
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 200,
      "shares": [
        "NBDS_1"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 201
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 202,
      "shares": [
        "B_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 203
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 204,
      "shares": [
        "NBDS_2"
      ]
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 205
    },
    {
      "type": "buy_shares",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 206,
      "shares": [
        "B_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 207
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 208,
      "shares": [
        "NBDS_3"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 209
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 210,
      "shares": [
        "B_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 211
    },
    {
      "type": "sell_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 212,
      "shares": [
        "Nord_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "jmay",
      "entity_type": "player",
      "id": 213,
      "shares": [
        "NBDS_4"
      ]
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 214
    },
    {
      "type": "undo",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 215
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 216
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 217
    },
    {
      "type": "buy_shares",
      "entity": "theriap",
      "entity_type": "player",
      "id": 218,
      "shares": [
        "NBDS_5"
      ]
    },
    {
      "type": "pass",
      "entity": "theriap",
      "entity_type": "player",
      "id": 219
    },
    {
      "type": "buy_shares",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 220,
      "shares": [
        "B_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Panzerlied",
      "entity_type": "player",
      "id": 221
    },
    {
      "type": "pass",
      "entity": "jmay",
      "entity_type": "player",
      "id": 222
    },
    {
      "type": "pass",
      "entity": "Bob Theriault",
      "entity_type": "player",
      "id": 223
    }
  ],
  "loaded": true,
  "created_at": 1597251911,
  "updated_at": 1597251978
}

JimA

### PR DESCRIPTION
**Pull request by jenf**
Fixes #1435

### CODE REVIEW

File: lib/engine/step/share_buying.rb [hunk 1]
```diff
@@ -17,12 +17,13 @@ def buy_shares(entity, shares, exchange: nil)
       # This works irrespective of if that player has sold this round
       # such as in 1889 for exchanging Dougo
       #
-      def can_gain?(entity, bundle)
+      def can_gain?(entity, bundle, exchanging = false)
```
Comment (perwestling) [inline lib/engine/step/share_buying.rb:20]: I wonder if 
exchange: false 
would be better?

Then it would be called with 
  exchange: true
which is a bit more expressive than just passing a simple true.

File: assets/app/view/game/round/stock.rb [hunk 2]
```diff
@@ -103,28 +103,28 @@ def render_ipoed
...
               children << h(:button, { on: { click: buy_pool } }, 'Buy Market Share')
             end
+          end
 
-            # Allow privates to be exchanged for shares
-            @game.companies.each do |company|
-              company.abilities(:exchange) do |ability|
-                next unless ability.corporation == @selected_corporation.name
-                next unless company.owner == @current_entity
+          # Allow privates to be exchanged for shares
```
Comment (perwestling) [inline assets/app/view/game/round/stock.rb:108]: Very long methods...

Personally I do like extract-method so I would consider a local allow_privates_to_be_exchanged_for_shares method, but that's me.

**Review by perwestling — COMMENTED** [review]
Just two code style comments. Do what you wish with them.

File: assets/app/view/game/round/stock.rb (hunk 2 above)
Comment (jenf) [reply assets/app/view/game/round/stock.rb:108]: Same here, but it'd be a much bigger rewrite to isolate that block

Comment (jenf) [reply assets/app/view/game/round/stock.rb:108]: Same here, but unfortunatly it relies on a lot of variables local to that method.
