### PR TITLE
1846 - corporation closure fixes

### LINKED ISSUE #958: 1846: incomplete company close
Two pieces:

- As the president of the closed company I was allowed to buy the train off of the closed company through my other company. Obviously not allowed

- Also, the market token stayed out on the 0 space not necessarily a bug, but also doesn’t have to be there

### PR DESCRIPTION
**Pull request by michaeljb**
* fix removal of reservations
* prevent buying trains from closed corporations
* remove share price token
* close companies owned by the corporation, and log it; duplicate the array
  since `company.close!` removes it from its owner's `companies`, i.e., `dup` is
  needed to avoid modifying the array that is being iterated over

[Fixes #958]

This game is on PRR's turn at the train buying step, after ERIE closed at action 65 - [958_example.json.txt](https://github.com/tobymao/18xx/files/4874174/958_example.json.txt)

### CODE REVIEW

File: lib/engine/game/g_1846.rb [hunk 1]
```diff
@@ -227,17 +227,23 @@ def action_processed(action)
       end
 
       def close_corporation(corporation)
+        @log << "#{corporation.name} closes"
+
         hexes.each do |hex|
           hex.tile.cities.each do |city|
-            next unless city.tokened_by?(corporation)
+            next unless city.tokened_by?(corporation) || city.reserved_by?(corporation)
```
Comment (tobymao) [inline lib/engine/game/g_1846.rb:234]: don't use unless with multiple statements

File: lib/engine/game/g_1846.rb [hunk 2]
```diff
@@ -227,17 +227,23 @@ def action_processed(action)
...
 
             city.tokens.map! { |token| token&.corporation == corporation ? nil : token }
-            city.reservations.delete(corporation.name)
+            city.reservations.delete(corporation)
           end
         end
 
         corporation.spend(corporation.cash, @bank)
-        @log << "#{corporation.name} closes"
+        corporation.trains.each { |t| t.buyable = false }
```
Comment (tobymao) [inline lib/engine/game/g_1846.rb:242]: how did these trains even show up to get bought?

File: lib/engine/game/g_1846.rb [hunk 3]
```diff
@@ -227,17 +227,23 @@ def action_processed(action)
...
+        if corporation.companies.any?
+          @log << "#{corporation.name}'s companies close: #{corporation.companies.map(&:sym).join(', ')}"
```
Comment (tobymao) [inline lib/engine/game/g_1846.rb:244]: do you think this is necessary?

Comment (michaeljb) [reply lib/engine/game/g_1846.rb:244]: Yes.
I think other events that close companies are logged (some close when used, or the phase change), and I find it useful to log when any entity leaves the game.

File: lib/engine/game/g_1846.rb (hunk 2 above)
Comment (michaeljb) [reply lib/engine/game/g_1846.rb:242]: `Engine::Depot`'s `@trains` still has references to the closed corporation's trains, so they are returned by `Engine::Depot#other_trains`

https://github.com/tobymao/18xx/blob/master/lib/engine/depot.rb#L78-L82

File: lib/engine/game/g_1846.rb (hunk 1 above)
Comment (michaeljb) [reply lib/engine/game/g_1846.rb]: e29161aa
