### PR TITLE
1870: Fix error on closing corporation (fixes #4987)

### LINKED ISSUE #4987: Unable to close company in 1870
I have a company on the verge of closing in 1870, but when I'm taking it there I get an error message. The game is 

https://18xx.games/game/35230

The stock value is 10, so it would go left and close. I've never played 1870 before, but the stock market says "Corporation closes", and I get the message:

Undefined message pass for nil

### PR DESCRIPTION
**Pull request by daniel-sousa-me**
The pass! on PriceProtection may be called during the Stock Round
while on the turn closed corporation and it inherits BuySellParShares

force_next_entity! tries to pass! every step, but we still want to run
through the CheckConnection

### CODE REVIEW

File: lib/engine/game/g_1870/step/check_connection.rb [hunk 1]
```diff
@@ -53,13 +53,17 @@ def actions(_entity)
             ACTIONS
           end
 
+          # This step should not be passed
```
Comment (jenf) [inline lib/engine/game/g_1870/step/check_connection.rb:56]: it'd be better to override operating.rb to change the behaviour to skip force next entity on check_connection.

Comment (daniel-sousa-me) [reply lib/engine/game/g_1870/step/check_connection.rb:56]: That requires copy-pasting the entire function, which is very likely that someone will want to change in the future

**Review by tobymao — APPROVED** [review]
