### PR TITLE
Allow way of abandoning game early, fix end game on hotseat and when undone

### LINKED ISSUE #239: Game not listed after undoing "Declare Bankruptcy"
During e-buy I pressed the "Declare Bankruptcy" button. Once I saw that it ended the game I pressed Undo. The game is still playable however it is no longer listed under Your Games, New Games, Active Games, or Finished Games. I can still access the game through the URL.

https://18xx.games/game/262

[g262_state.txt](https://github.com/tobymao/18xx/files/4561808/g262_state.txt)

### LINKED ISSUE #287: Add method to abandon/conclude/concede game early
Some games may be a foregone conclusion, add a method to allow all parties to agree to abandon the game.

### PR DESCRIPTION
**Pull request by jenf**
* Adds a game end action
* Hotseat games never entered the finish state
* Route wouldn't unapply game end state on pass

fixes #239 
fixes #287

Screenshot from 2020-05-11 21-05-28

### CODE REVIEW

File: assets/app/view/tools.rb [hunk 1]
```diff
@@ -5,8 +5,11 @@
 module View
   class Tools < Snabberb::Component
     include GameManager
+    include Actionable
 
     needs :game, store: true
+    needs :user
+    needs :confirming_conclude_game, store: true, default: false
```
Comment (tobymao) [inline assets/app/view/tools.rb:12]: can you rename this to something shorter

Comment (tobymao) [reply assets/app/view/tools.rb:12]: how does this work, are you able to end games that are already ended?

Comment (jenf) [reply assets/app/view/tools.rb:12]: nope, it checks to see if the game is already finished before showing the option to end the game.
