### PR TITLE
1862: fix display of PD in Parliament rounds

### LINKED ISSUE #6004: 1862 - Parliament Round Priority Deal
If a player acts in the parliament round, it changes where the priority deal marker sits on the players entities cards. During parliament round PD should not change as it reverts back to the original Priority owner at the start of the stock round.

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #6004 

UI only, no pins required.

### CODE REVIEW

File: lib/engine/game/g_1862/game.rb [hunk 1]
```diff
@@ -633,6 +633,26 @@ def remove_marker(corporation)
           hex.tile.icons.delete(marker) if marker
         end
 
+        def priority_deal_player
+          players = @players.reject(&:bankrupt)
+
+          if @round.is_a?(Engine::Game::G1862::Round::Stock)
+            puts "@round: #{@round}, class: #{@round.class.name}"
```
Comment (tobymao) [inline lib/engine/game/g_1862/game.rb:640]: puts
