### PR TITLE
[1822CA] don't recompute `destination_node_check?`

### LINKED ISSUE #10956: [1822CA] Game Won't Let Major Lay Second Yellow Track
Game ID  164866

https://18xx.games/game/164866

ICR was floated in SR 10.  In its operation in OR 10.1 "ICR lays tile #8 with rotation 0 on AP2" just fine, but for each of the several attempts (more than 5) to lay a second yellow tile, the server takes a long time to "accept" the move to advance to the token placement phase.  The wait time between clicking the green check mark to commit the second tile lay to advancing to token placement was so long that two page unresponsive messages offering to close the application or wait for it to respond appeared.  After each of the several times after each of the times the game did move beyond this point to letting the ICR place a token, buy a train, redeem a share, and appear to start the turn of the next RR, red messages were given that updates were not accepted due to refreshing and something like " can't process move 1590".

Here's a screen shot of the attempted tile lay:

image

I didn't seem to experience any trouble in other games taking turns immediately before or after this trouble.  I had taken turns in at least two games immediately before this problem.  I made several attempts in this game as described above.  I started this bug report and copied it into a document.  I closed and reopened my browser.  I made more attempts as described above.  I took turns in other games with no apparent problems.  I rebooted my computer, and I continued to have this problem.

### PR DESCRIPTION
**Pull request by michaeljb**
Closes #10956, but a lot of that issue is caused by #10331.

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### CODE REVIEW

**Comment by michaeljb** [comment]
Reverted this in https://github.com/tobymao/18xx/commit/29f45c5fd8615d63ac301b05d7f7957e70b5a09b to fix 10960

File: lib/engine/game/g_1822_ca/step/destination_token.rb [hunk 1]
```diff
@@ -80,6 +81,8 @@ def process_place_token(action)
           end
 
           def destination_node_check?(entity)
+            return @connected_destination_nodes if @dest_checked
```
Comment (michaeljb) [inline lib/engine/game/g_1822_ca/step/destination_token.rb:84]: This isn't the same thing normally returned by this function.

Fixed in #10964
