### PR TITLE
[1894] fix green->brown upgrade splitting cities when corporation's only token is there

### LINKED ISSUE #11862: [1894] Tile upgrade error: Illegal action: no implicit conversion of nil into Array... refreshing.
Error:
The server did not accept this action due to: Illegal action: no implicit conversion of nil into Array... refreshing.

Game: 1894
ID: 215178
Link: https://18xx.games/game/215178

1894: Phase Brown - Operating Round 4.2 (of 2) - Lay/Upgrade Track
Ouest is trying to upgrade hex B3 to tile #X18

Windows 10 - Firefox 140.0.2 (64-bit)
Android 15 - Brave 1.80.115, Chromium 138.0.7204.97

### PR DESCRIPTION
**Pull request by michaeljb**
cc @Galatolol 

* also fallback to `[]` when `hex_neighbors` returns `nil`, fixes #11862

* also clear graph after placing token via `UpdateTokens` step

    * the graph is already cleared when tokens are placed via the normal step

    * fixes issue where a token is placed as a "cheater", and then no hexes appear visible until a refresh, e.g.:
      1) go to https://18xx.games/game/216595?action=723
      2) use the arrow button to advance the game by one action, to see the
       "cheater" token appear on H9
      3) I8 is not highlighted and appears not accessible to the 'Est' corporation
      4) with a refresh, the graph is completely rebuilt and I8 (and other hexes)
       are correctly highlighted

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### CODE REVIEW

File: lib/engine/game/g_1894/step/track.rb [hunk 1]
```diff
@@ -16,8 +16,12 @@ def actions(entity)
           end
 
           def legal_tile_rotation?(entity, hex, tile)
-            return false if @game.class::GREEN_CITY_TILES.include?(hex.tile.name) &&
-              !tile.exits.intersect?(hex_neighbors(entity, hex))
+            if @game.class::GREEN_CITY_TILES.include?(hex.tile.name)
+              return false if hex.tile.exits.sort != tile.exits.sort
+              return true if hex.tile.cities.first.tokened_by?(entity)
+              return true if @game.saved_tokens_hex == hex && @game.saved_tokens.find { |t| t[:entity] == entity }
```
Comment (ollybh) [inline lib/engine/game/g_1894/step/track.rb]:
```suggestion
              return true if @game.saved_tokens_hex == hex && @game.saved_tokens.any? { |t| t[:entity] == entity }
```
