### PR TITLE
[1850] fix for price protect

### LINKED ISSUE #9041: (1850) Price protection
Rule 5.9.10 indicates a president can price protect even if they sold shares that stock round. Game 116181 disallowed that action.

https://18xx.games/game/116181

### PR DESCRIPTION
**Pull request by bentziaxl**
change price when prez sells

Fixes #9041

### CODE REVIEW

File: lib/engine/game/g_1850/game.rb [hunk 1]
```diff
@@ -331,9 +331,40 @@ def revenue_for(route, stops)
         end
 
         def sell_shares_and_change_price(bundle, allow_president_change: true, swap: nil, movement: nil)
-          @sell_queue << [bundle, bundle.corporation.owner]
+          bundle_owner = bundle.owner
+          @sell_queue << [bundle, bundle.corporation.owner] unless bundle.corporation.president?(bundle_owner)
```
Comment (bentziaxl) [inline lib/engine/game/g_1850/game.rb:336]: add logic here so that if president sells shares, they aren't asked to price protect those shares.

File: lib/engine/game/g_1850/game.rb [hunk 2]
```diff
@@ -331,9 +331,40 @@ def revenue_for(route, stops)
...
 
           @share_pool.sell_shares(bundle)
+
+          change_price(bundle, bundle.corporation.owner) if bundle.corporation.president?(bundle_owner)
+        end
+
+        def change_price(bundle, corporation_owner, forced = false)
+          corporation = bundle.corporation
```
Comment (bentziaxl) [inline lib/engine/game/g_1850/game.rb:343]: this code is taken from 1870 price_protect class made into a method and moved to the games class

File: lib/engine/game/g_1850/step/price_protection.rb [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+            return unless bundle == price_protection
+
+            have_cert_room = if bundle.corporation.counts_for_limit
+                               @game.num_certs(entity, price_protecting: true) + bundle.num_shares <= @game.cert_limit
+                             else
+                               true # can price protect yellow/green/brown even if over cert limit
+                             end
+
+            entity.cash >= bundle.price && have_cert_room
+          end
```
Comment (bentziaxl) [inline lib/engine/game/g_1850/step/price_protection.rb:22]: copied over the can_buy? method from 1870.
In 1870 if player previously sold they can't price protect. 
They can in 1850

**Comment by philcampeau** [comment]
Is it possible that this fix is what's causing the issue in #9659 ?
