### PR TITLE
1862 fixes: merges, map, London highlighting

### LINKED ISSUE #5369: [1862] Merger of Charted and Non-Chartered Company does not preserve Treasury Shares
https://18xx.games/game/42309?action=133

When a chartered and non-chartered company merge, the company should discard 1/2 of it's shares (and undergo the option process as necessary). The current implementation seems to discard all shares to the market.

### LINKED ISSUE #5371: [1862] Unable to Run Train After Merge
https://18xx.games/game/42309?action=461

The ECR merged and is not given an option to run its Freight train.

### LINKED ISSUE #5372: [1862] King's Lynn (C4) Should be a Y City
[title]

See physical board or rulebook for confirmation.

### LINKED ISSUE #5373: [ 1862 ] Hex B13 London Connectivity Issue
When I built track on B13 and the connection to London was connected via the SW offboard arrow. It didn't seem to register that my company was connected to London. When I built it so the connection was directly south. London lit up as if I were connected to it.

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #5369 
Fixes #5371 
Fixes #5372 
Fixes #5373

### CODE REVIEW

**Comment by roseundy** [comment]
Large chance that games will have to be archived due to the map and merger fixes.

File: lib/engine/game/g_1862/game.rb [hunk 1]
```diff
@@ -1898,7 +1898,10 @@ def reorder_shares(shares, corps)
 
         # look for next entity that has needed share
         def find_donor_share(entity, corp, holders, percent)
-          return nil if entity.corporation?
+          if entity.corporation?
+            match = @share_pool.shares_of(corp).find { |s| s.percent == percent }
```
Comment (tobymao) [inline lib/engine/game/g_1862/game.rb:1902]: return @sharepoolsharesof.find...

**Review by tobymao — APPROVED** [review]

File: lib/engine/game/g_1862/game.rb (hunk 1 above)
Comment (roseundy) [reply lib/engine/game/g_1862/game.rb:1902]: OK, I fixed this.
